import json, re, hashlib
from pathlib import Path
root=Path(__file__).resolve().parents[2]
data_dir=root/'web/data'; img_dir=root/'web/images/people'; tools_dir=root/'web/tools'
data_dir.mkdir(parents=True,exist_ok=True); img_dir.mkdir(parents=True,exist_ok=True); tools_dir.mkdir(parents=True,exist_ok=True)
base=json.loads((data_dir/'entries.js').read_text().split('=',1)[1].strip().rstrip(';'))
existing={e['id'] for e in base}

SRC70='https://www.oca.org/saints/lives/1981/01/04/100017-synaxis-of-the-seventy-apostles'
SRCANG='https://www.oca.org/orthodoxy/the-orthodox-faith/doctrine-scripture/the-symbol-of-faith/angels-and-evil-spirits'

def slug(s):
    s=s.lower().replace('—','-').replace('’','').replace("'",'')
    s=re.sub(r'[^a-z0-9]+','-',s).strip('-')
    return s

def mk(id,en,el,cat,role_en,role_el,story_en,story_el,feast_en='Local commemoration varies',feast_el='Η τοπική μνήμη ποικίλλει',scripture='—',prayer_en=None,prayer_el=None,notes_en='',notes_el='',sourceUrl='',sourceLabel='',aliases=None,venerated=True):
    if prayer_en is None:
        if venerated and cat in {'apostle','nt-saint','church-saint','prophet','righteous','forefather'}:
            prayer_en=f'Holy {en}, pray to God for us, that we may grow in faith, repentance, courage, and love.'
            prayer_el=f'Άγιε/Αγία {el}, πρέσβευε στον Θεό για μας, ώστε να αυξανόμαστε σε πίστη, μετάνοια, θάρρος και αγάπη.'
        elif cat=='angel':
            prayer_en=f'Holy {en}, servant of God, help us remain faithful to God and resist evil.'
            prayer_el=f'Άγιε {el}, λειτουργέ του Θεού, βοήθησέ μας να μένουμε πιστοί στον Θεό και να αντιστεκόμαστε στο κακό.'
        elif cat=='feast':
            prayer_en='Lord Jesus Christ, grant us to enter the mystery of this feast with faith, repentance, and thanksgiving.'
            prayer_el='Κύριε Ιησού Χριστέ, αξίωσέ μας να ζήσουμε το μυστήριο αυτής της εορτής με πίστη, μετάνοια και ευχαριστία.'
        else:
            prayer_en='Lord, grant me wisdom to learn from this biblical account, reject what is evil, and choose what is good.'
            prayer_el='Κύριε, δώσε μου σοφία να διδαχθώ από αυτή τη βιβλική διήγηση, να απορρίπτω το κακό και να επιλέγω το αγαθό.'
    status_en='' if venerated else 'This is a biblical context entry, not presented here as a saint or object of veneration. '
    status_el='' if venerated else 'Αυτή είναι καταχώριση βιβλικού πλαισίου και δεν παρουσιάζεται εδώ ως άγιος ή αντικείμενο τιμής. '
    if not notes_en:
        notes_en='This is a concise educational summary. Scripture references and local Orthodox calendars should be consulted for fuller context and commemoration details.'
    if not notes_el:
        notes_el='Πρόκειται για σύντομη εκπαιδευτική περίληψη. Για πληρέστερο πλαίσιο και λεπτομέρειες μνήμης συμβουλευτείτε τη Γραφή και τοπικό ορθόδοξο ημερολόγιο.'
    e={
      'id':id,'name':{'en':en,'el':el},'category':cat,'role':{'en':role_en,'el':role_el},
      'story':{'en':story_en,'el':story_el},'feast':{'en':feast_en,'el':feast_el},'scripture':scripture,
      'prayer':{'en':prayer_en,'el':prayer_el},
      'notes':{'en':status_en+notes_en,'el':status_el+notes_el},
      'aliases':aliases or [],'venerated':venerated,'image':f'web/images/catalog/{id}.svg'
    }
    if sourceUrl: e['sourceUrl']=sourceUrl
    if sourceLabel: e['sourceLabel']=sourceLabel
    e['search']=' '.join([en,el,role_en,role_el,scripture,*e['aliases']])
    return e

expanded=[]; church=[]; feasts=[]; context=[]
def add(bucket,e):
    if e['id'] in existing or any(x['id']==e['id'] for x in expanded+church+feasts+context): return
    bucket.append(e)

# Nine ranks / heavenly powers. Existing Cherubim and Seraphim remain.
angel_ranks=[
('thrones','Thrones','Θρόνοι','One of the nine ranks of bodiless powers','Ένα από τα εννέα τάγματα των Ασωμάτων Δυνάμεων','Orthodox tradition names the Thrones among the nine ranks of bodiless powers, associated with the worship and service of God.','Η ορθόδοξη παράδοση συγκαταλέγει τους Θρόνους στα εννέα τάγματα των Ασωμάτων Δυνάμεων, που υπηρετούν και δοξολογούν τον Θεό.','Colossians 1:16'),
('dominions','Dominions','Κυριότητες','One of the nine ranks of bodiless powers','Ένα από τα εννέα τάγματα των Ασωμάτων Δυνάμεων','The Dominions are named by Orthodox tradition among the heavenly ranks and are understood as servants of the divine order.','Οι Κυριότητες συγκαταλέγονται στην ορθόδοξη παράδοση στα ουράνια τάγματα και νοούνται ως λειτουργοί της θείας τάξεως.','Colossians 1:16'),
('virtues','Virtues','Δυνάμεις','One of the nine ranks of bodiless powers','Ένα από τα εννέα τάγματα των Ασωμάτων Δυνάμεων','The Virtues are one of the traditional nine ranks of bodiless powers in Orthodox teaching.','Οι Δυνάμεις αποτελούν ένα από τα εννέα παραδοσιακά τάγματα των Ασωμάτων Δυνάμεων στην ορθόδοξη διδασκαλία.','Ephesians 1:21; 1 Peter 3:22'),
('powers','Powers','Εξουσίες','One of the nine ranks of bodiless powers','Ένα από τα εννέα τάγματα των Ασωμάτων Δυνάμεων','The Powers are named among the heavenly ranks in Scripture and Orthodox tradition.','Οι Εξουσίες αναφέρονται ανάμεσα στα ουράνια τάγματα στη Γραφή και στην ορθόδοξη παράδοση.','Ephesians 1:21; Colossians 1:16'),
('principalities','Principalities','Αρχές','One of the nine ranks of bodiless powers','Ένα από τα εννέα τάγματα των Ασωμάτων Δυνάμεων','The Principalities are counted among the nine ranks of bodiless powers and are named in the apostolic writings.','Οι Αρχές συγκαταλέγονται στα εννέα τάγματα των Ασωμάτων Δυνάμεων και αναφέρονται στα αποστολικά κείμενα.','Ephesians 1:21; Colossians 1:16'),
('archangels-rank','Archangels','Αρχάγγελοι','One of the nine ranks of bodiless powers','Ένα από τα εννέα τάγματα των Ασωμάτων Δυνάμεων','Archangels are the heavenly rank associated in Scripture and tradition with great messages and spiritual warfare.','Οι Αρχάγγελοι είναι ουράνιο τάγμα που συνδέεται στη Γραφή και την παράδοση με μεγάλα αγγέλματα και πνευματικό αγώνα.','1 Thessalonians 4:16; Jude 9'),
('angels-rank','Angels','Άγγελοι','One of the nine ranks of bodiless powers','Ένα από τα εννέα τάγματα των Ασωμάτων Δυνάμεων','Angels are messengers and servants of God who appear throughout Scripture to guide, protect, announce, and worship.','Οι Άγγελοι είναι αγγελιοφόροι και λειτουργοί του Θεού που εμφανίζονται σε όλη τη Γραφή για να οδηγούν, να προστατεύουν, να αναγγέλλουν και να δοξολογούν.','Psalm 90/91:11; Hebrews 1:14'),
('guardian-angel','Guardian Angel','Φύλακας Άγγελος','Angelic protector in Orthodox prayer and tradition','Αγγελικός φύλακας στην ορθόδοξη προσευχή και παράδοση','Orthodox Christians pray for the protection and guidance of a guardian angel, drawing on biblical images of angelic care.','Οι Ορθόδοξοι Χριστιανοί προσεύχονται για την προστασία και καθοδήγηση του φύλακα αγγέλου, με βάση τις βιβλικές εικόνες αγγελικής φροντίδας.','Psalm 90/91:11; Matthew 18:10'),
]
for row in angel_ranks:
    add(expanded,mk(*row[:3],'angel',*row[3:7],feast_en='8 November — Synaxis of the Bodiless Powers',feast_el='8 Νοεμβρίου — Σύναξη των Ασωμάτων Δυνάμεων',scripture=row[7],sourceUrl=SRCANG,sourceLabel='OCA: Angels and Evil Spirits'))

# Apostles of the Seventy, based on OCA Synaxis list. tuple id,en,el,feast,scripture
seventy=[
('cleopas','Apostle Cleopas','Απόστολος Κλεόπας','30 October','Luke 24:13–35'),('simeon-cleopas','Apostle Simeon son of Cleopas','Απόστολος Συμεών του Κλεόπα','27 April','Early Church tradition; cf. John 19:25'),
('joses-barsabas','Apostle Joses Barsabas (Justus)','Απόστολος Ιωσήφ Βαρσαββάς ο Ιούστος','30 October','Acts 1:23'),('ananias-damascus','Apostle Ananias of Damascus','Απόστολος Ανανίας Δαμασκού','1 October','Acts 9:10–19; 22:12'),
('prochorus','Apostle Prochorus','Απόστολος Πρόχορος','28 July','Acts 6:5'),('nicanor-deacon','Apostle Nicanor','Απόστολος Νικάνωρ','28 July; 28 December','Acts 6:5'),('timon-deacon','Apostle Timon','Απόστολος Τίμων','28 July; 30 December','Acts 6:5'),('parmenas','Apostle Parmenas','Απόστολος Παρμενάς','28 July','Acts 6:5'),
('philemon','Apostle Philemon','Απόστολος Φιλήμων','22 November; 19 February','Philemon 1'),('epaphras','Apostle Epaphras','Απόστολος Επαφράς','22 November; 19 February','Colossians 1:7; 4:12'),('archippus','Apostle Archippus','Απόστολος Άρχιππος','22 November; 19 February','Colossians 4:17; Philemon 2'),('silvanus','Apostle Silvanus','Απόστολος Σιλουανός','30 July','1 Thessalonians 1:1; 1 Peter 5:12'),
('crescens','Apostle Crescens','Απόστολος Κρήσκης','30 July','2 Timothy 4:10'),('crispus','Apostle Crispus','Απόστολος Κρίσπος','30 July','Acts 18:8; 1 Corinthians 1:14'),('epaenetus','Apostle Epaenetus','Απόστολος Επαίνετος','30 July','Romans 16:5'),('andronicus','Apostle Andronicus','Απόστολος Ανδρόνικος','17 May; 30 July','Romans 16:7'),
('stachys','Apostle Stachys','Απόστολος Στάχυς','31 October','Romans 16:9'),('amplias','Apostle Amplias','Απόστολος Αμπλίας','31 October','Romans 16:8'),('urban-apostle','Apostle Urban','Απόστολος Ουρβανός','31 October','Romans 16:9'),('narcissus-apostle','Apostle Narcissus','Απόστολος Νάρκισσος','31 October','Romans 16:11'),('apelles','Apostle Apelles','Απόστολος Απελλής','31 October','Romans 16:10'),('aristobulus','Apostle Aristobulus','Απόστολος Αριστόβουλος','16 March; 31 October','Orthodox tradition; Romans 16 circle'),
('herodion','Apostle Herodion (Rodion)','Απόστολος Ηρωδίων (Ροδίων)','8 April; 10 November','Romans 16:11'),('agabus','Apostle Agabus','Απόστολος Άγαβος','8 April','Acts 11:28; 21:10–11'),('rufus','Apostle Rufus','Απόστολος Ρούφος','8 April','Romans 16:13'),('asyncritus','Apostle Asyncritus','Απόστολος Ασύγκριτος','8 April','Romans 16:14'),('phlegon','Apostle Phlegon','Απόστολος Φλέγων','8 April','Romans 16:14'),('hermas','Apostle Hermas','Απόστολος Ερμάς','5 November; 30 November; 31 May','Romans 16:14'),('patrobas','Apostle Patrobas','Απόστολος Πατρόβας','5 November','Romans 16:14'),('hermes-apostle','Apostle Hermes','Απόστολος Ερμής','8 April','Romans 16:14'),
('linus','Apostle Linus','Απόστολος Λίνος','5 November','2 Timothy 4:21'),('gaius-apostle','Apostle Gaius','Απόστολος Γάιος','5 November','Romans 16:23; 1 Corinthians 1:14'),('philologus','Apostle Philologus','Απόστολος Φιλόλογος','5 November','Romans 16:15'),('lucius-cyrene','Apostle Lucius of Cyrene','Απόστολος Λούκιος Κυρηναίος','10 September','Acts 13:1; Romans 16:21'),('jason','Apostle Jason','Απόστολος Ιάσων','28 April','Acts 17:5–9; Romans 16:21'),('sosipater','Apostle Sosipater','Απόστολος Σωσίπατρος','28 April; 10 November','Romans 16:21'),
('olympas','Apostle Olympas','Απόστολος Ολυμπάς','10 November','Romans 16:15 tradition'),('tertius','Apostle Tertius','Απόστολος Τέρτιος','30 October; 10 November','Romans 16:22'),('erastus','Apostle Erastus','Απόστολος Έραστος','30 November','Romans 16:23; 2 Timothy 4:20'),('quartus','Apostle Quartus','Απόστολος Κούαρτος','10 November','Romans 16:23'),('euodius','Apostle Euodius','Απόστολος Ευόδιος','7 September','Early Antiochian tradition'),('onesiphorus','Apostle Onesiphorus','Απόστολος Ονησιφόρος','7 September; 8 December','2 Timothy 1:16–18; 4:19'),
('clement-rome-apostle','Apostle Clement of Rome','Απόστολος Κλήμης Ρώμης','25 November','Philippians 4:3 (traditional identification)'),('sosthenes','Apostle Sosthenes','Απόστολος Σωσθένης','8 December','Acts 18:17; 1 Corinthians 1:1'),('tychicus','Apostle Tychicus','Απόστολος Τυχικός','8 December','Ephesians 6:21; Colossians 4:7'),('carpus','Apostle Carpus','Απόστολος Κάρπος','26 May','2 Timothy 4:13'),('quadratus','Apostle Quadratus','Απόστολος Κοδράτος','21 September','Early Church tradition'),
('john-mark-seventy','Apostle John Mark','Απόστολος Ιωάννης Μάρκος','27 September','Acts 12:12,25; 15:37'),('zenas','Apostle Zenas','Απόστολος Ζηνάς','27 September','Titus 3:13'),('aristarchus','Apostle Aristarchus','Απόστολος Αρίσταρχος','15 April; 27 September','Acts 19:29; Colossians 4:10'),('pudens','Apostle Pudens','Απόστολος Πούδης','15 April','2 Timothy 4:21'),('trophimus','Apostle Trophimus','Απόστολος Τρόφιμος','15 April','Acts 20:4; 21:29; 2 Timothy 4:20'),('mark-barnabas-nephew','Apostle Mark, kinsman of Barnabas','Απόστολος Μάρκος, συγγενής του Βαρνάβα','30 October','Colossians 4:10'),('artemas','Apostle Artemas','Απόστολος Αρτεμάς','30 October','Titus 3:12'),('fortunatus','Apostle Fortunatus','Απόστολος Φορτουνάτος','15 June','1 Corinthians 16:17'),('achaicus','Apostle Achaicus','Απόστολος Αχαϊκός','4 January','1 Corinthians 16:17'),('cephas-seventy','Apostle Cephas of the Seventy','Απόστολος Κηφάς των Εβδομήκοντα','4 January','1 Corinthians 15:5 — traditional identification'),('simeon-niger','Apostle Simeon called Niger','Απόστολος Συμεών ο Νίγερ','4 January','Acts 13:1'),
]
for id,en,el,fd,sc in seventy:
    story_en=f'{en} is honored in Orthodox tradition among the Seventy Apostles, the wider circle of disciples sent by Christ to proclaim the Kingdom. The New Testament or early Church tradition connects this disciple with the apostolic mission.'
    story_el=f'Ο {el} τιμάται στην ορθόδοξη παράδοση ανάμεσα στους Εβδομήκοντα Αποστόλους, τον ευρύτερο κύκλο μαθητών που απέστειλε ο Χριστός για να κηρύξουν τη Βασιλεία. Η Καινή Διαθήκη ή η αρχαία εκκλησιαστική παράδοση τον συνδέει με την αποστολική διακονία.'
    add(expanded,mk(id,en,el,'apostle','Apostle of the Seventy','Απόστολος εκ των Εβδομήκοντα',story_en,story_el,fd,fd,sc,notes_en='The ancient lists of the Seventy are not identical; this catalog follows the Orthodox Church in America Synaxis list and notes that traditional lists can differ.',notes_el='Οι αρχαίοι κατάλογοι των Εβδομήκοντα δεν είναι απολύτως ταυτόσημοι· ο κατάλογος εδώ ακολουθεί τη Σύναξη της Orthodox Church in America και σημειώνει ότι οι παραδόσεις μπορεί να διαφέρουν.',sourceUrl=SRC70,sourceLabel='OCA: Synaxis of the Seventy Apostles'))

# Additional biblical holy figures / forefathers / righteous / prophets.
forefathers=[
('lot','Righteous Lot','Δίκαιος Λωτ','Nephew of Abraham','Ανεψιός του Αβραάμ','Lot traveled with Abraham and was rescued from Sodom; Scripture remembers both his deliverance and the moral dangers surrounding his household.','Ο Λωτ πορεύθηκε με τον Αβραάμ και σώθηκε από τα Σόδομα· η Γραφή θυμάται τόσο τη σωτηρία του όσο και τους ηθικούς κινδύνους γύρω από τον οίκο του.','Genesis 11–19; 2 Peter 2:7–8'),
('reuben','Reuben, son of Jacob','Ρουβήν, υιός Ιακώβ','Son of Jacob and Leah','Υιός του Ιακώβ και της Λείας','Reuben was Jacob’s firstborn and became the ancestor of the tribe bearing his name.','Ο Ρουβήν ήταν ο πρωτότοκος του Ιακώβ και έγινε πρόγονος της φυλής που έφερε το όνομά του.','Genesis 29:32; 35:23; 49:3–4'),
('simeon-patriarch','Simeon, son of Jacob','Συμεών, υιός Ιακώβ','Patriarch of a tribe of Israel','Πατριάρχης φυλής του Ισραήλ','Simeon was a son of Jacob and Leah and ancestor of the tribe of Simeon.','Ο Συμεών ήταν υιός του Ιακώβ και της Λείας και πρόγονος της φυλής Συμεών.','Genesis 29:33; 35:23; 49:5–7'),
('levi-patriarch','Levi, son of Jacob','Λευί, υιός Ιακώβ','Ancestor of the Levitical priestly tribe','Πρόγονος της ιερατικής φυλής του Λευί','Levi was a son of Jacob and Leah; the Levites and the priestly house of Aaron descended from his line.','Ο Λευί ήταν υιός του Ιακώβ και της Λείας· από τη γενιά του προήλθαν οι Λευίτες και ο ιερατικός οίκος του Ααρών.','Genesis 29:34; Exodus 6:16–20'),
('judah-patriarch','Judah, son of Jacob','Ιούδας, υιός Ιακώβ','Forefather of the royal and messianic line','Προπάτορας της βασιλικής και μεσσιανικής γενιάς','Judah became the forefather of the royal line of David and, according to the flesh, of Christ.','Ο Ιούδας έγινε προπάτορας της βασιλικής γενιάς του Δαβίδ και, κατά σάρκα, του Χριστού.','Genesis 29:35; 49:8–12; Matthew 1'),
('dan-patriarch','Dan, son of Jacob','Δαν, υιός Ιακώβ','Patriarch of a tribe of Israel','Πατριάρχης φυλής του Ισραήλ','Dan was a son of Jacob by Bilhah and ancestor of the tribe of Dan.','Ο Δαν ήταν υιός του Ιακώβ από τη Βαλλά και πρόγονος της φυλής Δαν.','Genesis 30:6; 35:25'),
('naphtali','Naphtali, son of Jacob','Νεφθαλί, υιός Ιακώβ','Patriarch of a tribe of Israel','Πατριάρχης φυλής του Ισραήλ','Naphtali was a son of Jacob by Bilhah and ancestor of the tribe of Naphtali.','Ο Νεφθαλί ήταν υιός του Ιακώβ από τη Βαλλά και πρόγονος της φυλής Νεφθαλί.','Genesis 30:8; 35:25'),
('gad-patriarch','Gad, son of Jacob','Γαδ, υιός Ιακώβ','Patriarch of a tribe of Israel','Πατριάρχης φυλής του Ισραήλ','Gad was a son of Jacob by Zilpah and ancestor of the tribe of Gad.','Ο Γαδ ήταν υιός του Ιακώβ από τη Ζελφά και πρόγονος της φυλής Γαδ.','Genesis 30:11; 35:26'),
('asher-patriarch','Asher, son of Jacob','Ασήρ, υιός Ιακώβ','Patriarch of a tribe of Israel','Πατριάρχης φυλής του Ισραήλ','Asher was a son of Jacob by Zilpah and ancestor of the tribe of Asher.','Ο Ασήρ ήταν υιός του Ιακώβ από τη Ζελφά και πρόγονος της φυλής Ασήρ.','Genesis 30:13; 35:26'),
('issachar','Issachar, son of Jacob','Ισσάχαρ, υιός Ιακώβ','Patriarch of a tribe of Israel','Πατριάρχης φυλής του Ισραήλ','Issachar was a son of Jacob and Leah and ancestor of the tribe of Issachar.','Ο Ισσάχαρ ήταν υιός του Ιακώβ και της Λείας και πρόγονος της φυλής Ισσάχαρ.','Genesis 30:18; 35:23'),
('zebulun','Zebulun, son of Jacob','Ζαβουλών, υιός Ιακώβ','Patriarch of a tribe of Israel','Πατριάρχης φυλής του Ισραήλ','Zebulun was a son of Jacob and Leah and ancestor of the tribe of Zebulun.','Ο Ζαβουλών ήταν υιός του Ιακώβ και της Λείας και πρόγονος της φυλής Ζαβουλών.','Genesis 30:20; 35:23'),
('benjamin-patriarch','Benjamin, son of Jacob','Βενιαμίν, υιός Ιακώβ','Patriarch of a tribe of Israel','Πατριάρχης φυλής του Ισραήλ','Benjamin was the younger son of Jacob and Rachel and ancestor of the tribe of Benjamin.','Ο Βενιαμίν ήταν ο νεότερος υιός του Ιακώβ και της Ραχήλ και πρόγονος της φυλής Βενιαμίν.','Genesis 35:18; 49:27'),
('ephraim','Ephraim, son of Joseph','Εφραίμ, υιός Ιωσήφ','Forefather of a tribe of Israel','Προπάτορας φυλής του Ισραήλ','Ephraim, son of Joseph and Asenath, received Jacob’s blessing and became ancestor of a major tribe of Israel.','Ο Εφραίμ, υιός του Ιωσήφ και της Ασενέθ, έλαβε την ευλογία του Ιακώβ και έγινε πρόγονος μεγάλης φυλής του Ισραήλ.','Genesis 41:52; 48'),
('manasseh-joseph','Manasseh, son of Joseph','Μανασσής, υιός Ιωσήφ','Forefather of a tribe of Israel','Προπάτορας φυλής του Ισραήλ','Manasseh was Joseph’s firstborn and became ancestor of the tribe of Manasseh.','Ο Μανασσής ήταν ο πρωτότοκος του Ιωσήφ και έγινε πρόγονος της φυλής Μανασσή.','Genesis 41:51; 48'),
('tamar-judah','Tamar','Θάμαρ','Foremother in the genealogy of Christ','Προμήτωρ στη γενεαλογία του Χριστού','Tamar appears in Judah’s family story and is named in the genealogy of Christ in Matthew.','Η Θάμαρ εμφανίζεται στην οικογενειακή ιστορία του Ιούδα και ονομάζεται στη γενεαλογία του Χριστού κατά Ματθαίον.','Genesis 38; Matthew 1:3'),
('perez','Perez','Φαρές','Ancestor in the genealogy of Christ','Πρόγονος στη γενεαλογία του Χριστού','Perez, son of Judah and Tamar, stands in the biblical line leading to David and Christ.','Ο Φαρές, υιός του Ιούδα και της Θάμαρ, βρίσκεται στη βιβλική γενιά που οδηγεί στον Δαβίδ και στον Χριστό.','Genesis 38:29; Matthew 1:3'),
('hezron','Hezron','Εσρώμ','Ancestor in the genealogy of Christ','Πρόγονος στη γενεαλογία του Χριστού','Hezron is named in the ancestral line of Judah that leads to King David and Christ.','Ο Εσρώμ αναφέρεται στην προγονική γενιά του Ιούδα που οδηγεί στον βασιλιά Δαβίδ και στον Χριστό.','Ruth 4:18–22; Matthew 1:3'),
('ram-ancestor','Ram','Αράμ','Ancestor in the genealogy of Christ','Πρόγονος στη γενεαλογία του Χριστού','Ram is named in the genealogy linking the tribe of Judah to David and Christ.','Ο Αράμ αναφέρεται στη γενεαλογία που συνδέει τη φυλή του Ιούδα με τον Δαβίδ και τον Χριστό.','Ruth 4:19; Matthew 1:3–4'),
('amminadab','Amminadab','Αμιναδάβ','Ancestor in the genealogy of Christ','Πρόγονος στη γενεαλογία του Χριστού','Amminadab is remembered in the genealogy of Judah and the ancestry of Christ.','Ο Αμιναδάβ μνημονεύεται στη γενεαλογία του Ιούδα και στους προγόνους του Χριστού.','Ruth 4:19–20; Matthew 1:4'),
('nahshon','Nahshon','Ναασσών','Leader of Judah and ancestor of Christ','Άρχοντας του Ιούδα και πρόγονος του Χριστού','Nahshon was a leader of Judah in the wilderness and is named among Christ’s ancestors.','Ο Ναασσών ήταν άρχοντας του Ιούδα στην έρημο και αναφέρεται ανάμεσα στους προγόνους του Χριστού.','Numbers 1:7; Matthew 1:4'),
('salmon-ancestor','Salmon','Σαλμών','Ancestor in the genealogy of Christ','Πρόγονος στη γενεαλογία του Χριστού','Salmon is named in the genealogy of Christ as the father of Boaz.','Ο Σαλμών αναφέρεται στη γενεαλογία του Χριστού ως πατέρας του Βοόζ.','Ruth 4:20–21; Matthew 1:4–5'),
('obed','Obed','Ωβήδ','Son of Boaz and Ruth; grandfather of David','Υιός του Βοόζ και της Ρουθ· παππούς του Δαβίδ','Obed was born to Boaz and Ruth and became the father of Jesse and grandfather of King David.','Ο Ωβήδ γεννήθηκε από τον Βοόζ και τη Ρουθ και έγινε πατέρας του Ιεσσαί και παππούς του βασιλιά Δαβίδ.','Ruth 4:17,21–22; Matthew 1:5'),
('jesse','Jesse','Ιεσσαί','Father of King David','Πατέρας του βασιλιά Δαβίδ','Jesse of Bethlehem was the father of David; the prophets use the “root of Jesse” as a messianic image fulfilled in Christ.','Ο Ιεσσαί από τη Βηθλεέμ ήταν πατέρας του Δαβίδ· οι προφήτες χρησιμοποιούν τη «ρίζα του Ιεσσαί» ως μεσσιανική εικόνα που εκπληρώνεται στον Χριστό.','1 Samuel 16; Isaiah 11:1; Matthew 1:6'),
('rehoboam','Rehoboam','Ροβοάμ','King of Judah and ancestor of Christ','Βασιλιάς του Ιούδα και πρόγονος του Χριστού','Rehoboam, son of Solomon, ruled Judah after the division of the kingdom and appears in Matthew’s genealogy of Christ.','Ο Ροβοάμ, υιός του Σολομώντα, βασίλεψε στον Ιούδα μετά τη διαίρεση του βασιλείου και εμφανίζεται στη γενεαλογία του Χριστού κατά Ματθαίον.','1 Kings 12; Matthew 1:7'),
('abijah-king','Abijah (Abia), King of Judah','Αβιά, βασιλιάς Ιούδα','King of Judah and ancestor of Christ','Βασιλιάς του Ιούδα και πρόγονος του Χριστού','Abijah reigned in Judah and is named in the royal genealogy leading to Christ.','Ο Αβιά βασίλεψε στον Ιούδα και αναφέρεται στη βασιλική γενεαλογία που οδηγεί στον Χριστό.','1 Kings 15:1–8; Matthew 1:7'),
('asa-king','Asa, King of Judah','Ασά, βασιλιάς Ιούδα','Reforming king and ancestor of Christ','Μεταρρυθμιστής βασιλιάς και πρόγονος του Χριστού','Asa is remembered for religious reforms in Judah and appears in the genealogy of Christ.','Ο Ασά μνημονεύεται για θρησκευτικές μεταρρυθμίσεις στον Ιούδα και εμφανίζεται στη γενεαλογία του Χριστού.','1 Kings 15:9–24; Matthew 1:7'),
('jehoshaphat','Jehoshaphat','Ιωσαφάτ','King of Judah and ancestor of Christ','Βασιλιάς του Ιούδα και πρόγονος του Χριστού','Jehoshaphat sought the Lord and strengthened worship in Judah; he is in the royal genealogy of Christ.','Ο Ιωσαφάτ αναζήτησε τον Κύριο και ενίσχυσε τη λατρεία στον Ιούδα· βρίσκεται στη βασιλική γενεαλογία του Χριστού.','1 Kings 22; 2 Chronicles 17–20; Matthew 1:8'),
('joram-king','Joram (Jehoram), King of Judah','Ιωράμ, βασιλιάς Ιούδα','King of Judah and ancestor in Matthew’s genealogy','Βασιλιάς του Ιούδα και πρόγονος στη γενεαλογία του Ματθαίου','Joram ruled Judah and is named in the compressed royal genealogy in Matthew.','Ο Ιωράμ βασίλεψε στον Ιούδα και αναφέρεται στη συνοπτική βασιλική γενεαλογία του Ματθαίου.','2 Kings 8:16–24; Matthew 1:8'),
('uzziah','Uzziah (Azariah)','Οζίας (Αζαρίας)','King of Judah and ancestor of Christ','Βασιλιάς του Ιούδα και πρόγονος του Χριστού','Uzziah had a long reign in Judah and appears in Christ’s royal genealogy.','Ο Οζίας είχε μακρά βασιλεία στον Ιούδα και εμφανίζεται στη βασιλική γενεαλογία του Χριστού.','2 Kings 15; 2 Chronicles 26; Matthew 1:8–9'),
('jotham','Jotham','Ιωάθαμ','King of Judah and ancestor of Christ','Βασιλιάς του Ιούδα και πρόγονος του Χριστού','Jotham reigned in Judah and is named in Matthew’s genealogy.','Ο Ιωάθαμ βασίλεψε στον Ιούδα και αναφέρεται στη γενεαλογία του Ματθαίου.','2 Kings 15:32–38; Matthew 1:9'),
('ahaz','Ahaz','Άχαζ','King of Judah in the genealogy of Christ','Βασιλιάς του Ιούδα στη γενεαλογία του Χριστού','Ahaz ruled Judah during Isaiah’s ministry and is part of the genealogy leading to Christ, despite his grave failures.','Ο Άχαζ βασίλεψε στον Ιούδα κατά τη διακονία του Ησαΐα και αποτελεί μέρος της γενεαλογίας που οδηγεί στον Χριστό, παρά τις σοβαρές πτώσεις του.','2 Kings 16; Isaiah 7; Matthew 1:9'),
('manasseh-king','Manasseh, King of Judah','Μανασσής, βασιλιάς Ιούδα','Penitent king and ancestor of Christ','Μετανοημένος βασιλιάς και πρόγονος του Χριστού','Manasseh is remembered for severe apostasy and, in Chronicles, profound repentance and prayer; he is an ancestor of Christ.','Ο Μανασσής μνημονεύεται για βαριά αποστασία και, στα Χρονικά, για βαθιά μετάνοια και προσευχή· είναι πρόγονος του Χριστού.','2 Kings 21; 2 Chronicles 33; Prayer of Manasseh; Matthew 1:10'),
('amon-king','Amon, King of Judah','Αμών, βασιλιάς Ιούδα','King of Judah in the genealogy of Christ','Βασιλιάς του Ιούδα στη γενεαλογία του Χριστού','Amon was the son of Manasseh and father of Josiah, and appears in Christ’s royal genealogy.','Ο Αμών ήταν υιός του Μανασσή και πατέρας του Ιωσία και εμφανίζεται στη βασιλική γενεαλογία του Χριστού.','2 Kings 21:19–26; Matthew 1:10'),
('jeconiah','Jeconiah (Jehoiachin)','Ιεχονίας','Exiled king in the genealogy of Christ','Εξόριστος βασιλιάς στη γενεαλογία του Χριστού','Jeconiah was carried into Babylonian exile and is named at a turning point in Matthew’s genealogy.','Ο Ιεχονίας οδηγήθηκε στη βαβυλώνια αιχμαλωσία και αναφέρεται σε κομβικό σημείο της γενεαλογίας του Ματθαίου.','2 Kings 24:8–17; Matthew 1:11–12'),
('shealtiel','Shealtiel','Σαλαθιήλ','Ancestor after the Babylonian exile','Πρόγονος μετά τη βαβυλώνια αιχμαλωσία','Shealtiel belongs to the post-exilic line in the genealogy leading to Christ.','Ο Σαλαθιήλ ανήκει στη μεταεξορική γενιά της γενεαλογίας που οδηγεί στον Χριστό.','Ezra 3:2; Matthew 1:12'),
('zerubbabel','Zerubbabel','Ζοροβάβελ','Leader of the return from exile; ancestor of Christ','Ηγέτης της επιστροφής από την εξορία· πρόγονος του Χριστού','Zerubbabel helped lead the returned exiles and the rebuilding of the Temple and appears in Christ’s genealogy.','Ο Ζοροβάβελ βοήθησε να ηγηθεί της επιστροφής των εξορίστων και της ανοικοδόμησης του Ναού και εμφανίζεται στη γενεαλογία του Χριστού.','Ezra 2–5; Haggai 1–2; Matthew 1:12–13'),
]
for id,en,el,ren,rel,sen,sel,sc in forefathers:
    add(expanded,mk(id,en,el,'forefather',ren,rel,sen,sel,'Sunday of the Holy Forefathers / Ancestors; local calendar varies','Κυριακή των Αγίων Προπατόρων / Προγόνων· ανάλογα με το ημερολόγιο',sc,notes_en='Included as part of the biblical ancestry remembered in Orthodox Scripture and liturgical tradition; individual commemorations can vary.',notes_el='Περιλαμβάνεται ως μέρος της βιβλικής προγονικής μνήμης στην Ορθόδοξη Γραφή και λατρευτική παράδοση· οι ατομικές μνήμες μπορεί να διαφέρουν.'))

more_holy=[
('nathan-prophet','Prophet Nathan','Προφήτης Νάθαν','prophet','Prophet in the reign of David','Προφήτης επί βασιλείας Δαβίδ','Nathan confronted David after his sin, conveyed God’s promises concerning David’s house, and took part in Solomon’s succession.','Ο Νάθαν έλεγξε τον Δαβίδ μετά την αμαρτία του, μετέφερε τις υποσχέσεις του Θεού για τον οίκο του Δαβίδ και συμμετείχε στη διαδοχή του Σολομώντα.','2 Samuel 7; 12; 1 Kings 1'),
('gad-prophet','Prophet Gad','Προφήτης Γαδ','prophet','Prophet and seer associated with David','Προφήτης και βλέπων συνδεδεμένος με τον Δαβίδ','Gad served as a prophetic adviser to David and delivered God’s word at decisive moments.','Ο Γαδ υπηρέτησε ως προφητικός σύμβουλος του Δαβίδ και μετέφερε τον λόγο του Θεού σε κρίσιμες στιγμές.','1 Samuel 22:5; 2 Samuel 24'),
('huldah','Prophetess Huldah','Προφήτις Όλδα','prophet','Prophetess in Jerusalem during Josiah’s reign','Προφήτις στην Ιερουσαλήμ επί Ιωσία','Huldah authenticated the Book of the Law found in the Temple and announced God’s judgment and mercy during Josiah’s reforms.','Η προφήτις Όλδα επιβεβαίωσε το Βιβλίο του Νόμου που βρέθηκε στον Ναό και ανήγγειλε κρίση και έλεος του Θεού κατά τις μεταρρυθμίσεις του Ιωσία.','2 Kings 22:14–20; 2 Chronicles 34:22–28'),
('othniel','Righteous Othniel','Δίκαιος Γοθονιήλ','righteous','Judge and deliverer of Israel','Κριτής και ελευθερωτής του Ισραήλ','Othniel, related to Caleb, became the first judge named in Judges and delivered Israel from oppression.','Ο Γοθονιήλ, συγγενής του Χάλεβ, έγινε ο πρώτος ονομαζόμενος κριτής στο βιβλίο των Κριτών και ελευθέρωσε τον Ισραήλ από καταπίεση.','Judges 3:7–11'),
('ehud','Righteous Ehud','Δίκαιος Αώδ','righteous','Judge and deliverer of Israel','Κριτής και ελευθερωτής του Ισραήλ','Ehud was raised up as a judge who freed Israel from Moabite domination.','Ο Αώδ αναδείχθηκε κριτής και ελευθέρωσε τον Ισραήλ από την κυριαρχία των Μωαβιτών.','Judges 3:12–30'),
('jael','Jael','Ιαήλ','righteous','Woman associated with Deborah’s deliverance','Γυναίκα συνδεδεμένη με τη σωτηρία επί Δεββώρας','Jael played a decisive role in the defeat of Sisera and is praised in the Song of Deborah.','Η Ιαήλ έπαιξε αποφασιστικό ρόλο στην ήττα του Σισάρα και εγκωμιάζεται στο άσμα της Δεββώρας.','Judges 4–5'),
('eli-priest','Eli the Priest','Ηλί ο ιερέας','righteous','Priest and judge at Shiloh','Ιερέας και κριτής στη Σηλώ','Eli served at the sanctuary of Shiloh, blessed Hannah, and raised the young Samuel, though Scripture also records his failures to restrain his sons.','Ο Ηλί υπηρετούσε στο ιερό της Σηλώ, ευλόγησε την Άννα και ανέθρεψε τον νεαρό Σαμουήλ, αν και η Γραφή καταγράφει και την αποτυχία του να συγκρατήσει τους υιούς του.','1 Samuel 1–4'),
('jonathan-son-saul','Jonathan, son of Saul','Ιωνάθαν, υιός Σαούλ','righteous','Friend of David and prince of Israel','Φίλος του Δαβίδ και άρχοντας του Ισραήλ','Jonathan showed courage, covenant loyalty, and selfless friendship toward David despite the conflict with his father Saul.','Ο Ιωνάθαν έδειξε θάρρος, πιστότητα στη διαθήκη και ανιδιοτελή φιλία προς τον Δαβίδ παρά τη σύγκρουση με τον πατέρα του Σαούλ.','1 Samuel 13–14; 18–20; 31'),
('abigail','Righteous Abigail','Δικαία Αβιγαία','righteous','Wise woman who became wife of David','Σοφή γυναίκα που έγινε σύζυγος του Δαβίδ','Abigail prevented bloodshed through courage and wisdom and later became David’s wife.','Η Αβιγαία απέτρεψε αιματοχυσία με θάρρος και σοφία και αργότερα έγινε σύζυγος του Δαβίδ.','1 Samuel 25'),
('bathsheba','Bathsheba','Βηρσαβεέ','forefather','Mother of King Solomon','Μητέρα του βασιλιά Σολομώντα','Bathsheba became the mother of Solomon and stands within the royal ancestry remembered in Matthew’s genealogy of Christ.','Η Βηρσαβεέ έγινε μητέρα του Σολομώντα και βρίσκεται στη βασιλική προγονική γραμμή που μνημονεύεται στη γενεαλογία του Χριστού κατά Ματθαίον.','2 Samuel 11–12; 1 Kings 1–2; Matthew 1:6'),
('mattathias-maccabee','Mattathias the Hasmonean','Ματταθίας ο Ασμοναίος','righteous','Priestly leader of the Maccabean resistance','Ιερατικός ηγέτης της μακκαβαϊκής αντίστασης','Mattathias resisted forced apostasy under Seleucid persecution and inspired the Maccabean struggle for faithfulness to the Law.','Ο Ματταθίας αντιστάθηκε στον εξαναγκασμό σε αποστασία κατά τον σελευκιδικό διωγμό και ενέπνευσε τον μακκαβαϊκό αγώνα για πιστότητα στον Νόμο.','1 Maccabees 2'),
('judas-maccabeus','Judas Maccabeus','Ιούδας Μακκαβαίος','righteous','Leader of the Maccabean revolt','Ηγέτης της μακκαβαϊκής εξέγερσης','Judas Maccabeus led the faithful in battle, cleansed the Temple, and restored its worship after desecration.','Ο Ιούδας Μακκαβαίος ηγήθηκε των πιστών στον αγώνα, καθάρισε τον Ναό και αποκατέστησε τη λατρεία μετά τη βεβήλωση.','1 Maccabees 3–4; 2 Maccabees 8–12'),
('tabitha','Righteous Tabitha (Dorcas)','Δικαία Ταβιθά (Δορκάς)','nt-saint','Disciple known for works of mercy','Μαθήτρια γνωστή για έργα ελεημοσύνης','Tabitha of Joppa was a disciple renowned for good works and almsgiving; Peter raised her from death by prayer.','Η Ταβιθά από την Ιόππη ήταν μαθήτρια γνωστή για αγαθοεργίες και ελεημοσύνες· ο Πέτρος την ανέστησε με προσευχή.','Acts 9:36–42'),
('joanna-myrrhbearer','Saint Joanna the Myrrh-bearer','Αγία Ιωάννα η Μυροφόρος','nt-saint','Woman disciple and Myrrh-bearer','Μαθήτρια και Μυροφόρος','Joanna, wife of Chuza, supported Christ’s ministry and is named among the women who came to the tomb and proclaimed the Resurrection.','Η Ιωάννα, σύζυγος του Χουζά, διακονούσε τον Χριστό και αναφέρεται ανάμεσα στις γυναίκες που ήρθαν στον τάφο και ανήγγειλαν την Ανάσταση.','Luke 8:3; 24:10'),
('salome-myrrhbearer','Saint Salome the Myrrh-bearer','Αγία Σαλώμη η Μυροφόρος','nt-saint','Myrrh-bearer and mother of James and John','Μυροφόρος και μητέρα Ιακώβου και Ιωάννου','Salome followed Christ, stood among the women at the Crucifixion, and came to the tomb with spices.','Η Σαλώμη ακολούθησε τον Χριστό, βρέθηκε ανάμεσα στις γυναίκες στη Σταύρωση και ήρθε στον τάφο με αρώματα.','Mark 15:40; 16:1'),
('mary-clopas','Saint Mary of Clopas','Αγία Μαρία του Κλωπά','nt-saint','Woman disciple at the Cross','Μαθήτρια κοντά στον Σταυρό','Mary of Clopas is named in John’s Gospel among the women standing near the Cross of Christ.','Η Μαρία του Κλωπά αναφέρεται στο Κατά Ιωάννην ανάμεσα στις γυναίκες που στέκονταν κοντά στον Σταυρό του Χριστού.','John 19:25'),
('junia','Apostle Junia','Απόστολος Ιουνία','nt-saint','Early Christian praised by Paul','Πρώιμη χριστιανή που επαινείται από τον Παύλο','Junia is greeted by Paul together with Andronicus as a kinswoman, fellow prisoner, and notable among the apostles.','Η Ιουνία χαιρετίζεται από τον Παύλο μαζί με τον Ανδρόνικο ως συγγενής, συναιχμάλωτη και επίσημη μεταξύ των αποστόλων.','Romans 16:7'),
('eunice','Saint Eunice','Αγία Ευνίκη','nt-saint','Mother of Timothy','Μητέρα του Τιμοθέου','Eunice, Timothy’s Jewish Christian mother, is remembered by Paul for sincere faith passed through the family.','Η Ευνίκη, Ιουδαία χριστιανή μητέρα του Τιμοθέου, μνημονεύεται από τον Παύλο για την ανυπόκριτη πίστη που μεταδόθηκε στην οικογένεια.','Acts 16:1; 2 Timothy 1:5; 3:15'),
('lois','Saint Lois','Αγία Λωΐδα','nt-saint','Grandmother of Timothy','Γιαγιά του Τιμοθέου','Lois is praised by Paul for the sincere faith that lived in her and was passed to Eunice and Timothy.','Η Λωΐδα επαινείται από τον Παύλο για την ανυπόκριτη πίστη που κατοικούσε μέσα της και μεταδόθηκε στην Ευνίκη και στον Τιμόθεο.','2 Timothy 1:5'),
('damaris','Saint Damaris of Athens','Αγία Δάμαρις Αθηνών','nt-saint','Athenian convert through Paul’s preaching','Αθηναία που πίστεψε από το κήρυγμα του Παύλου','Damaris was among those in Athens who believed after Paul’s address at the Areopagus.','Η Δάμαρις ήταν ανάμεσα σε όσους πίστεψαν στην Αθήνα μετά την ομιλία του Παύλου στον Άρειο Πάγο.','Acts 17:34'),
('wise-thief','The Wise Thief','Ο Ευγνώμων Ληστής','nt-saint','Penitent crucified beside Christ','Μετανοημένος ληστής που σταυρώθηκε δίπλα στον Χριστό','One of the criminals crucified beside Christ confessed His innocence and kingdom and heard the promise, “Today you will be with Me in Paradise.”','Ένας από τους ληστές που σταυρώθηκαν δίπλα στον Χριστό ομολόγησε την αθωότητα και τη βασιλεία Του και άκουσε την υπόσχεση ότι θα είναι μαζί Του στον Παράδεισο.','Luke 23:39–43'),
('simon-cyrene','Simon of Cyrene','Σίμων ο Κυρηναίος','nt-saint','Bearer of Christ’s Cross','Αυτός που σήκωσε τον Σταυρό του Χριστού','Simon of Cyrene was compelled to carry Christ’s Cross on the way to Golgotha; Mark names his sons Alexander and Rufus.','Ο Σίμων ο Κυρηναίος αγγαρεύτηκε να σηκώσει τον Σταυρό του Χριστού προς τον Γολγοθά· ο Μάρκος ονομάζει τους υιούς του Αλέξανδρο και Ρούφο.','Matthew 27:32; Mark 15:21; Luke 23:26'),
]
for id,en,el,cat,ren,rel,sen,sel,sc in more_holy:
    add(expanded,mk(id,en,el,cat,ren,rel,sen,sel,scripture=sc))

# Great feasts and key liturgical commemorations.
feast_rows=[
('nativity-christ','Nativity of Christ','Γέννηση του Χριστού','25 December','25 Δεκεμβρίου','The Church celebrates the birth in the flesh of Jesus Christ from the Virgin Mary in Bethlehem.','Η Εκκλησία εορτάζει τη κατά σάρκα Γέννηση του Ιησού Χριστού από την Παρθένο Μαρία στη Βηθλεέμ.','Matthew 1–2; Luke 2'),
('theophany','Theophany of Christ','Θεοφάνεια του Χριστού','6 January','6 Ιανουαρίου','At Christ’s Baptism in the Jordan, the Son is revealed, the Father’s voice is heard, and the Holy Spirit descends like a dove.','Στη Βάπτιση του Χριστού στον Ιορδάνη φανερώνεται ο Υιός, ακούγεται η φωνή του Πατέρα και κατέρχεται το Άγιο Πνεύμα σαν περιστερά.','Matthew 3:13–17; Mark 1:9–11; Luke 3:21–22'),
('presentation-christ','Meeting / Presentation of the Lord','Υπαπαντή του Κυρίου','2 February','2 Φεβρουαρίου','The infant Christ is brought to the Temple and received by Simeon and Anna.','Ο βρέφος Χριστός προσφέρεται στον Ναό και γίνεται δεκτός από τον Συμεών και την Άννα.','Luke 2:22–38'),
('annunciation','Annunciation to the Theotokos','Ευαγγελισμός της Θεοτόκου','25 March','25 Μαρτίου','The Archangel Gabriel announces to Mary that she will bear the Son of God, and she freely answers in faith.','Ο Αρχάγγελος Γαβριήλ αναγγέλλει στη Μαρία ότι θα γεννήσει τον Υιό του Θεού και εκείνη απαντά ελεύθερα με πίστη.','Luke 1:26–38'),
('entry-jerusalem','Entry of the Lord into Jerusalem','Είσοδος του Κυρίου στα Ιεροσόλυμα','Sunday before Pascha','Κυριακή πριν το Πάσχα','Christ enters Jerusalem humbly on a colt while the crowd greets Him with palms and cries of Hosanna.','Ο Χριστός εισέρχεται ταπεινά στα Ιεροσόλυμα πάνω σε πώλο, ενώ ο λαός Τον υποδέχεται με βάγια και κραυγές «Ωσαννά».','Matthew 21:1–11; John 12:12–19'),
('pascha','Holy Pascha — Resurrection of Christ','Άγιο Πάσχα — Ανάσταση του Χριστού','Moveable — Sunday of Pascha','Κινητή εορτή — Κυριακή του Πάσχα','The Feast of Feasts proclaims that Christ is risen from the dead, trampling down death by death and opening life to the world.','Η Εορτή των Εορτών διακηρύσσει ότι ο Χριστός ανέστη εκ νεκρών, πατώντας τον θάνατο με τον θάνατό Του και ανοίγοντας τη ζωή στον κόσμο.','Matthew 28; Mark 16; Luke 24; John 20'),
('ascension','Ascension of Christ','Ανάληψη του Χριστού','40 days after Pascha','40 ημέρες μετά το Πάσχα','The risen Christ ascends in glory and blesses His disciples, who await the promised Holy Spirit.','Ο αναστημένος Χριστός αναλαμβάνεται εν δόξη και ευλογεί τους μαθητές Του, που περιμένουν το υποσχεμένο Άγιο Πνεύμα.','Luke 24:50–53; Acts 1:1–11'),
('pentecost','Holy Pentecost','Αγία Πεντηκοστή','50 days after Pascha','50 ημέρες μετά το Πάσχα','The Holy Spirit descends on the apostolic community, empowering the Church’s mission to all nations.','Το Άγιο Πνεύμα κατέρχεται στην αποστολική κοινότητα και ενδυναμώνει την αποστολή της Εκκλησίας προς όλα τα έθνη.','Acts 2'),
('transfiguration','Transfiguration of Christ','Μεταμόρφωση του Χριστού','6 August','6 Αυγούστου','Christ reveals His divine glory on the mountain before Peter, James, and John; Moses and Elijah appear with Him.','Ο Χριστός φανερώνει τη θεία δόξα Του στο όρος ενώπιον Πέτρου, Ιακώβου και Ιωάννου· μαζί Του εμφανίζονται ο Μωυσής και ο Ηλίας.','Matthew 17:1–9; Mark 9:2–10; Luke 9:28–36'),
('nativity-theotokos','Nativity of the Theotokos','Γέννηση της Θεοτόκου','8 September','8 Σεπτεμβρίου','The Church celebrates the birth of the Virgin Mary, who would become the Mother of God.','Η Εκκλησία εορτάζει τη γέννηση της Παρθένου Μαρίας, που θα γινόταν Μητέρα του Θεού.','Liturgical tradition; cf. early Christian tradition'),
('entry-theotokos','Entry of the Theotokos into the Temple','Εισόδια της Θεοτόκου','21 November','21 Νοεμβρίου','The feast celebrates the dedication of the young Virgin Mary to God in the Temple according to Church tradition.','Η εορτή τιμά την αφιέρωση της νεαρής Παρθένου Μαρίας στον Θεό μέσα στον Ναό σύμφωνα με την εκκλησιαστική παράδοση.','Liturgical tradition'),
('exaltation-cross','Exaltation of the Holy Cross','Ύψωση του Τιμίου Σταυρού','14 September','14 Σεπτεμβρίου','The Church lifts up the Cross of Christ as the sign of His saving Passion and victory.','Η Εκκλησία υψώνει τον Σταυρό του Χριστού ως σημείο του σωτηρίου Πάθους και της νίκης Του.','John 3:13–17; liturgical tradition'),
('lazarus-saturday','Lazarus Saturday','Σάββατο του Λαζάρου','Saturday before Palm Sunday','Σάββατο πριν την Κυριακή των Βαΐων','The raising of Lazarus reveals Christ as the Resurrection and the Life and prepares the Church for Holy Week.','Η ανάσταση του Λαζάρου φανερώνει τον Χριστό ως Ανάσταση και Ζωή και προετοιμάζει την Εκκλησία για τη Μεγάλη Εβδομάδα.','John 11:1–45'),
('holy-thursday','Great and Holy Thursday','Μεγάλη Πέμπτη','Thursday of Holy Week','Πέμπτη της Μεγάλης Εβδομάδας','The Church remembers the Mystical Supper, the washing of the disciples’ feet, Christ’s prayer, and His betrayal.','Η Εκκλησία μνημονεύει τον Μυστικό Δείπνο, τον νιπτήρα των μαθητών, την προσευχή του Χριστού και την προδοσία Του.','Matthew 26; John 13–17'),
('holy-friday','Great and Holy Friday','Μεγάλη Παρασκευή','Friday of Holy Week','Παρασκευή της Μεγάλης Εβδομάδας','The Church stands before the saving Passion and Crucifixion of Christ and venerates His life-giving Cross.','Η Εκκλησία στέκεται μπροστά στο σωτήριο Πάθος και τη Σταύρωση του Χριστού και προσκυνεί τον ζωοποιό Σταυρό Του.','Matthew 27; Mark 15; Luke 23; John 18–19'),
('holy-saturday','Great and Holy Saturday','Μεγάλο Σάββατο','Saturday of Holy Week','Σάββατο της Μεγάλης Εβδομάδας','Christ rests in the tomb while the Church anticipates His victorious Resurrection and His descent into Hades.','Ο Χριστός αναπαύεται στον τάφο, ενώ η Εκκλησία προσδοκά τη νικηφόρα Ανάστασή Του και την κάθοδό Του στον Άδη.','Matthew 27:57–66; 1 Peter 3:18–20'),
('sunday-myrrhbearers','Sunday of the Myrrh-bearing Women','Κυριακή των Μυροφόρων','Second Sunday after Pascha','Δεύτερη Κυριακή μετά το Πάσχα','The Church honors the women who came faithfully to Christ’s tomb and became the first heralds of the Resurrection, together with Joseph of Arimathea and Nicodemus.','Η Εκκλησία τιμά τις γυναίκες που ήρθαν πιστά στον τάφο του Χριστού και έγιναν οι πρώτες κήρυκες της Αναστάσεως, μαζί με τον Ιωσήφ Αριμαθαίας και τον Νικόδημο.','Mark 15:43–16:8'),
('all-saints','Sunday of All Saints','Κυριακή των Αγίων Πάντων','First Sunday after Pentecost','Πρώτη Κυριακή μετά την Πεντηκοστή','The Church glorifies the Holy Spirit’s fruit in all saints, known and unknown, from every age and place.','Η Εκκλησία δοξάζει τον καρπό του Αγίου Πνεύματος σε όλους τους αγίους, γνωστούς και αγνώστους, από κάθε εποχή και τόπο.','Hebrews 11:33–12:2; Matthew 10:32–33,37–38; 19:27–30'),
('synaxis-seventy','Synaxis of the Seventy Apostles','Σύναξη των Εβδομήκοντα Αποστόλων','4 January','4 Ιανουαρίου','The Orthodox Church celebrates together the wider apostolic company sent by Christ two by two before Him.','Η Ορθόδοξη Εκκλησία εορτάζει μαζί τον ευρύτερο αποστολικό χορό που απέστειλε ο Χριστός ανά δύο πριν από Αυτόν.','Luke 10:1–20'),
('synaxis-archangels','Synaxis of the Archangels and Bodiless Powers','Σύναξη Αρχαγγέλων και Ασωμάτων Δυνάμεων','8 November','8 Νοεμβρίου','The Church gathers in thanksgiving for Michael, Gabriel, Raphael, and all the bodiless heavenly powers who serve God.','Η Εκκλησία συνάγεται με ευχαριστία για τον Μιχαήλ, Γαβριήλ, Ραφαήλ και όλες τις ασώματες ουράνιες δυνάμεις που υπηρετούν τον Θεό.','Daniel 10–12; Luke 1; Tobit 3–12; Hebrews 1:14'),
]
for id,en,el,fd,fdel,sen,sel,sc in feast_rows:
    add(feasts,mk(id,en,el,'feast','Liturgical feast','Λειτουργική εορτή',sen,sel,fd,fdel,sc,notes_en='Liturgical dates and observance may differ where the old and new calendars are used.',notes_el='Οι λειτουργικές ημερομηνίες και η τήρηση μπορεί να διαφέρουν ανάλογα με τη χρήση παλαιού ή νέου ημερολογίου.'))

# Prominent Orthodox saints (post-biblical), selected for broad geographic / historical coverage.
saints=[
('basil-great','Saint Basil the Great','Άγιος Βασίλειος ο Μέγας','Archbishop of Caesarea, Cappadocian Father','Αρχιεπίσκοπος Καισαρείας, Καππαδόκης Πατέρας','1 January','Defended Nicene faith, organized charitable institutions, and shaped Orthodox theology, monastic life, and liturgy.'),
('gregory-theologian','Saint Gregory the Theologian','Άγιος Γρηγόριος ο Θεολόγος','Archbishop of Constantinople and theologian','Αρχιεπίσκοπος Κωνσταντινουπόλεως και θεολόγος','25 January','A Cappadocian Father whose theological orations helped articulate the Church’s confession of the Holy Trinity.'),
('gregory-nyssa','Saint Gregory of Nyssa','Άγιος Γρηγόριος Νύσσης','Bishop and Cappadocian Father','Επίσκοπος και Καππαδόκης Πατέρας','10 January','Brother of Saint Basil, bishop, theologian, and major witness to Nicene Trinitarian teaching.'),
('athanasius-great','Saint Athanasius the Great','Άγιος Αθανάσιος ο Μέγας','Archbishop of Alexandria','Αρχιεπίσκοπος Αλεξανδρείας','18 January','A leading defender of the divinity of Christ and the Nicene faith during the Arian controversy.'),
('cyril-alexandria','Saint Cyril of Alexandria','Άγιος Κύριλλος Αλεξανδρείας','Archbishop and defender of the title Theotokos','Αρχιεπίσκοπος και υπερασπιστής του τίτλου Θεοτόκος','9 June','A major Alexandrian father who defended the unity of Christ and the confession of the Virgin Mary as Theotokos.'),
('spyridon','Saint Spyridon of Trimythous','Άγιος Σπυρίδων Τριμυθούντος','Bishop and wonderworker','Επίσκοπος και θαυματουργός','12 December','A shepherd who became bishop of Trimythous and is beloved for humble faith, pastoral care, and miracles.'),
('catherine','Saint Catherine the Great Martyr','Αγία Αικατερίνη η Μεγαλομάρτυς','Great Martyr of Alexandria','Μεγαλομάρτυς Αλεξανδρείας','25 November','Honored as a learned young martyr who confessed Christ before pagan rulers and teachers.'),
('barbara','Saint Barbara the Great Martyr','Αγία Βαρβάρα η Μεγαλομάρτυς','Great Martyr','Μεγαλομάρτυς','4 December','Venerated for steadfast confession of Christ and martyrdom despite persecution from her own household.'),
('marina','Saint Marina the Great Martyr','Αγία Μαρίνα η Μεγαλομάρτυς','Great Martyr','Μεγαλομάρτυς','17 July','A young martyr honored for courage, purity, and steadfast faith under persecution.'),
('paraskevi','Saint Paraskevi','Αγία Παρασκευή','Virgin Martyr','Παρθενομάρτυς','26 July','A widely venerated martyr associated with missionary zeal, endurance, and healing traditions.'),
('irene-great-martyr','Saint Irene the Great Martyr','Αγία Ειρήνη η Μεγαλομάρτυς','Great Martyr','Μεγαλομάρτυς','5 May','An early Christian martyr remembered for fearless witness and the conversion of many through her confession.'),
('panteleimon','Saint Panteleimon the Great Martyr','Άγιος Παντελεήμων ο Μεγαλομάρτυς','Physician and Unmercenary healer','Ιατρός και Ανάργυρος','27 July','A physician and martyr who used his healing gifts freely and confessed Christ under persecution.'),
('constantine-helen','Saints Constantine and Helen','Άγιοι Κωνσταντίνος και Ελένη','Equal-to-the-Apostles rulers','Ισαπόστολοι βασιλείς','21 May','Emperor Constantine ended imperial persecution of Christians, while his mother Helen is linked with the discovery and veneration of the Cross.'),
('thecla','Saint Thecla, Protomartyr among women','Αγία Θέκλα η Πρωτομάρτυς','Equal-to-the-Apostles and Protomartyr','Ισαπόστολος και Πρωτομάρτυς','24 September','An early disciple associated with Saint Paul, honored for ascetic dedication and fearless witness to Christ.'),
('euphemia','Saint Euphemia the Great Martyr','Αγία Ευφημία η Μεγαλομάρτυς','Great Martyr of Chalcedon','Μεγαλομάρτυς Χαλκηδόνος','16 September; 11 July','A martyr of Chalcedon whose memory is also linked in Orthodox tradition with the Fourth Ecumenical Council.'),
('anastasia-pharmakolytria','Saint Anastasia the Deliverer from Potions','Αγία Αναστασία η Φαρμακολύτρια','Great Martyr','Μεγαλομάρτυς','22 December','A martyr remembered for caring for imprisoned Christians and for deliverance associated with poisons and bonds.'),
('kyriaki','Saint Kyriaki the Great Martyr','Αγία Κυριακή η Μεγαλομάρτυς','Great Martyr','Μεγαλομάρτυς','7 July','A young martyr who endured interrogation and suffering rather than deny Christ.'),
('theodore-tyro','Saint Theodore the Recruit','Άγιος Θεόδωρος ο Τήρων','Great Martyr','Μεγαλομάρτυς','17 February','A soldier-martyr whose steadfast confession is commemorated especially in the first week of Great Lent.'),
('theodore-stratelates','Saint Theodore the Commander','Άγιος Θεόδωρος ο Στρατηλάτης','Great Martyr','Μεγαλομάρτυς','8 February','A military commander and martyr honored for courageous confession and charity.'),
('menas','Saint Menas the Great Martyr','Άγιος Μηνάς ο Μεγαλομάρτυς','Soldier and Great Martyr','Στρατιώτης και Μεγαλομάρτυς','11 November','An Egyptian soldier-martyr, widely invoked for help in need and the recovery of what is lost.'),
('tryphon','Saint Tryphon the Martyr','Άγιος Τρύφων ο Μάρτυς','Martyr and wonderworker','Μάρτυς και θαυματουργός','1 February','A young martyr remembered for simple faith and traditions of healing and protection of fields and animals.'),
('charalambos','Saint Charalambos the Hieromartyr','Άγιος Χαράλαμπος ο Ιερομάρτυς','Hieromartyr and priest','Ιερομάρτυς και ιερέας','10 February','An aged priest and martyr honored for perseverance under severe persecution and for intercession in times of disease.'),
('anthony-great','Saint Anthony the Great','Άγιος Αντώνιος ο Μέγας','Father of monasticism','Πατέρας του μοναχισμού','17 January','An Egyptian ascetic whose life in the desert became foundational for Christian monasticism.'),
('pachomius','Saint Pachomius the Great','Άγιος Παχώμιος ο Μέγας','Founder of cenobitic monasticism','Θεμελιωτής του κοινοβιακού μοναχισμού','15 May','An Egyptian monk who organized communal monastic life under a shared rule.'),
('macarius-egypt','Saint Macarius the Great of Egypt','Άγιος Μακάριος ο Αιγύπτιος','Desert Father','Πατέρας της Ερήμου','19 January','A renowned Desert Father remembered for humility, spiritual discernment, and deep prayer.'),
('euthymius-great','Saint Euthymius the Great','Άγιος Ευθύμιος ο Μέγας','Desert monastic father','Μεγάλος ασκητικός πατέρας','20 January','A major Palestinian monastic father who formed communities of prayer, repentance, and hospitality.'),
('sabbas-sanctified','Saint Sabbas the Sanctified','Άγιος Σάββας ο Ηγιασμένος','Monastic founder of Palestine','Μοναστικός κτήτωρ της Παλαιστίνης','5 December','Founder of the Great Lavra near Jerusalem, influential in Orthodox monastic worship and discipline.'),
('john-climacus','Saint John Climacus','Άγιος Ιωάννης της Κλίμακος','Abbot and spiritual writer','Ηγούμενος και πνευματικός συγγραφέας','30 March','Abbot of Sinai and author of The Ladder of Divine Ascent, a classic guide to repentance and spiritual growth.'),
('maximus-confessor','Saint Maximus the Confessor','Άγιος Μάξιμος ο Ομολογητής','Theologian and confessor','Θεολόγος και ομολογητής','21 January','A profound theologian who suffered for defending the Orthodox teaching that Christ has both divine and human wills.'),
('john-damascus','Saint John of Damascus','Άγιος Ιωάννης ο Δαμασκηνός','Theologian and hymnographer','Θεολόγος και υμνογράφος','4 December','A monk, theologian, hymnographer, and major defender of the holy icons during iconoclasm.'),
('ephrem-syrian','Saint Ephrem the Syrian','Άγιος Εφραίμ ο Σύρος','Deacon, poet, and theologian','Διάκονος, ποιητής και θεολόγος','28 January','A Syriac deacon whose hymns and poetic theology remain treasures of the Christian East.'),
('isaac-syrian','Saint Isaac the Syrian','Άγιος Ισαάκ ο Σύρος','Bishop, ascetic, and spiritual writer','Επίσκοπος, ασκητής και πνευματικός συγγραφέας','28 January','An ascetic writer renowned for teaching on mercy, compunction, silence, and the love of God.'),
('symeon-new-theologian','Saint Symeon the New Theologian','Άγιος Συμεών ο Νέος Θεολόγος','Monk and mystical theologian','Μοναχός και μυστικός θεολόγος','12 March','A Byzantine monk and theologian who emphasized repentance, conscious life in the Holy Spirit, and direct experience of divine grace.'),
('gregory-palamas','Saint Gregory Palamas','Άγιος Γρηγόριος Παλαμάς','Archbishop of Thessalonica and theologian','Αρχιεπίσκοπος Θεσσαλονίκης και θεολόγος','14 November; Second Sunday of Great Lent','Defended the Orthodox teaching on hesychastic prayer and participation in the uncreated energies of God.'),
('seraphim-sarov','Saint Seraphim of Sarov','Άγιος Σεραφείμ του Σάρωφ','Monk and wonderworker','Μοναχός και θαυματουργός','2 January','A Russian elder known for ascetic struggle, radiant joy, and teaching that the Christian aim is the acquisition of the Holy Spirit.'),
('silouan-athonite','Saint Silouan the Athonite','Άγιος Σιλουανός ο Αθωνίτης','Athonite monk','Αγιορείτης μοναχός','24 September','An Athonite monk whose teaching centers on humility, love for enemies, and prayer for the whole world.'),
('sophrony-essex','Saint Sophrony of Essex','Άγιος Σωφρόνιος του Έσσεξ','Athonite elder and monastery founder','Αγιορείτης γέροντας και κτήτορας μονής','11 July','Disciple of Saint Silouan who carried Athonite spiritual life to Western Europe and wrote extensively on prayer and personhood.'),
('paisios','Saint Paisios the Athonite','Άγιος Παΐσιος ο Αγιορείτης','Athonite elder','Αγιορείτης γέροντας','12 July','A twentieth-century Athonite elder beloved for compassion, discernment, simplicity, and practical spiritual counsel.'),
('porphyrios','Saint Porphyrios of Kavsokalyvia','Άγιος Πορφύριος ο Καυσοκαλυβίτης','Athonite elder and priest','Αγιορείτης γέροντας και ιερέας','2 December','A modern Greek elder known for joy in Christ, pastoral sensitivity, and an emphasis on loving Christ rather than obsessing over darkness.'),
('iakovos-tsalikis','Saint Iakovos Tsalikis','Άγιος Ιάκωβος Τσαλίκης','Abbot and spiritual father','Ηγούμενος και πνευματικός πατέρας','22 November','A modern Greek abbot of the Monastery of Saint David of Evia, remembered for humility, prayer, and pastoral love.'),
('kosmas-aetolos','Saint Kosmas of Aetolia','Άγιος Κοσμάς ο Αιτωλός','Equal-to-the-Apostles missionary','Ισαπόστολος ιεραπόστολος','24 August','An eighteenth-century missionary who traveled widely, preaching repentance, education, and fidelity to Orthodox Christian life.'),
('nicodemus-hagiorite','Saint Nicodemus the Hagiorite','Άγιος Νικόδημος ο Αγιορείτης','Athonite theologian and spiritual writer','Αγιορείτης θεολόγος και πνευματικός συγγραφέας','14 July','An Athonite monk, editor, and writer associated with the Philokalia and the renewal of patristic spiritual life.'),
('nikephoros-leper','Saint Nikephoros the Leper','Άγιος Νικηφόρος ο Λεπρός','Monk and confessor of suffering','Μοναχός και ομολογητής της υπομονής','4 January','A twentieth-century Greek monk who lived with leprosy in patience, prayer, and gratitude, becoming a source of consolation to others.'),
('luke-crimea','Saint Luke of Crimea','Άγιος Λουκάς ο Ιατρός','Archbishop, surgeon, and confessor','Αρχιεπίσκοπος, χειρουργός και ομολογητής','11 June','A gifted surgeon and Orthodox bishop who endured imprisonment and exile while continuing both medical service and episcopal ministry.'),
('john-shanghai','Saint John of Shanghai and San Francisco','Άγιος Ιωάννης Σαγκάης και Σαν Φρανσίσκο','Bishop and wonderworker','Επίσκοπος και θαυματουργός','2 July','A twentieth-century hierarch known for intense prayer, care for refugees and orphans, and missionary pastoral work across continents.'),
('herman-alaska','Saint Herman of Alaska','Άγιος Γερμανός της Αλάσκας','Missionary monk','Ιεραπόστολος μοναχός','9 August; 13 December','A Russian monk and missionary who served the Indigenous peoples of Alaska with humility, advocacy, and prayer.'),
('innocent-alaska','Saint Innocent of Alaska','Άγιος Ιννοκέντιος της Αλάσκας','Missionary bishop and linguist','Ιεραπόστολος επίσκοπος και γλωσσολόγος','31 March','A missionary who learned Indigenous languages, translated Christian texts, traveled widely, and later became Metropolitan of Moscow.'),
('elizabeth-new-martyr','Saint Elizabeth the New Martyr','Αγία Ελισάβετ η Νεομάρτυς','Nun and New Martyr','Μοναχή και Νεομάρτυς','18 July','A grand duchess who embraced Orthodox monastic service, founded a community of mercy, and was martyred after the Russian Revolution.'),
('maria-paris','Saint Maria of Paris','Αγία Μαρία των Παρισίων','Nun, theologian, and martyr','Μοναχή, θεολόγος και μάρτυς','20 July','A Russian émigré nun who served the poor and persecuted in Paris and died in a Nazi concentration camp after helping Jews escape.'),
('moses-ethiopian','Saint Moses the Ethiopian','Άγιος Μωυσής ο Αιθίοπας','Desert Father and former bandit','Πατέρας της Ερήμου και πρώην ληστής','28 August','A former bandit transformed by repentance into a Desert Father renowned for humility, nonjudgment, and mercy.'),
('romanus-melodist','Saint Romanos the Melodist','Άγιος Ρωμανός ο Μελωδός','Hymnographer and deacon','Υμνογράφος και διάκονος','1 October','One of the greatest Byzantine hymnographers, famous for poetic kontakia that proclaim the mysteries of Christ.'),
('photios-great','Saint Photios the Great','Άγιος Φώτιος ο Μέγας','Patriarch of Constantinople','Πατριάρχης Κωνσταντινουπόλεως','6 February','A learned patriarch, theologian, and missionary supporter who defended Orthodox doctrine and encouraged the mission to the Slavs.'),
('cyril-methodius','Saints Cyril and Methodius','Άγιοι Κύριλλος και Μεθόδιος','Equal-to-the-Apostles missionaries to the Slavs','Ισαπόστολοι φωτιστές των Σλάβων','11 May','Brothers from Thessalonica who evangelized the Slavs, translated Scripture and worship, and shaped Slavic Christian literacy.'),
('ignatius-antioch','Saint Ignatius of Antioch','Άγιος Ιγνάτιος ο Θεοφόρος','Bishop and Hieromartyr','Επίσκοπος και Ιερομάρτυς','20 December','An early bishop of Antioch whose letters on the way to martyrdom bear powerful witness to Christ, Eucharist, episcopal unity, and love.'),
('polycarp','Saint Polycarp of Smyrna','Άγιος Πολύκαρπος Σμύρνης','Bishop and Hieromartyr','Επίσκοπος και Ιερομάρτυς','23 February','An early bishop and disciple of the apostolic generation whose martyrdom account is among the oldest Christian texts of its kind.'),
('irenaeus-lyon','Saint Irenaeus of Lyons','Άγιος Ειρηναίος Λυώνος','Bishop and theologian','Επίσκοπος και θεολόγος','23 August','A second-century bishop who defended apostolic faith against Gnosticism and emphasized the unity of Scripture and salvation in Christ.'),
('justin-martyr','Saint Justin the Philosopher and Martyr','Άγιος Ιουστίνος ο Φιλόσοφος και Μάρτυς','Apologist and martyr','Απολογητής και μάρτυς','1 June','A philosopher who embraced Christianity and wrote important early apologies explaining Christian faith and worship before his martyrdom.'),
('cyprian-justina','Saints Cyprian and Justina','Άγιοι Κυπριανός και Ιουστίνη','Martyrs associated with victory over sorcery','Μάρτυρες συνδεδεμένοι με νίκη κατά της μαγείας','2 October','Their traditional account emphasizes conversion, chastity, repentance, and Christ’s victory over occult powers.'),
('dionysius-areopagite','Saint Dionysius the Areopagite','Άγιος Διονύσιος ο Αρεοπαγίτης','Athenian disciple and bishop','Αθηναίος μαθητής και επίσκοπος','3 October','Dionysius believed through Paul’s preaching at the Areopagus and is honored in tradition as the first bishop of Athens.','Acts 17:34'),
('ambrose-milan','Saint Ambrose of Milan','Άγιος Αμβρόσιος Μεδιολάνων','Bishop and Church Father','Επίσκοπος και Πατέρας της Εκκλησίας','7 December','A Western Church Father, hymnographer, and bishop who defended Nicene faith and influenced Saint Augustine.'),
('augustine-hippo','Saint Augustine of Hippo','Άγιος Αυγουστίνος Ιππώνος','Bishop and Church Father','Επίσκοπος και Πατέρας της Εκκλησίας','15 June','A North African bishop and prolific theologian whose Confessions and other works deeply shaped Christian thought.'),
('benedict-nursia','Saint Benedict of Nursia','Άγιος Βενέδικτος της Νουρσίας','Monastic father of the West','Μοναστικός πατέρας της Δύσεως','14 March','A pre-schism Western monastic father whose Rule shaped communities of prayer, work, stability, and hospitality.'),
('patrick-ireland','Saint Patrick of Ireland','Άγιος Πατρίκιος Ιρλανδίας','Missionary bishop','Ιεραπόστολος επίσκοπος','17 March','A fifth-century missionary bishop associated with the evangelization of Ireland and a surviving personal Confession of faith.'),
('brigid-kildare','Saint Brigid of Kildare','Αγία Βριγίδα του Κιλντέαρ','Abbess and Irish saint','Ηγουμένη και Ιρλανδή αγία','1 February','An early Irish abbess remembered for prayer, generosity, hospitality, and care for the poor.'),
('columba-iona','Saint Columba of Iona','Άγιος Κολούμπα της Ιόνα','Monk and missionary','Μοναχός και ιεραπόστολος','9 June','An Irish monk who founded the monastery of Iona and helped spread Christianity among the peoples of Scotland.'),
('aiden-lindisfarne','Saint Aidan of Lindisfarne','Άγιος Αϊδανός Λίντισφαρν','Bishop and missionary','Επίσκοπος και ιεραπόστολος','31 August','A Celtic missionary bishop known for simplicity, walking evangelism, education, and care for the poor in Northumbria.'),
('cuthbert','Saint Cuthbert of Lindisfarne','Άγιος Κούθμπερτ Λίντισφαρν','Bishop and hermit','Επίσκοπος και ερημίτης','20 March','A Northumbrian monk, hermit, and bishop remembered for pastoral gentleness, prayer, and closeness to creation.'),
]
for row in saints:
    id,en,el,ren,rel,fd,story,*rest=row
    sc=rest[0] if rest else 'Church tradition / Lives of the Saints'
    story_el=f'Ο/Η {el} τιμάται στην Ορθόδοξη Εκκλησία. {"Η ζωή και η διακονία του/της μαρτυρούν πίστη, μετάνοια, προσευχή, αγάπη και σταθερότητα στον Χριστό."}'
    add(church,mk(id,en,el,'church-saint',ren,rel,story,story_el,fd,fd,sc,notes_en='A concise educational summary; consult an Orthodox synaxarion or local calendar for the full life, hymns, and jurisdiction-specific commemoration.',notes_el='Σύντομη εκπαιδευτική περίληψη· για πλήρη βίο, ύμνους και τοπική μνήμη συμβουλευτείτε ορθόδοξο συναξάρι ή τοπικό ημερολόγιο.'))

# Biblical context figures: included for completeness but explicitly not presented as saints.
ctx=[
('cain','Cain','Κάιν','First son of Adam and Eve','Πρώτος υιός Αδάμ και Εύας','Cain killed his brother Abel after God rejected his offering and became a biblical image of envy, violence, judgment, and the need to master sin.','Ο Κάιν σκότωσε τον αδελφό του Άβελ όταν η προσφορά του δεν έγινε δεκτή και έγινε βιβλική εικόνα φθόνου, βίας, κρίσεως και ανάγκης να κυριαρχήσει ο άνθρωπος πάνω στην αμαρτία.','Genesis 4:1–16'),
('nimrod','Nimrod','Νεβρώδ','Mighty ruler in early Genesis','Ισχυρός άρχοντας στην πρώιμη Γένεση','Nimrod is described as a mighty figure whose kingdom included Babel and other cities in Mesopotamia.','Ο Νεβρώδ περιγράφεται ως ισχυρή μορφή, του οποίου το βασίλειο περιλάμβανε τη Βαβέλ και άλλες πόλεις της Μεσοποταμίας.','Genesis 10:8–12'),
('hagar','Hagar','Άγαρ','Egyptian servant of Sarah and mother of Ishmael','Αιγύπτια δούλη της Σάρρας και μητέρα του Ισμαήλ','Hagar fled into the wilderness, encountered the angel of the Lord, and became mother of Ishmael; her story includes suffering, promise, and divine care.','Η Άγαρ έφυγε στην έρημο, συνάντησε άγγελο Κυρίου και έγινε μητέρα του Ισμαήλ· η ιστορία της περιλαμβάνει πόνο, υπόσχεση και θεία φροντίδα.','Genesis 16; 21:8–21'),
('ishmael','Ishmael','Ισμαήλ','Son of Abraham and Hagar','Υιός του Αβραάμ και της Άγαρ','Ishmael was Abraham’s son by Hagar; God promised that he too would become the ancestor of a great people.','Ο Ισμαήλ ήταν υιός του Αβραάμ από την Άγαρ· ο Θεός υποσχέθηκε ότι και αυτός θα γίνει πρόγονος μεγάλου λαού.','Genesis 16–17; 21'),
('esau','Esau','Ησαύ','Twin brother of Jacob','Δίδυμος αδελφός του Ιακώβ','Esau sold his birthright to Jacob and later reconciled with him after years of separation.','Ο Ησαύ πούλησε τα πρωτοτόκια στον Ιακώβ και αργότερα συμφιλιώθηκε μαζί του μετά από χρόνια χωρισμού.','Genesis 25–36'),
('laban','Laban','Λάβαν','Brother of Rebekah and uncle of Jacob','Αδελφός της Ρεβέκκας και θείος του Ιακώβ','Laban employed and repeatedly bargained with Jacob, becoming part of the complicated family story behind Israel’s patriarchs.','Ο Λάβαν εργοδότησε και διαπραγματεύτηκε επανειλημμένα με τον Ιακώβ, αποτελώντας μέρος της πολύπλοκης οικογενειακής ιστορίας των πατριαρχών του Ισραήλ.','Genesis 24; 29–31'),
('dinah','Dinah','Δείνα','Daughter of Jacob and Leah','Θυγατέρα του Ιακώβ και της Λείας','Dinah’s painful story in Genesis 34 leads to violent retaliation by her brothers Simeon and Levi.','Η οδυνηρή ιστορία της Δείνας στη Γένεση 34 οδηγεί σε βίαιη εκδίκηση από τους αδελφούς της Συμεών και Λευί.','Genesis 30:21; 34'),
('potiphar','Potiphar','Πετεφρής','Egyptian official who purchased Joseph','Αιγύπτιος αξιωματούχος που αγόρασε τον Ιωσήφ','Potiphar bought Joseph as a slave; Joseph rose to responsibility in his household before being falsely accused.','Ο Πετεφρής αγόρασε τον Ιωσήφ ως δούλο· ο Ιωσήφ ανέλαβε ευθύνη στον οίκο του πριν κατηγορηθεί ψευδώς.','Genesis 39'),
('pharaoh-exodus','Pharaoh of the Exodus','Φαραώ της Εξόδου','Egyptian ruler who opposed Moses','Αιγύπτιος άρχοντας που αντιστάθηκε στον Μωυσή','The unnamed Pharaoh repeatedly hardened his heart against Moses’ demand to release Israel, leading to the plagues and the Exodus.','Ο ανώνυμος Φαραώ σκλήρυνε επανειλημμένα την καρδιά του απέναντι στο αίτημα του Μωυσή να ελευθερώσει τον Ισραήλ, οδηγώντας στις πληγές και στην Έξοδο.','Exodus 5–14'),
('pharaoh-daughter','Pharaoh’s Daughter','Η θυγατέρα του Φαραώ','Royal woman who rescued Moses','Βασιλική γυναίκα που έσωσε τον Μωυσή','Pharaoh’s daughter found the infant Moses in the Nile and raised him, preserving the life of the future deliverer of Israel.','Η θυγατέρα του Φαραώ βρήκε τον βρέφος Μωυσή στον Νείλο και τον ανέθρεψε, διασώζοντας τη ζωή του μελλοντικού ελευθερωτή του Ισραήλ.','Exodus 2:5–10'),
('shiphrah','Shiphrah','Σεπφώρα','Hebrew midwife who feared God','Εβραία μαία που φοβόταν τον Θεό','Shiphrah, with Puah, refused Pharaoh’s command to kill Hebrew male infants.','Η Σεπφώρα, μαζί με τη Φουά, αρνήθηκε την εντολή του Φαραώ να θανατώνει τα αρσενικά βρέφη των Εβραίων.','Exodus 1:15–21'),
('puah','Puah','Φουά','Hebrew midwife who feared God','Εβραία μαία που φοβόταν τον Θεό','Puah, with Shiphrah, defied Pharaoh and protected newborn Hebrew children.','Η Φουά, μαζί με τη Σεπφώρα, αντιστάθηκε στον Φαραώ και προστάτευσε τα νεογέννητα παιδιά των Εβραίων.','Exodus 1:15–21'),
('korah','Korah','Κορέ','Leader of a rebellion in the wilderness','Ηγέτης εξέγερσης στην έρημο','Korah led a rebellion against Moses and Aaron, and his story became a warning against pride and unlawful grasping at sacred authority.','Ο Κορέ ηγήθηκε εξέγερσης εναντίον του Μωυσή και του Ααρών και η ιστορία του έγινε προειδοποίηση κατά της υπερηφάνειας και της παράνομης διεκδίκησης ιερής εξουσίας.','Numbers 16; Jude 11'),
('balaam','Balaam','Βαλαάμ','Diviner summoned to curse Israel','Μάντης που κλήθηκε να καταραστεί τον Ισραήλ','Balaam was hired by Balak to curse Israel but was compelled to speak blessing; later biblical texts also criticize his corrupt influence.','Ο Βαλαάμ μισθώθηκε από τον Βαλάκ για να καταραστεί τον Ισραήλ αλλά αναγκάστηκε να προφέρει ευλογία· μεταγενέστερα κείμενα επικρίνουν και τη διεφθαρμένη επιρροή του.','Numbers 22–24; 31:16; 2 Peter 2:15'),
('balak','Balak','Βαλάκ','King of Moab who feared Israel','Βασιλιάς Μωάβ που φοβήθηκε τον Ισραήλ','Balak summoned Balaam to curse Israel as the people approached the promised land.','Ο Βαλάκ κάλεσε τον Βαλαάμ να καταραστεί τον Ισραήλ καθώς ο λαός πλησίαζε στη γη της επαγγελίας.','Numbers 22–24'),
('sisera','Sisera','Σισάρα','Canaanite military commander','Χαναναίος στρατιωτικός διοικητής','Sisera commanded the forces defeated under Deborah and Barak and was later killed by Jael.','Ο Σισάρα διοικούσε τις δυνάμεις που ηττήθηκαν επί Δεββώρας και Βαράκ και αργότερα θανατώθηκε από την Ιαήλ.','Judges 4–5'),
('delilah','Delilah','Δαλιδά','Woman who betrayed Samson','Γυναίκα που πρόδωσε τον Σαμψών','Delilah repeatedly pressed Samson to reveal the secret connected with his strength and betrayed him to the Philistine rulers.','Η Δαλιδά πίεζε επανειλημμένα τον Σαμψών να αποκαλύψει το μυστικό που συνδεόταν με τη δύναμή του και τον πρόδωσε στους άρχοντες των Φιλισταίων.','Judges 16:4–22'),
('saul-king','King Saul','Βασιλιάς Σαούλ','First king of Israel','Πρώτος βασιλιάς του Ισραήλ','Saul began as Israel’s first king but his reign became marked by disobedience, jealousy toward David, spiritual decline, and tragedy.','Ο Σαούλ άρχισε ως ο πρώτος βασιλιάς του Ισραήλ, αλλά η βασιλεία του σημαδεύτηκε από ανυπακοή, ζήλια προς τον Δαβίδ, πνευματική πτώση και τραγωδία.','1 Samuel 9–31'),
('michal','Michal','Μελχόλ','Daughter of Saul and wife of David','Θυγατέρα Σαούλ και σύζυγος Δαβίδ','Michal loved and helped David escape from Saul, but later her relationship with David became strained.','Η Μελχόλ αγάπησε και βοήθησε τον Δαβίδ να διαφύγει από τον Σαούλ, αλλά αργότερα η σχέση τους έγινε δύσκολη.','1 Samuel 18–19; 2 Samuel 6'),
('absalom','Absalom','Αβεσσαλώμ','Son of David who rebelled','Υιός του Δαβίδ που επαναστάτησε','Absalom led a rebellion against his father David, ending in civil war and his death, which brought David profound grief.','Ο Αβεσσαλώμ ηγήθηκε εξέγερσης κατά του πατέρα του Δαβίδ, που κατέληξε σε εμφύλιο πόλεμο και στον θάνατό του, προκαλώντας βαθύ πένθος στον Δαβίδ.','2 Samuel 13–19'),
('joab','Joab','Ιωάβ','Commander of David’s army','Αρχιστράτηγος του Δαβίδ','Joab was a powerful and often ruthless military commander under David, involved in both victories and grave acts of violence.','Ο Ιωάβ ήταν ισχυρός και συχνά σκληρός στρατιωτικός διοικητής υπό τον Δαβίδ, εμπλεκόμενος τόσο σε νίκες όσο και σε βαριές πράξεις βίας.','2 Samuel; 1 Kings 1–2'),
('jeroboam','Jeroboam I','Ιεροβοάμ Αʹ','First king of the northern kingdom','Πρώτος βασιλιάς του βόρειου βασιλείου','Jeroboam led the northern tribes after the kingdom divided and established rival cult centers condemned by the biblical writers.','Ο Ιεροβοάμ ηγήθηκε των βόρειων φυλών μετά τη διαίρεση του βασιλείου και ίδρυσε ανταγωνιστικά κέντρα λατρείας που καταδικάζονται από τους βιβλικούς συγγραφείς.','1 Kings 11–14'),
('ahab','King Ahab','Βασιλιάς Αχαάβ','King of Israel opposed by Elijah','Βασιλιάς Ισραήλ που ελέγχθηκε από τον Ηλία','Ahab’s reign was marked by alliance with Jezebel, promotion of Baal worship, conflict with Elijah, and the injustice against Naboth.','Η βασιλεία του Αχαάβ σημαδεύτηκε από τη συμμαχία με την Ιεζάβελ, την προώθηση της λατρείας του Βάαλ, τη σύγκρουση με τον Ηλία και την αδικία κατά του Ναβουθαί.','1 Kings 16–22'),
('jezebel','Jezebel','Ιεζάβελ','Queen who promoted Baal worship','Βασίλισσα που προώθησε τη λατρεία του Βάαλ','Jezebel persecuted prophets of the Lord, supported Baal worship, and arranged the judicial murder of Naboth.','Η Ιεζάβελ καταδίωξε προφήτες του Κυρίου, υποστήριξε τη λατρεία του Βάαλ και οργάνωσε τη δικαστική δολοφονία του Ναβουθαί.','1 Kings 16–21; 2 Kings 9'),
('naaman','Naaman','Νεεμάν','Syrian commander healed of leprosy','Σύρος στρατηγός που θεραπεύτηκε από λέπρα','Naaman was healed after humbling himself and washing in the Jordan at Elisha’s instruction, confessing the God of Israel.','Ο Νεεμάν θεραπεύτηκε όταν ταπεινώθηκε και λούστηκε στον Ιορδάνη σύμφωνα με την εντολή του Ελισαίου, ομολογώντας τον Θεό του Ισραήλ.','2 Kings 5'),
('gehazi','Gehazi','Γιεζεί','Servant of Elisha','Υπηρέτης του Ελισαίου','Gehazi served Elisha but greedily deceived Naaman for gifts, receiving judgment for his dishonesty.','Ο Γιεζεί υπηρετούσε τον Ελισαίο αλλά από πλεονεξία εξαπάτησε τον Νεεμάν για δώρα και δέχθηκε κρίση για την ανεντιμότητά του.','2 Kings 4–5; 8:4–5'),
('nebuchadnezzar','Nebuchadnezzar II','Ναβουχοδονόσορ','King of Babylon','Βασιλιάς της Βαβυλώνας','Nebuchadnezzar conquered Jerusalem and appears prominently in Daniel, where his pride is humbled and he acknowledges the Most High.','Ο Ναβουχοδονόσορ κατέκτησε την Ιερουσαλήμ και εμφανίζεται έντονα στον Δανιήλ, όπου η υπερηφάνειά του ταπεινώνεται και αναγνωρίζει τον Ύψιστο.','2 Kings 24–25; Daniel 1–4'),
('belshazzar','Belshazzar','Βαλτάσαρ','Babylonian ruler in Daniel','Βαβυλώνιος άρχοντας στον Δανιήλ','Belshazzar profaned sacred vessels at a feast and saw the mysterious writing on the wall interpreted by Daniel.','Ο Βαλτάσαρ βεβήλωσε ιερά σκεύη σε συμπόσιο και είδε τη μυστηριώδη γραφή στον τοίχο που ερμήνευσε ο Δανιήλ.','Daniel 5'),
('cyrus','Cyrus the Great','Κύρος ο Μέγας','Persian king who permitted the return from exile','Πέρσης βασιλιάς που επέτρεψε την επιστροφή από την εξορία','Cyrus permitted exiled Judeans to return and rebuild the Temple and is strikingly called God’s “anointed” in Isaiah for this providential role.','Ο Κύρος επέτρεψε στους εξόριστους Ιουδαίους να επιστρέψουν και να ανοικοδομήσουν τον Ναό και ονομάζεται εντυπωσιακά «χριστός» του Θεού στον Ησαΐα για αυτόν τον προνοιακό ρόλο.','Isaiah 44:28–45:1; Ezra 1'),
('haman','Haman','Αμάν','Enemy of the Jews in Esther','Εχθρός των Ιουδαίων στο βιβλίο της Εσθήρ','Haman plotted to destroy the Jewish people in Persia but his plan was overturned through Esther and Mordecai.','Ο Αμάν σχεδίασε την εξόντωση των Ιουδαίων στην Περσία, αλλά το σχέδιό του ανατράπηκε μέσω της Εσθήρ και του Μαροδοχαίου.','Esther 3–7'),
('antiochus-iv','Antiochus IV Epiphanes','Αντίοχος Δʹ Επιφανής','Seleucid ruler and persecutor','Σελευκίδης άρχοντας και διώκτης','Antiochus IV imposed severe religious persecution, desecrated the Temple, and provoked the Maccabean resistance.','Ο Αντίοχος Δʹ επέβαλε σκληρό θρησκευτικό διωγμό, βεβήλωσε τον Ναό και προκάλεσε τη μακκαβαϊκή αντίσταση.','1 Maccabees 1; 2 Maccabees 5–7'),
('judas-iscariot','Judas Iscariot','Ιούδας Ισκαριώτης','One of the Twelve who betrayed Christ','Ένας από τους Δώδεκα που πρόδωσε τον Χριστό','Judas was chosen among the Twelve but betrayed Jesus for money; the Gospel accounts present his fall as a grave warning about greed, despair, and betrayal.','Ο Ιούδας επιλέχθηκε ανάμεσα στους Δώδεκα αλλά πρόδωσε τον Ιησού για χρήματα· τα Ευαγγέλια παρουσιάζουν την πτώση του ως βαριά προειδοποίηση για την πλεονεξία, την απόγνωση και την προδοσία.','Matthew 10:4; 26–27; John 12–13; Acts 1'),
('herod-great','Herod the Great','Ηρώδης ο Μέγας','King of Judea at the Nativity','Βασιλιάς της Ιουδαίας κατά τη Γέννηση','Herod appears in Matthew as the ruler who sought to kill the infant Christ and ordered the massacre of the children of Bethlehem.','Ο Ηρώδης εμφανίζεται στον Ματθαίο ως ο άρχοντας που επιδίωξε να θανατώσει τον βρέφος Χριστό και διέταξε τη σφαγή των παιδιών της Βηθλεέμ.','Matthew 2'),
('herod-antipas','Herod Antipas','Ηρώδης Αντύπας','Tetrarch of Galilee','Τετράρχης της Γαλιλαίας','Herod Antipas imprisoned and executed John the Baptist and later mocked Jesus during the Passion.','Ο Ηρώδης Αντύπας φυλάκισε και αποκεφάλισε τον Ιωάννη τον Βαπτιστή και αργότερα χλεύασε τον Ιησού κατά το Πάθος.','Matthew 14:1–12; Luke 23:6–12'),
('herodias','Herodias','Ηρωδιάδα','Wife of Herod Antipas','Σύζυγος του Ηρώδη Αντύπα','Herodias opposed John the Baptist for condemning her unlawful marriage and sought his death.','Η Ηρωδιάδα εναντιώθηκε στον Ιωάννη τον Βαπτιστή επειδή καταδίκαζε τον παράνομο γάμο της και επιδίωξε τον θάνατό του.','Mark 6:17–29'),
('pontius-pilate','Pontius Pilate','Πόντιος Πιλάτος','Roman governor who sentenced Christ','Ρωμαίος ηγεμόνας που καταδίκασε τον Χριστό','Pilate examined Jesus, declared he found no fault worthy of death, yet yielded to pressure and authorized the Crucifixion.','Ο Πιλάτος ανέκρινε τον Ιησού, δήλωσε ότι δεν έβρισκε ενοχή άξια θανάτου, αλλά υπέκυψε στην πίεση και επέτρεψε τη Σταύρωση.','Matthew 27; Mark 15; Luke 23; John 18–19'),
('caiaphas','Caiaphas','Καϊάφας','High priest during Christ’s Passion','Αρχιερέας κατά το Πάθος του Χριστού','Caiaphas presided over the high-priestly leadership involved in the proceedings against Jesus.','Ο Καϊάφας προΐστατο της αρχιερατικής ηγεσίας που εμπλέκεται στις διαδικασίες εναντίον του Ιησού.','Matthew 26:3,57–68; John 11:49–53; 18:13–28'),
('annas','Annas','Άννας','Former high priest and influential priestly elder','Πρώην αρχιερέας και ισχυρός ιερατικός πρεσβύτερος','Annas, father-in-law of Caiaphas, questioned Jesus and remained influential in the priestly leadership.','Ο Άννας, πεθερός του Καϊάφα, ανέκρινε τον Ιησού και παρέμεινε ισχυρός στην ιερατική ηγεσία.','Luke 3:2; John 18:13–24; Acts 4:6'),
('barabbas','Barabbas','Βαραββάς','Prisoner released instead of Jesus','Φυλακισμένος που απελευθερώθηκε αντί του Ιησού','Barabbas, imprisoned for violence and rebellion, was released when the crowd asked Pilate to crucify Jesus instead.','Ο Βαραββάς, φυλακισμένος για βία και στάση, απελευθερώθηκε όταν το πλήθος ζήτησε από τον Πιλάτο να σταυρώσει τον Ιησού αντί γι’ αυτόν.','Matthew 27:15–26; Mark 15:6–15; Luke 23:18–25; John 18:39–40'),
('simon-magus','Simon Magus','Σίμων ο Μάγος','Samaritan magician rebuked by Peter','Σαμαρείτης μάγος που ελέγχθηκε από τον Πέτρο','Simon believed and was baptized but tried to buy apostolic spiritual authority, leading Peter to call him to repentance.','Ο Σίμων πίστεψε και βαπτίστηκε αλλά προσπάθησε να αγοράσει αποστολική πνευματική εξουσία, και ο Πέτρος τον κάλεσε σε μετάνοια.','Acts 8:9–24'),
('elymas','Elymas (Bar-Jesus)','Ελύμας (Βαριησούς)','Magician who opposed Paul','Μάγος που αντιστάθηκε στον Παύλο','Elymas opposed Paul and Barnabas before the proconsul Sergius Paulus and was struck temporarily blind.','Ο Ελύμας αντιστάθηκε στον Παύλο και τον Βαρνάβα ενώπιον του ανθύπατου Σεργίου Παύλου και τυφλώθηκε προσωρινά.','Acts 13:6–12'),
('felix-governor','Antonius Felix','Αντώνιος Φήλιξ','Roman governor who heard Paul','Ρωμαίος ηγεμόνας που άκουσε τον Παύλο','Felix heard Paul’s defense and teaching about righteousness and judgment but kept him imprisoned, hoping for a bribe.','Ο Φήλιξ άκουσε την απολογία και τη διδασκαλία του Παύλου για δικαιοσύνη και κρίση, αλλά τον κράτησε φυλακισμένο ελπίζοντας σε δωροδοκία.','Acts 23:24–24:27'),
('festus','Porcius Festus','Πόρκιος Φήστος','Roman governor who handled Paul’s appeal','Ρωμαίος ηγεμόνας που χειρίστηκε την έφεση του Παύλου','Festus succeeded Felix and heard Paul’s case after Paul appealed to Caesar.','Ο Φήστος διαδέχθηκε τον Φήλικα και άκουσε την υπόθεση του Παύλου αφού ο Παύλος επικαλέστηκε τον Καίσαρα.','Acts 24:27–26:32'),
('agrippa-ii','Herod Agrippa II','Ηρώδης Αγρίππας Βʹ','Client king who heard Paul','Βασιλιάς που άκουσε τον Παύλο','Agrippa II listened to Paul’s testimony and acknowledged that Paul had done nothing deserving death or imprisonment.','Ο Αγρίππας Βʹ άκουσε τη μαρτυρία του Παύλου και αναγνώρισε ότι δεν είχε κάνει τίποτε άξιο θανάτου ή φυλάκισης.','Acts 25–26'),
('ananias-sapphira','Ananias and Sapphira','Ανανίας και Σαπφείρα','Early Christians judged for deceit','Πρώιμοι χριστιανοί που κρίθηκαν για απάτη','Ananias and Sapphira lied about money from a property sale and died after being confronted by Peter, a severe warning about hypocrisy before God.','Ο Ανανίας και η Σαπφείρα είπαν ψέματα για χρήματα από πώληση περιουσίας και πέθαναν μετά τον έλεγχο του Πέτρου, αποτελώντας αυστηρή προειδοποίηση για την υποκρισία ενώπιον του Θεού.','Acts 5:1–11'),
('satan','Satan / the Devil','Σατανάς / Διάβολος','Adversary and tempter','Αντίδικος και πειραστής','Scripture presents Satan as the adversary, tempter, accuser, and enemy defeated by Christ; Orthodox Christianity rejects every form of invocation or fascination with evil spirits.','Η Γραφή παρουσιάζει τον Σατανά ως αντίδικο, πειραστή, κατήγορο και εχθρό που νικιέται από τον Χριστό· η Ορθόδοξη Χριστιανοσύνη απορρίπτει κάθε επίκληση ή γοητεία προς τα πονηρά πνεύματα.','Job 1–2; Matthew 4:1–11; Luke 10:18; Revelation 12:9'),
('demons','Demons / Unclean Spirits','Δαιμόνια / Ακάθαρτα Πνεύματα','Fallen spiritual powers opposed to God','Πεσμένες πνευματικές δυνάμεις που αντιτίθενται στον Θεό','The Gospels repeatedly show Christ rebuking and expelling unclean spirits, revealing His complete authority over evil.','Τα Ευαγγέλια δείχνουν επανειλημμένα τον Χριστό να επιτιμά και να εκβάλλει ακάθαρτα πνεύματα, φανερώνοντας την απόλυτη εξουσία Του πάνω στο κακό.','Mark 1:21–28; 5:1–20; Luke 10:17–20'),
('legion','“Legion” of Demons','«Λεγεών» δαιμονίων','Group of unclean spirits expelled by Christ','Ομάδα ακαθάρτων πνευμάτων που εξέβαλε ο Χριστός','In the Gerasene account, many unclean spirits identify themselves as “Legion”; Christ expels them and restores the possessed man.','Στη διήγηση των Γερασηνών, πολλά ακάθαρτα πνεύματα ονομάζονται «Λεγεών»· ο Χριστός τα εκβάλλει και αποκαθιστά τον δαιμονισμένο άνθρωπο.','Mark 5:1–20; Luke 8:26–39'),
]
for id,en,el,ren,rel,sen,sel,sc in ctx:
    add(context,mk(id,en,el,'biblical-context',ren,rel,sen,sel,'No saintly commemoration in this catalog','Δεν υπάρχει αγιολογική μνήμη σε αυτόν τον κατάλογο',sc,notes_en='Included to make biblical search more complete and to provide Orthodox educational context. No prayer is addressed to this figure.',notes_el='Περιλαμβάνεται για πληρέστερη βιβλική αναζήτηση και ορθόδοξο εκπαιδευτικό πλαίσιο. Δεν απευθύνεται προσευχή σε αυτό το πρόσωπο.',venerated=False))

# Write additive files.
sets=[('expanded-biblical.js','ORTHODOX_EXPANDED_BIBLICAL',expanded),('church-saints.js','ORTHODOX_CHURCH_SAINTS',church),('feasts.js','ORTHODOX_FEASTS',feasts),('biblical-context.js','ORTHODOX_BIBLICAL_CONTEXT',context)]
for fn,var,arr in sets:
    (data_dir/fn).write_text(f'window.{var} = '+json.dumps(arr,ensure_ascii=False,separators=(',',':'))+';\n',encoding='utf-8')

# Catalog merger loaded after all datasets and before app.
(data_dir/'catalog.js').write_text("window.ORTHODOX_ENTRIES = [\n  ...(window.ORTHODOX_ENTRIES || []),\n  ...(window.ORTHODOX_EXPANDED_BIBLICAL || []),\n  ...(window.ORTHODOX_CHURCH_SAINTS || []),\n  ...(window.ORTHODOX_FEASTS || []),\n  ...(window.ORTHODOX_BIBLICAL_CONTEXT || []),\n  ...(window.ORTHODOX_FURTHER_EXPANSION || []),\n  ...(window.ORTHODOX_DEEP_BIBLICAL || [])\n];\n",encoding='utf-8')

# SVG medallions for every new entry. These are illustrative, not canonical icons.
palettes={
 'christ':('#ffd95a','#ff7b55'),'theotokos':('#6bd7ff','#7772ff'),'angel':('#71f3ff','#8798ff'),'forefather':('#ffc86a','#ff8b66'),'righteous':('#9bf58a','#42c89a'),'prophet':('#c196ff','#6f63ff'),'apostle':('#ff8cca','#b35cff'),'nt-saint':('#71edc4','#46a7ca'),'church-saint':('#ffac78','#ef6b7b'),'feast':('#ffe36a','#ff8c63'),'biblical-context':('#a9b1c9','#606b87')}

def initials(name):
    words=[w for w in re.sub(r'[^A-Za-z0-9 ]',' ',name).split() if w.lower() not in {'saint','saints','the','of','and','apostle','righteous','prophet'}]
    if not words: words=name.split()
    return ''.join(w[0].upper() for w in words[:2])[:2]

def svg_for(e):
    c1,c2=palettes.get(e['category'],('#75e7ff','#a66cff'))
    ini=initials(e['name']['en'])
    title=e['name']['en'].replace('&','&amp;').replace('<','&lt;').replace('>','&gt;')
    halo='' if e.get('venerated') is False or e['category']=='biblical-context' else '<circle cx="128" cy="91" r="42" fill="none" stroke="#fff4a8" stroke-width="7" opacity=".82"/>'
    wings=''
    accessory=''
    if e['category']=='angel':
        wings='<path d="M88 126C46 108 28 77 35 47c29 13 47 32 59 59M168 126c42-18 60-49 53-79-29 13-47 32-59 59" fill="#eafcff" opacity=".72"/>'
        accessory='<path d="M128 143v45M108 166h40" stroke="#fff" stroke-width="7" stroke-linecap="round" opacity=".9"/>'
    elif e['category'] in {'prophet','forefather','righteous'}:
        accessory='<path d="M73 164h37v45H73z" rx="4" fill="#fff6c8" opacity=".85"/><path d="M82 175h20M82 185h20M82 195h16" stroke="#76632f" stroke-width="3"/>'
    elif e['category'] in {'apostle','nt-saint','church-saint'}:
        accessory='<path d="M152 158h31v44h-31z" fill="#f7edff" opacity=".88"/><path d="M168 166v28M159 180h18" stroke="#7b4a89" stroke-width="4"/>'
    elif e['category']=='feast':
        accessory='<path d="M128 53v76M105 81h46" stroke="#fff8c8" stroke-width="9" stroke-linecap="round" opacity=".95"/><path d="M69 193h118" stroke="#fff" stroke-width="7" stroke-linecap="round" opacity=".72"/>'
    elif e['category']=='biblical-context':
        accessory='<path d="M91 174h74" stroke="#e8ebf5" stroke-width="6" stroke-linecap="round" opacity=".7"/><circle cx="128" cy="130" r="51" fill="none" stroke="#e8ebf5" stroke-width="3" opacity=".28"/>'
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 256 256" role="img" aria-labelledby="t"><title id="t">Illustrative medallion for {title}</title><defs><radialGradient id="g" cx="30%" cy="18%" r="90%"><stop stop-color="#fff" stop-opacity=".35"/><stop offset=".28" stop-color="{c1}"/><stop offset="1" stop-color="{c2}"/></radialGradient><filter id="s"><feDropShadow dx="0" dy="7" stdDeviation="8" flood-opacity=".25"/></filter></defs><circle cx="128" cy="128" r="124" fill="url(#g)"/><circle cx="128" cy="128" r="115" fill="none" stroke="#fff" stroke-opacity=".48" stroke-width="4"/>{wings}{halo}<g filter="url(#s)"><circle cx="128" cy="99" r="31" fill="#f5d4b5"/><path d="M72 211c5-55 25-79 56-79s51 24 56 79" fill="#3d275f" opacity=".88"/></g>{accessory}<circle cx="128" cy="128" r="115" fill="none" stroke="#fff" stroke-opacity=".2" stroke-width="2"/><rect x="74" y="211" width="108" height="30" rx="15" fill="#160f35" fill-opacity=".78"/><text x="128" y="232" text-anchor="middle" font-family="system-ui,Arial,sans-serif" font-size="18" font-weight="800" fill="#fff">{ini}</text></svg>'''

all_new=expanded+church+feasts+context
for e in all_new:
    p=img_dir/f"{e['id']}.svg"
    if not p.exists(): p.write_text(svg_for(e),encoding='utf-8')

# Developer-readable catalog report. Include additive expansion files if they already exist.
combined_for_report=base+all_new
extra_report={}
for extra_fn in ('further-expansion.js','deep-biblical.js'):
    extra_path=data_dir/extra_fn
    if extra_path.exists():
        try:
            extra_arr=json.loads(extra_path.read_text(encoding='utf-8').split('=',1)[1].strip().rstrip(';'))
            combined_for_report.extend(extra_arr)
            extra_report[extra_fn]=len(extra_arr)
        except Exception:
            extra_report[extra_fn]='unreadable'
report={
 'base_entries':len(base),'expanded_biblical':len(expanded),'church_saints':len(church),'feasts':len(feasts),'biblical_context':len(context),
 'additive_datasets':extra_report,'total':len(combined_for_report),'categories':{}
}
from collections import Counter
cnt=Counter(e['category'] for e in combined_for_report); report['categories']=dict(sorted(cnt.items()))
(data_dir/'catalog-stats.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps(report,ensure_ascii=False,indent=2))
