#!/usr/bin/env python3
from __future__ import annotations
import json, html, re
from pathlib import Path
from collections import Counter

ROOT=Path(__file__).resolve().parents[2]
DATA=ROOT/'web'/'data'
IMG=ROOT/'web'/'images'/'people'
IMG.mkdir(parents=True, exist_ok=True)

BASE_FILES=['entries.js','expanded-biblical.js','church-saints.js','feasts.js','biblical-context.js','further-expansion.js','deep-biblical.js','comprehensive-expansion.js']
def load(path): return json.loads(path.read_text(encoding='utf-8').split('=',1)[1].strip().rstrip(';'))
base=[]
for fn in BASE_FILES: base.extend(load(DATA/fn))
base_ids={e['id'] for e in base}

OCA_ARCH='https://www.oca.org/saints/lives/2042/11/08/103244-synaxis-of-the-archangel-michael-and-the-other-bodiless-powers'

def saint(id,en,el,role_en,role_el,story_en,story_el,feast_en,feast_el,source=None,scripture='Church tradition / Lives of the Saints',aliases=None,category='church-saint'):
    prayer_en=(f'Holy {en}, pray to God for us, that we may learn from your witness and follow Christ with faith, repentance, courage, and love.' if category!='angel' else f'Holy Archangel {en.split()[-1]}, servant of God, intercede for us and help us live faithfully before God.')
    prayer_el=(f'Άγιε/Αγία {el}, πρέσβευε στον Θεό για μας, ώστε να διδαχθούμε από τη μαρτυρία σου και να ακολουθούμε τον Χριστό με πίστη, μετάνοια, θάρρος και αγάπη.' if category!='angel' else f'Άγιε Αρχάγγελε {el.split()[-1]}, λειτουργέ του Θεού, πρέσβευε για μας και βοήθησέ μας να ζούμε πιστά ενώπιον του Θεού.')
    e={
      'id':id,'name':{'en':en,'el':el},'category':category,
      'role':{'en':role_en,'el':role_el},
      'story':{'en':story_en,'el':story_el},
      'feast':{'en':feast_en,'el':feast_el},'scripture':scripture,
      'prayer':{'en':prayer_en,'el':prayer_el},
      'notes':{'en':'The profile distinguishes well-attested historical or biblical information from later devotional tradition. Local calendars may differ in date or emphasis.',
               'el':'Το προφίλ διακρίνει τις καλά τεκμηριωμένες ιστορικές ή βιβλικές πληροφορίες από τη μεταγενέστερη ευσεβή παράδοση. Τα τοπικά ημερολόγια μπορεί να διαφέρουν ως προς την ημερομηνία ή την έμφαση.'},
      'aliases':aliases or [],'image':f'web/images/catalog/{id}.svg'
    }
    if source: e['sourceUrl']=source; e['sources']=[{'label':{'en':'Orthodox reference','el':'Ορθόδοξη αναφορά'},'url':source}]
    e['search']=' '.join([en,el,role_en,role_el,scripture]+(aliases or []))
    return e

E=[]
# Archangels named in received Eastern Orthodox tradition / OCA Synaxis.
arch=[
('uriel','Archangel Uriel','Αρχάγγελος Ουριήλ','Archangel associated with divine light and enlightenment','Αρχάγγελος που συνδέεται με το θείο φως και τον φωτισμό','Orthodox tradition names Uriel among the archangels commemorated with Michael. The name is linked with divine light; 2 Esdras/4 Ezra preserves appearances of Uriel in an interpretive role.','Η Ορθόδοξη παράδοση ονομάζει τον Ουριήλ μεταξύ των αρχαγγέλων που τιμώνται μαζί με τον Μιχαήλ. Το όνομα συνδέεται με το θείο φως· το Β΄ Έσδρα/Δ΄ Έσδρα διασώζει εμφανίσεις του Ουριήλ με ερμηνευτικό ρόλο.','2 Esdras 4–5; Orthodox angelic tradition'),
('selaphiel','Archangel Selaphiel','Αρχάγγελος Σελαφιήλ','Archangel associated with prayer','Αρχάγγελος που συνδέεται με την προσευχή','Selaphiel (Salathiel) is named in Orthodox angelic tradition as one who encourages prayer and intercedes for humanity. The Church’s liturgical memory places him within the Synaxis of the Bodiless Powers, not as an independent object of worship.','Ο Σελαφιήλ (Σαλαθιήλ) ονομάζεται στην ορθόδοξη αγγελική παράδοση ως εκείνος που παρακινεί στην προσευχή και πρεσβεύει για την ανθρωπότητα. Η λειτουργική μνήμη τον εντάσσει στη Σύναξη των Ασωμάτων Δυνάμεων, όχι ως ανεξάρτητο αντικείμενο λατρείας.','2 Esdras 5:15; Orthodox angelic tradition'),
('jehudiel','Archangel Jehudiel','Αρχάγγελος Ιεγουδιήλ','Archangel associated with glorifying God and holy labor','Αρχάγγελος που συνδέεται με τη δοξολογία του Θεού και τον άγιο κόπο','Jehudiel (Jegudiel) belongs to the group of archangels named in Eastern Orthodox tradition. He is associated with zeal for God’s glory and encouragement in works undertaken for God.','Ο Ιεγουδιήλ (Ιεχουδιήλ) ανήκει στην ομάδα των αρχαγγέλων που ονομάζονται στην ανατολική ορθόδοξη παράδοση. Συνδέεται με τον ζήλο για τη δόξα του Θεού και την ενίσχυση στους κόπους που γίνονται για τον Θεό.','Orthodox angelic tradition'),
('barachiel','Archangel Barachiel','Αρχάγγελος Βαραχιήλ','Archangel associated with God’s blessings','Αρχάγγελος που συνδέεται με τις ευλογίες του Θεού','Barachiel is named in Orthodox tradition among the archangels and is associated with God’s blessings and mercy. Iconographic tradition often gives him symbols of blessing such as roses.','Ο Βαραχιήλ ονομάζεται στην Ορθόδοξη παράδοση μεταξύ των αρχαγγέλων και συνδέεται με τις ευλογίες και το έλεος του Θεού. Η εικονογραφική παράδοση συχνά του αποδίδει σύμβολα ευλογίας, όπως τριαντάφυλλα.','Orthodox angelic tradition'),
('jeremiel','Archangel Jeremiel','Αρχάγγελος Ιερεμιήλ','Archangel associated with raising the mind toward God','Αρχάγγελος που συνδέεται με την ανύψωση του νου προς τον Θεό','Jeremiel is included in some Orthodox lists of the archangels. 2 Esdras/4 Ezra associates him with the destiny of souls and the completion of the age; later Orthodox explanation connects his name with raising the heart and mind toward God.','Ο Ιερεμιήλ περιλαμβάνεται σε ορισμένους ορθόδοξους καταλόγους αρχαγγέλων. Το Β΄ Έσδρα/Δ΄ Έσδρα τον συνδέει με την πορεία των ψυχών και την ολοκλήρωση του αιώνα· μεταγενέστερη ορθόδοξη ερμηνεία συνδέει το όνομά του με την ανύψωση της καρδιάς και του νου προς τον Θεό.','2 Esdras 4:36; Orthodox angelic tradition')]
for x in arch:
    E.append(saint(x[0],x[1],x[2],x[3],x[4],x[5],x[6],'8 November — Synaxis of the Archangel Michael and the Other Bodiless Powers','8 Νοεμβρίου — Σύναξη του Αρχαγγέλου Μιχαήλ και των λοιπών Ασωμάτων Δυνάμεων',OCA_ARCH,x[7],category='angel'))

# Carefully selected additions with established Orthodox commemoration.
rows=[
('john-russian','Saint John the Russian','Άγιος Ιωάννης ο Ρώσος','Confessor and wonderworker','Ομολογητής και θαυματουργός','Born around 1690, John served as a soldier and was captured during the Russo-Turkish conflict. Enslaved in Prokopion of Asia Minor, he refused conversion to Islam while serving his master with humility. He lived an ascetic Christian life, prayed in a nearby church, and became known for holiness. After his repose his incorrupt relics became a focus of veneration; after the population exchange they were taken to Prokopi on Euboea.','Γεννημένος περίπου το 1690, ο Ιωάννης υπηρέτησε ως στρατιώτης και αιχμαλωτίστηκε σε ρωσοτουρκική σύγκρουση. Ως δούλος στο Προκόπι της Μικράς Ασίας αρνήθηκε να εξισλαμιστεί, ενώ υπηρετούσε τον κύριό του με ταπείνωση. Έζησε ασκητικά, προσευχόταν σε κοντινό ναό και έγινε γνωστός για την αγιότητά του. Μετά την κοίμησή του τα άφθαρτα λείψανά του τιμήθηκαν ευρύτατα και, μετά την ανταλλαγή πληθυσμών, μεταφέρθηκαν στο Προκόπι Ευβοίας.','27 May','27 Μαΐου','https://www.oca.org/saints/lives/2016/05/27/101545-saint-john-the-russian-and-confessor-whose-relics-are-on-the-isl'),
('nicholas-japan','Saint Nicholas of Japan','Άγιος Νικόλαος Ιαπωνίας','Equal-to-the-Apostles, missionary and bishop','Ισαπόστολος, ιεραπόστολος και επίσκοπος','Born Ivan Kasatkin in 1836, he became a monk and priest and went to the Russian consular church at Hakodate. He mastered Japanese language and culture, translated liturgical and biblical texts, trained local clergy, and built a native Orthodox mission rather than a foreign enclave. During the Russo-Japanese War he remained with his Japanese flock while refraining from public services for Russian victory. He became the first Archbishop of the Orthodox Church in Japan.','Γεννημένος ως Ιβάν Κασάτκιν το 1836, έγινε μοναχός και ιερέας και πήγε στον ρωσικό προξενικό ναό της Χακοντάτε. Έμαθε βαθιά την ιαπωνική γλώσσα και τον πολιτισμό, μετέφρασε λειτουργικά και βιβλικά κείμενα, εκπαίδευσε ντόπιο κλήρο και οικοδόμησε γηγενή ορθόδοξη ιεραποστολή. Κατά τον Ρωσοϊαπωνικό Πόλεμο παρέμεινε με το ιαπωνικό ποίμνιό του. Έγινε ο πρώτος Αρχιεπίσκοπος της Ορθόδοξης Εκκλησίας στην Ιαπωνία.','3 February','3 Φεβρουαρίου','https://www.oca.org/saints/lives/2017/02/03/100455-saint-nicholas-enlightener-of-japan'),
('cyprian-carthage','Saint Cyprian of Carthage','Άγιος Κυπριανός Καρχηδόνος','Hieromartyr and bishop','Ιερομάρτυρας και επίσκοπος','Thascius Cyprianus was born around 200 in Carthage and became a highly educated rhetorician before embracing Christianity. Soon ordained and then chosen as bishop, he guided the Church through persecution, controversy over the reconciliation of the lapsed, plague, and debates about baptism and ecclesial unity. His letters and treatises became major witnesses to early episcopal and sacramental life. He was exiled and then beheaded in 258 under Valerian.','Ο Θάσκιος Κυπριανός γεννήθηκε περίπου το 200 στην Καρχηδόνα και έγινε μορφωμένος ρήτορας πριν ασπαστεί τον Χριστιανισμό. Χειροτονήθηκε σύντομα και κατόπιν εξελέγη επίσκοπος, καθοδηγώντας την Εκκλησία μέσα από διωγμούς, τη διαμάχη για την επανένταξη των πεπτωκότων, επιδημία και συζητήσεις για το βάπτισμα και την εκκλησιαστική ενότητα. Οι επιστολές και πραγματείες του αποτελούν σημαντική μαρτυρία της αρχαίας εκκλησιαστικής ζωής. Εξορίστηκε και αποκεφαλίστηκε το 258 επί Ουαλεριανού.','31 August','31 Αυγούστου','https://www.oca.org/saints/lives/2017/08/31/102443-hieromartyr-cyprian-bishop-of-carthage'),
('ambrose-optina','Venerable Ambrose of Optina','Όσιος Αμβρόσιος της Όπτινα','Elder and spiritual father','Γέροντας και πνευματικός πατέρας','Alexander Grenkov was born in 1812, studied at seminary, and after illness and a long inner struggle entered Optina Monastery in 1839. Tonsured Ambrose, he became a disciple of the elders Leonid and Macarius. Chronic illness limited his liturgical activity but deepened his ministry of spiritual counsel. For decades people from every social class sought his advice; his pastoral wisdom combined humor, discernment, compassion, and insistence on humble prayer. He reposed in 1891.','Ο Αλέξανδρος Γκρένκοφ γεννήθηκε το 1812, σπούδασε σε ιεροδιδασκαλείο και, έπειτα από ασθένεια και μακρά εσωτερική πάλη, εισήλθε στη Μονή Όπτινα το 1839. Ως μοναχός Αμβρόσιος έγινε μαθητής των γερόντων Λεωνίδα και Μακαρίου. Η χρόνια ασθένεια περιόρισε τη λειτουργική του δράση αλλά βάθυνε τη διακονία της πνευματικής καθοδήγησης. Για δεκαετίες άνθρωποι κάθε κοινωνικής τάξης ζητούσαν τη συμβουλή του· η ποιμαντική του σοφία συνδύαζε χιούμορ, διάκριση, συμπόνια και ταπεινή προσευχή. Εκοιμήθη το 1891.','10 October','10 Οκτωβρίου','https://www.oca.org/saints/lives/2017/10/10/102934-venerable-ambrose-of-optina'),
('macarius-optina','Venerable Macarius of Optina','Όσιος Μακάριος της Όπτινα','Elder, translator and spiritual father','Γέροντας, μεταφραστής και πνευματικός πατέρας','Born Michael Ivanov in 1788, he entered monastic life and became one of the central Optina elders. He worked closely with disciples and educated laypeople to edit and publish Russian translations of patristic and ascetical texts, helping renew the study of the Fathers in nineteenth-century Russia. As a confessor and spiritual guide he stressed humility, obedience, self-knowledge, and steady prayer. He reposed in 1860.','Γεννημένος ως Μιχαήλ Ιβάνοφ το 1788, εισήλθε στον μοναχισμό και έγινε ένας από τους κεντρικούς γέροντες της Όπτινα. Συνεργάστηκε με μαθητές και μορφωμένους λαϊκούς για την έκδοση ρωσικών μεταφράσεων πατερικών και ασκητικών κειμένων, συμβάλλοντας στην ανανέωση της μελέτης των Πατέρων στη Ρωσία του 19ου αιώνα. Ως εξομολόγος και πνευματικός τόνιζε την ταπείνωση, την υπακοή, την αυτογνωσία και τη σταθερή προσευχή. Εκοιμήθη το 1860.','7 September','7 Σεπτεμβρίου','https://www.oca.org/saints/lives/2014/09/07/148999-venerable-macarius-of-optina'),
('philaret-moscow','Saint Philaret of Moscow','Άγιος Φιλάρετος Μόσχας','Metropolitan, theologian and preacher','Μητροπολίτης, θεολόγος και ιεροκήρυκας','Born Vasily Drozdov in 1782, Philaret became one of the most influential Russian hierarchs of the nineteenth century. A gifted preacher and theologian, he participated in biblical translation work, theological education, and major Church affairs. He served for decades as Metropolitan of Moscow, corresponded widely, and was respected for precision of doctrine combined with pastoral restraint. He reposed in 1867.','Γεννημένος ως Βασίλειος Ντροζντόφ το 1782, ο Φιλάρετος έγινε ένας από τους σημαντικότερους Ρώσους ιεράρχες του 19ου αιώνα. Χαρισματικός ιεροκήρυκας και θεολόγος, συμμετείχε σε μεταφραστικό έργο της Αγίας Γραφής, στη θεολογική εκπαίδευση και σε μεγάλες εκκλησιαστικές υποθέσεις. Υπηρέτησε επί δεκαετίες ως Μητροπολίτης Μόσχας και διακρίθηκε για τη δογματική ακρίβεια και την ποιμαντική σύνεση. Εκοιμήθη το 1867.','19 November','19 Νοεμβρίου','https://www.oca.org/saints/lives/2035/11/19'),
('isidore-seville','Saint Isidore of Seville','Άγιος Ισίδωρος Σεβίλλης','Bishop and scholar','Επίσκοπος και λόγιος','Isidore, bishop of Seville in Visigothic Spain, combined pastoral leadership with an extraordinary program of learning. His works preserved and organized much of the classical and Christian knowledge available in the Latin West, while his ecclesial work supported councils, education, clerical formation, and the consolidation of Nicene Christianity. He reposed in 636 and is honored in the undivided Church.','Ο Ισίδωρος, επίσκοπος Σεβίλλης στη Βησιγοτθική Ισπανία, συνδύασε ποιμαντική ηγεσία με εξαιρετικό μορφωτικό έργο. Τα συγγράμματά του διέσωσαν και οργάνωσαν μεγάλο μέρος της κλασικής και χριστιανικής γνώσης της λατινικής Δύσης, ενώ το εκκλησιαστικό του έργο στήριξε συνόδους, εκπαίδευση και κληρική κατάρτιση. Εκοιμήθη το 636 και τιμάται στην αδιαίρετη Εκκλησία.','4 April','4 Απριλίου','https://www.oca.org/saints/lives?q=Isidore%20of%20Seville'),
('paul-simple','Venerable Paul the Simple','Όσιος Παύλος ο Απλός','Desert Father and disciple of Saint Anthony','Πατέρας της ερήμου και μαθητής του Αγίου Αντωνίου','Paul entered the Egyptian desert at an advanced age and became a disciple of Saint Anthony the Great. The sayings of the Desert Fathers remember his simplicity, obedience, humility, discernment, and spiritual gifts. His title “the Simple” points not to ignorance but to an undivided and guileless heart formed by ascetic obedience.','Ο Παύλος εισήλθε στην αιγυπτιακή έρημο σε προχωρημένη ηλικία και έγινε μαθητής του Μεγάλου Αντωνίου. Τα Αποφθέγματα των Πατέρων της Ερήμου διασώζουν τη μνήμη της απλότητας, υπακοής, ταπείνωσης, διάκρισης και των πνευματικών του χαρισμάτων. Ο τίτλος «ο Απλός» δεν δηλώνει άγνοια αλλά αδιαίρετη και άδολη καρδιά που μορφώθηκε με την ασκητική υπακοή.','7 March; local calendars may vary','7 Μαρτίου· πιθανές τοπικές διαφοροποιήσεις','https://www.oca.org/saints/lives?q=Paul%20the%20Simple'),
('pambo','Venerable Pambo of Nitria','Όσιος Παμβώ της Νιτρίας','Desert Father','Πατέρας της ερήμου','Pambo was one of the renowned fourth-century ascetics of the Egyptian desert, associated with Nitria and the circle of Saint Anthony. The desert tradition remembers his silence, sobriety, generosity, and refusal to speak before he had lived what he heard from Scripture. Stories about him emphasize the slow work of repentance over display or clever speech.','Ο Παμβώ ήταν ένας από τους γνωστούς ασκητές του 4ου αιώνα στην αιγυπτιακή έρημο, συνδεδεμένος με τη Νιτρία και τον κύκλο του Μεγάλου Αντωνίου. Η ερημιτική παράδοση θυμάται τη σιωπή, τη νηφαλιότητα, τη γενναιοδωρία και την άρνησή του να μιλήσει πριν βιώσει όσα άκουγε από τη Γραφή. Οι διηγήσεις γι’ αυτόν τονίζουν τη σταδιακή εργασία της μετάνοιας αντί για επίδειξη ή ευφυολογία.','18 July','18 Ιουλίου','https://www.oca.org/saints/lives?q=Pambo'),
('mark-ascetic','Venerable Mark the Ascetic','Όσιος Μάρκος ο Ασκητής','Ascetical writer','Ασκητικός συγγραφέας','Mark the Ascetic, also called Mark the Monk, is known primarily through influential spiritual writings preserved in the Philokalic tradition. His works treat baptismal grace, repentance, watchfulness, the relation of works and grace, and the danger of imagining that spiritual progress earns God’s gifts. Biographical details are sparse, and the profile keeps that uncertainty explicit.','Ο Μάρκος ο Ασκητής, γνωστός και ως Μάρκος ο Μοναχός, είναι γνωστός κυρίως από σημαντικά πνευματικά έργα που διασώθηκαν στη φιλοκαλική παράδοση. Τα κείμενά του πραγματεύονται τη βαπτισματική χάρη, τη μετάνοια, τη νήψη, τη σχέση έργων και χάριτος και τον κίνδυνο να θεωρείται η πνευματική πρόοδος ως «μισθός». Τα βιογραφικά στοιχεία είναι περιορισμένα και η καταχώριση το δηλώνει ρητά.','5 March in many calendars','5 Μαρτίου σε πολλά ημερολόγια','https://www.oca.org/saints/lives?q=Mark%20the%20Ascetic'),
('diadochos-photiki','Saint Diadochos of Photiki','Άγιος Διάδοχος Φωτικής','Bishop and spiritual writer','Επίσκοπος και πνευματικός συγγραφέας','Diadochos was a fifth-century bishop of Photiki in Epirus and an important ascetical theologian. His “Hundred Chapters on Spiritual Knowledge and Discrimination” became influential in the later Philokalic tradition. He writes about grace, baptism, discernment, the Jesus Prayer, love of God, and the purification of the heart while warning against confusing imagination with spiritual experience.','Ο Διάδοχος ήταν επίσκοπος Φωτικής στην Ήπειρο τον 5ο αιώνα και σημαντικός ασκητικός θεολόγος. Τα «Εκατό Γνωστικά Κεφάλαια» επηρέασαν βαθιά τη μεταγενέστερη φιλοκαλική παράδοση. Γράφει για τη χάρη, το βάπτισμα, τη διάκριση, την ευχή του Ιησού, την αγάπη του Θεού και την κάθαρση της καρδιάς, προειδοποιώντας να μη συγχέεται η φαντασία με την πνευματική εμπειρία.','29 March in some traditions; consult local calendar','29 Μαρτίου σε ορισμένες παραδόσεις· συμβουλευθείτε το τοπικό ημερολόγιο','https://www.oca.org/saints/lives?q=Diadochos'),
('theodore-sykeon','Saint Theodore of Sykeon','Άγιος Θεόδωρος Συκεώτης','Bishop, ascetic and wonderworker','Επίσκοπος, ασκητής και θαυματουργός','Theodore was born in sixth-century Galatia near Sykeon. From childhood he was drawn to prayer and ascetic life, lived in severe discipline near a shrine of Saint George, and eventually gathered disciples. Though he preferred solitude he was made bishop of Anastasiopolis; later he was released from episcopal office and returned to monastic life. His early Life is a major source for late antique Byzantine religious history.','Ο Θεόδωρος γεννήθηκε τον 6ο αιώνα στη Γαλατία, κοντά στα Σύκεα. Από παιδί στράφηκε στην προσευχή και την άσκηση, έζησε με αυστηρή πειθαρχία κοντά σε προσκύνημα του Αγίου Γεωργίου και σταδιακά συγκέντρωσε μαθητές. Παρότι αγαπούσε την ησυχία, έγινε επίσκοπος Αναστασιουπόλεως· αργότερα απαλλάχθηκε από το αξίωμα και επέστρεψε στη μοναχική ζωή. Ο αρχαίος Βίος του είναι σημαντική πηγή για τη βυζαντινή ιστορία.','22 April','22 Απριλίου','https://www.oca.org/saints/lives?q=Theodore%20of%20Sykeon'),
('tarasius-constantinople','Saint Tarasius of Constantinople','Άγιος Ταράσιος Κωνσταντινουπόλεως','Patriarch and defender of holy icons','Πατριάρχης και υπερασπιστής των ιερών εικόνων','A senior imperial official before becoming Patriarch of Constantinople, Tarasius accepted the office while insisting that the icon controversy be settled by an ecumenical council. He presided at the Seventh Ecumenical Council in Nicaea in 787, which distinguished the veneration shown to icons from the worship due to God alone. He was also remembered for personal austerity and care for the poor.','Ανώτερος αυτοκρατορικός αξιωματούχος πριν γίνει Πατριάρχης Κωνσταντινουπόλεως, ο Ταράσιος δέχθηκε το αξίωμα με την προϋπόθεση ότι η εικονομαχική διαμάχη θα λυνόταν από οικουμενική σύνοδο. Προήδρευσε στην Ζ΄ Οικουμενική Σύνοδο στη Νίκαια το 787, η οποία διέκρινε την τιμητική προσκύνηση των εικόνων από τη λατρεία που ανήκει μόνο στον Θεό. Μνημονεύεται επίσης για προσωπική λιτότητα και φροντίδα των φτωχών.','25 February','25 Φεβρουαρίου','https://www.oca.org/saints/lives?q=Tarasius'),
('john-merciful','Saint John the Merciful of Alexandria','Άγιος Ιωάννης ο Ελεήμων','Patriarch of Alexandria','Πατριάρχης Αλεξανδρείας','John, Patriarch of Alexandria in the early seventh century, became famous for treating the poor as the “masters” of his household and for organizing systematic almsgiving. His episcopate unfolded amid war and displacement in the eastern Mediterranean. Hagiographic sources remember his extraordinary generosity, personal simplicity, concern for justice, and refusal to separate worship from care for people in need.','Ο Ιωάννης, Πατριάρχης Αλεξανδρείας στις αρχές του 7ου αιώνα, έγινε γνωστός επειδή θεωρούσε τους φτωχούς «κυρίους» του οίκου του και οργάνωσε συστηματική ελεημοσύνη. Η πατριαρχία του συνέπεσε με πολέμους και μετακινήσεις πληθυσμών στην ανατολική Μεσόγειο. Οι βιογραφικές πηγές θυμούνται την εξαιρετική γενναιοδωρία, την προσωπική απλότητα, το ενδιαφέρον για δικαιοσύνη και την άρνησή του να χωρίσει τη λατρεία από τη φροντίδα των αναγκεμένων.','12 November','12 Νοεμβρίου','https://www.oca.org/saints/lives?q=John%20the%20Merciful'),
('eulogius-alexandria','Saint Eulogius of Alexandria','Άγιος Ευλόγιος Αλεξανδρείας','Patriarch and theologian','Πατριάρχης και θεολόγος','Eulogius served as Patriarch of Alexandria at the turn of the seventh century. He was a theological ally and correspondent of Saint Gregory the Great of Rome and wrote against Christological errors then dividing Christians in the eastern Mediterranean. Much of his writing survives only in fragments or summaries, so his importance is clearer than the details of his personal biography.','Ο Ευλόγιος υπηρέτησε ως Πατριάρχης Αλεξανδρείας στα τέλη του 6ου και τις αρχές του 7ου αιώνα. Ήταν θεολογικός σύμμαχος και αλληλογράφος του Αγίου Γρηγορίου του Μεγάλου της Ρώμης και έγραψε κατά χριστολογικών πλανών που δίχαζαν τους χριστιανούς. Μεγάλο μέρος του έργου του σώζεται μόνο σε αποσπάσματα ή περιλήψεις, γι’ αυτό η σημασία του είναι σαφέστερη από τις λεπτομέρειες της προσωπικής του ζωής.','13 February','13 Φεβρουαρίου','https://www.oca.org/saints/lives?q=Eulogius%20Alexandria'),
('macrina-elder','Saint Macrina the Elder','Αγία Μακρίνα η Πρεσβυτέρα','Confessor and grandmother of the Cappadocian saints','Ομολογήτρια και γιαγιά των Καππαδοκών Αγίων','Macrina the Elder lived through the persecutions of the early fourth century and, according to family memory preserved by Saint Basil the Great, suffered exile and hardship with her husband. She transmitted the faith she had received from the disciples of Saint Gregory Thaumaturgus to her descendants, helping form the remarkable Christian family that included Basil, Gregory of Nyssa, Macrina the Younger, Peter of Sebaste, and others.','Η Μακρίνα η Πρεσβυτέρα έζησε τους διωγμούς των αρχών του 4ου αιώνα και, σύμφωνα με την οικογενειακή μνήμη που διασώζει ο Μέγας Βασίλειος, υπέστη εξορία και στερήσεις μαζί με τον σύζυγό της. Μετέδωσε στους απογόνους της την πίστη που είχε παραλάβει από μαθητές του Αγίου Γρηγορίου του Θαυματουργού, συμβάλλοντας στη διαμόρφωση της οικογένειας που ανέδειξε τον Βασίλειο, τον Γρηγόριο Νύσσης, τη Μακρίνα τη Νεότερη, τον Πέτρο Σεβαστείας και άλλους.','14 January in many calendars','14 Ιανουαρίου σε πολλά ημερολόγια','https://www.oca.org/saints/lives?q=Macrina%20the%20Elder'),
('emmelia','Saint Emmelia','Αγία Εμμέλεια','Mother of Saints Basil and Gregory of Nyssa','Μητέρα του Μεγάλου Βασιλείου και του Γρηγορίου Νύσσης','Emmelia, wife of Basil the Elder, belonged to the great Christian family of Cappadocia. She raised a large household in faith; among her children were Saint Macrina the Younger, Saint Basil the Great, Saint Gregory of Nyssa, Saint Peter of Sebaste, and Naucratius. After her husband’s death, she joined Macrina in a life of prayer and community on the family estate in Pontus.','Η Εμμέλεια, σύζυγος του Βασιλείου του Πρεσβυτέρου, ανήκε στη μεγάλη χριστιανική οικογένεια της Καππαδοκίας. Ανέθρεψε πολυμελή οικογένεια στην πίστη· ανάμεσα στα παιδιά της ήταν η Αγία Μακρίνα η Νεότερη, ο Μέγας Βασίλειος, ο Άγιος Γρηγόριος Νύσσης, ο Άγιος Πέτρος Σεβαστείας και ο Ναυκράτιος. Μετά τον θάνατο του συζύγου της ενώθηκε με τη Μακρίνα σε ζωή προσευχής και κοινοβιακής άσκησης στον Πόντο.','30 May in several Orthodox calendars','30 Μαΐου σε αρκετά ορθόδοξα ημερολόγια','https://www.oca.org/saints/lives?q=Emmelia'),
('caesarius-nazianzus','Saint Caesarius of Nazianzus','Άγιος Καισάριος Ναζιανζηνός','Physician and brother of Saint Gregory the Theologian','Ιατρός και αδελφός του Αγίου Γρηγορίου του Θεολόγου','Caesarius, son of Saints Gregory the Elder and Nonna and brother of Gregory the Theologian and Gorgonia, was highly educated and became a physician at the imperial court. He survived political and religious pressures under Julian and later escaped a devastating earthquake at Nicaea, an event that moved him toward a more explicitly ascetical Christian life. He died young, leaving his wealth to the poor.','Ο Καισάριος, γιος των Αγίων Γρηγορίου του Πρεσβυτέρου και Νόννας και αδελφός του Γρηγορίου του Θεολόγου και της Γοργονίας, έλαβε υψηλή μόρφωση και έγινε ιατρός στην αυτοκρατορική αυλή. Αντιμετώπισε πολιτικές και θρησκευτικές πιέσεις επί Ιουλιανού και αργότερα επέζησε από καταστροφικό σεισμό στη Νίκαια, γεγονός που τον ώθησε σε πιο συνειδητή ασκητική χριστιανική ζωή. Πέθανε νέος, αφήνοντας την περιουσία του στους φτωχούς.','9 March','9 Μαρτίου','https://www.oca.org/saints/lives?q=Caesarius%20Nazianzus'),
('amphilochius-iconium','Saint Amphilochius of Iconium','Άγιος Αμφιλόχιος Ικονίου','Bishop and Cappadocian Father','Επίσκοπος και Καππαδόκης Πατέρας','Amphilochius, a relative and friend of the Cappadocian Fathers, left legal work for ascetic life and was made bishop of Iconium in the 370s. He defended Nicene faith, worked with Basil the Great and Gregory the Theologian, addressed questions about the divinity of the Holy Spirit and the canon of Scripture, and participated in the struggle against several fourth-century heresies.','Ο Αμφιλόχιος, συγγενής και φίλος των Καππαδοκών Πατέρων, εγκατέλειψε τη νομική σταδιοδρομία για την άσκηση και έγινε επίσκοπος Ικονίου τη δεκαετία του 370. Υπερασπίστηκε την πίστη της Νίκαιας, συνεργάστηκε με τον Μέγα Βασίλειο και τον Γρηγόριο τον Θεολόγο, ασχολήθηκε με τη θεότητα του Αγίου Πνεύματος και τον κανόνα της Γραφής και συμμετείχε στον αγώνα κατά αιρέσεων του 4ου αιώνα.','23 November','23 Νοεμβρίου','https://www.oca.org/saints/lives?q=Amphilochius%20Iconium'),
('willibrord','Saint Willibrord of Utrecht','Άγιος Βιλλιβρόρδος Ουτρέχτης','Missionary bishop and apostle of the Frisians','Ιεραπόστολος επίσκοπος και απόστολος των Φρισίων','Born in Northumbria around 658, Willibrord was formed in monastic life in England and Ireland before joining the mission to the Frisians. He was consecrated bishop in Rome and established his see at Utrecht, while the monastery of Echternach became a center of his work. His mission unfolded amid unstable politics and repeated setbacks, but he continued preaching and organizing Christian communities until his repose in 739.','Γεννημένος στη Νορθουμβρία περίπου το 658, ο Βιλλιβρόρδος διαμορφώθηκε μοναχικά στην Αγγλία και την Ιρλανδία πριν συμμετάσχει στην ιεραποστολή προς τους Φρίσιους. Χειροτονήθηκε επίσκοπος στη Ρώμη και εγκατέστησε την έδρα του στην Ουτρέχτη, ενώ η μονή Έχτερναχ έγινε κέντρο του έργου του. Η ιεραποστολή του αντιμετώπισε πολιτική αστάθεια και επανειλημμένες ανατροπές, αλλά συνέχισε το κήρυγμα και την οργάνωση χριστιανικών κοινοτήτων έως την κοίμησή του το 739.','7 November','7 Νοεμβρίου','https://www.oca.org/saints/lives?q=Willibrord'),
('etheldreda-ely','Saint Etheldreda of Ely','Αγία Εθελδρέδα του Έλυ','Abbess and monastic founder','Ηγουμένη και ιδρύτρια μονής','Etheldreda (Æthelthryth), an East Anglian princess of the seventh century, eventually left royal life to embrace monasticism. She founded a double monastery at Ely and became its abbess. Bede records her reputation for ascetic discipline and the later veneration of her relics. She became one of the most beloved female saints of medieval England and is honored in Orthodox calendars as a pre-schism Western saint.','Η Εθελδρέδα (Æthelthryth), πριγκίπισσα της Ανατολικής Αγγλίας τον 7ο αιώνα, εγκατέλειψε τελικά τη βασιλική ζωή για τον μοναχισμό. Ίδρυσε διπλή μονή στο Έλυ και έγινε ηγουμένη της. Ο Βέδας καταγράφει τη φήμη της για ασκητική πειθαρχία και τη μεταγενέστερη τιμή των λειψάνων της. Έγινε μία από τις πιο αγαπητές γυναίκες αγίες της μεσαιωνικής Αγγλίας και τιμάται ορθόδοξα ως προ του Σχίσματος αγία της Δύσης.','23 June','23 Ιουνίου','https://www.oca.org/saints/lives?q=Etheldreda'),
('edmund-martyr','Saint Edmund the Martyr','Άγιος Έντμουντ ο Μάρτυρας','King and martyr of East Anglia','Βασιλιάς και μάρτυρας της Ανατολικής Αγγλίας','Edmund was king of East Anglia in the ninth century and died during the Viking invasions, traditionally in 869. Early medieval tradition remembers him as a Christian ruler who refused to renounce Christ and was killed after capture. His shrine at Bury St Edmunds became one of England’s major pilgrimage centers. Details of his martyrdom are partly hagiographic, but the cult itself is ancient and well attested.','Ο Έντμουντ ήταν βασιλιάς της Ανατολικής Αγγλίας τον 9ο αιώνα και πέθανε κατά τις επιδρομές των Βίκινγκ, κατά την παράδοση το 869. Η πρώιμη μεσαιωνική παράδοση τον θυμάται ως χριστιανό άρχοντα που αρνήθηκε να αποκηρύξει τον Χριστό και θανατώθηκε μετά τη σύλληψή του. Το προσκύνημά του στο Bury St Edmunds έγινε ένα από τα σημαντικότερα της Αγγλίας. Οι λεπτομέρειες του μαρτυρίου είναι εν μέρει αγιολογικές, αλλά η αρχαία τιμή του είναι καλά τεκμηριωμένη.','20 November','20 Νοεμβρίου','https://www.oca.org/saints/lives?q=Edmund%20Martyr'),
('edward-martyr','Saint Edward the Martyr','Άγιος Εδουάρδος ο Μάρτυρας','King and passion-bearer','Βασιλιάς και πασιοφόρος','Edward became king of England as a young man in 975 and was murdered at Corfe in 978 during a succession struggle. Medieval Christian memory regarded his violent death and subsequent cult as the witness of an innocent ruler rather than a martyr killed explicitly for refusing apostasy. His relics were translated to Shaftesbury, where his veneration became widespread.','Ο Εδουάρδος έγινε βασιλιάς της Αγγλίας σε νεαρή ηλικία το 975 και δολοφονήθηκε στο Corfe το 978 κατά τη διάρκεια διαμάχης διαδοχής. Η μεσαιωνική χριστιανική μνήμη αντιμετώπισε τον βίαιο θάνατο και την επακόλουθη τιμή του ως μαρτυρία αθώου άρχοντα, όχι ως μαρτύριο εξαιτίας άρνησης αποστασίας. Τα λείψανά του μεταφέρθηκαν στο Shaftesbury, όπου η τιμή του διαδόθηκε ευρύτατα.','18 March','18 Μαρτίου','https://www.oca.org/saints/lives?q=Edward%20the%20Martyr'),
('rupert-salzburg','Saint Rupert of Salzburg','Άγιος Ρούπερτ Σάλτσμπουργκ','Missionary bishop','Ιεραπόστολος επίσκοπος','Rupert, active around the turn of the eighth century, was a Frankish bishop invited into Bavaria. He founded or renewed Christian centers around Salzburg, including the monastery of Saint Peter and a women’s community associated with Saint Erentrudis. His work helped establish durable ecclesiastical life in the region, and Salzburg later regarded him as its principal patron.','Ο Ρούπερτ, που έδρασε στα τέλη του 7ου και τις αρχές του 8ου αιώνα, ήταν Φράγκος επίσκοπος που προσκλήθηκε στη Βαυαρία. Ίδρυσε ή ανανέωσε χριστιανικά κέντρα γύρω από το Σάλτσμπουργκ, μεταξύ αυτών τη μονή του Αγίου Πέτρου και γυναικεία κοινότητα συνδεδεμένη με την Αγία Ερεντρούδη. Το έργο του εδραίωσε την εκκλησιαστική ζωή στην περιοχή και το Σάλτσμπουργκ τον τίμησε ως κύριο προστάτη του.','27 March','27 Μαρτίου','https://www.oca.org/saints/lives?q=Rupert%20Salzburg'),
('walburga','Saint Walburga','Αγία Βαλβούργα','Abbess and missionary monastic','Ηγουμένη και ιεραπόστολος μοναχή','Walburga was born in Anglo-Saxon England, related to the missionary saints Willibald and Winibald. She crossed to the continent and became abbess of the double monastery at Heidenheim, taking part in the Anglo-Saxon monastic mission among the German peoples. Her relics at Eichstätt became a long-standing place of pilgrimage.','Η Βαλβούργα γεννήθηκε στην αγγλοσαξονική Αγγλία και ήταν συγγενής των ιεραποστόλων αγίων Βιλλιβάλδου και Βινιβάλδου. Πέρασε στην ηπειρωτική Ευρώπη και έγινε ηγουμένη του διπλού μοναστηριού στο Heidenheim, συμμετέχοντας στην αγγλοσαξονική μοναστική ιεραποστολή στους γερμανικούς λαούς. Τα λείψανά της στο Eichstätt έγιναν διαχρονικό προσκύνημα.','25 February','25 Φεβρουαρίου','https://www.oca.org/saints/lives?q=Walburga'),
('olga-alaska','Saint Olga of Alaska','Αγία Όλγα της Αλάσκας','Matushka, midwife and servant of the Yup’ik people','Πρεσβυτέρα, μαία και διακόνισσα του λαού Yup’ik','Olga Michael of Kwethluk, Alaska (1916–1979), was a Yup’ik Orthodox Christian, wife of the priest Michael Michael, mother of a large family, and a midwife who served women and families with practical generosity and quiet faith. Local devotion to her grew after her repose, especially among people seeking healing from trauma and abuse. The Orthodox Church in America formally glorified her, making her one of the first canonized female Orthodox saints of North America.','Η Όλγα Μάικλ του Kwethluk στην Αλάσκα (1916–1979) ήταν Yup’ik Ορθόδοξη Χριστιανή, σύζυγος του ιερέα Μιχαήλ Μάικλ, μητέρα πολυμελούς οικογένειας και μαία που υπηρετούσε γυναίκες και οικογένειες με πρακτική γενναιοδωρία και ήσυχη πίστη. Η τοπική τιμή της αυξήθηκε μετά την κοίμησή της, ιδιαίτερα ανάμεσα σε ανθρώπους που αναζητούν ίαση από τραύμα και κακοποίηση. Η Ορθόδοξη Εκκλησία στην Αμερική την κατέταξε επίσημα στο αγιολόγιο.','10 November in the OCA','10 Νοεμβρίου στην OCA','https://www.oca.org/saints/lives?q=Olga%20Alaska'),
('ephraim-katunakia','Saint Ephraim of Katounakia','Άγιος Εφραίμ Κατουνακιώτης','Athonite elder and hesychast','Αγιορείτης γέροντας και ησυχαστής','Ephraim (1912–1998) lived for decades in the desert of Katounakia on Mount Athos. Formed in strict obedience and the Jesus Prayer, he became associated spiritually with Saint Joseph the Hesychast and later guided many monks and laypeople. Accounts of his life emphasize obedience, repentance, inner prayer, discernment, and compassion born from long ascetic struggle.','Ο Εφραίμ (1912–1998) έζησε για δεκαετίες στην έρημο των Κατουνακίων του Αγίου Όρους. Διαμορφώθηκε μέσα σε αυστηρή υπακοή και την ευχή του Ιησού, συνδέθηκε πνευματικά με τον Άγιο Ιωσήφ τον Ησυχαστή και αργότερα καθοδήγησε πολλούς μοναχούς και λαϊκούς. Οι διηγήσεις της ζωής του τονίζουν την υπακοή, τη μετάνοια, την εσωτερική προσευχή, τη διάκριση και τη συμπόνια που γεννήθηκε από μακρόχρονο ασκητικό αγώνα.','27 February','27 Φεβρουαρίου','https://www.oca.org/saints/lives?q=Ephraim%20Katounakia'),
('nikon-optina','Venerable Nikon of Optina','Όσιος Νίκων της Όπτινα','Last major Optina elder before the Soviet suppression','Ένας από τους τελευταίους μεγάλους γέροντες της Όπτινα πριν τη σοβιετική καταστολή','Nikon Belyaev entered Optina as a young man and became a disciple of Elder Barsanuphius. After the Russian Revolution and closure of the monastery he continued pastoral and spiritual work under persecution, was arrested, imprisoned, and exiled. Suffering from tuberculosis, he endured his final years with prayer and pastoral correspondence and reposed in exile in 1931.','Ο Νίκων Μπελιάεφ εισήλθε νέος στην Όπτινα και έγινε μαθητής του Γέροντα Βαρσανουφίου. Μετά τη Ρωσική Επανάσταση και το κλείσιμο της μονής συνέχισε το ποιμαντικό και πνευματικό έργο μέσα σε διωγμό, συνελήφθη, φυλακίστηκε και εξορίστηκε. Πάσχοντας από φυματίωση, έζησε τα τελευταία χρόνια με προσευχή και ποιμαντική αλληλογραφία και εκοιμήθη στην εξορία το 1931.','25 June','25 Ιουνίου','https://www.oca.org/saints/all-lives/4462/06/25'),
('dimitri-rostov','Saint Dimitri of Rostov','Άγιος Δημήτριος Ροστώφ','Metropolitan, preacher and hagiographer','Μητροπολίτης, ιεροκήρυκας και αγιογράφος','Dimitri Tuptalo (1651–1709) became one of the great preachers and church writers of the Ukrainian and Russian Orthodox world. His monumental collection of saints’ lives synthesized a wide range of sources for daily reading. As Metropolitan of Rostov he promoted clerical education, preached against superstition and sectarianism, wrote theological and devotional works, and lived with notable personal simplicity.','Ο Δημήτριος Τούπταλο (1651–1709) έγινε ένας από τους μεγάλους ιεροκήρυκες και εκκλησιαστικούς συγγραφείς του ουκρανικού και ρωσικού ορθόδοξου κόσμου. Η μνημειώδης συλλογή Βίων Αγίων συνέθεσε πολυάριθμες πηγές για καθημερινή ανάγνωση. Ως Μητροπολίτης Ροστώφ προώθησε την εκπαίδευση του κλήρου, κήρυξε κατά δεισιδαιμονιών και αιρέσεων, έγραψε θεολογικά και ευσεβή έργα και έζησε με προσωπική απλότητα.','28 October','28 Οκτωβρίου','https://www.oca.org/saints/lives?q=Dimitri%20Rostov'),
('nectarius-optina','Venerable Nectarius of Optina','Όσιος Νεκτάριος της Όπτινα','Optina elder and confessor','Γέροντας και ομολογητής της Όπτινα','Nectarius Tikhonov became an Optina monk and spiritual child within the monastery’s eldership tradition. Known for humility, prayer, humor, and unusual insight into people, he became one of Optina’s last elders before the monastery was closed after the Revolution. He was arrested and later lived outside the monastery while continuing to receive spiritual children until his repose in 1928.','Ο Νεκτάριος Τιχόνοφ έγινε μοναχός της Όπτινα και πνευματικό τέκνο της παράδοσης των γερόντων της μονής. Γνωστός για ταπείνωση, προσευχή, χιούμορ και βαθιά γνώση των ανθρώπων, έγινε ένας από τους τελευταίους γέροντες πριν το κλείσιμο της μονής μετά την Επανάσταση. Συνελήφθη και αργότερα έζησε εκτός μονής, συνεχίζοντας να δέχεται πνευματικά τέκνα έως την κοίμησή του το 1928.','29 April','29 Απριλίου','https://www.oca.org/saints/lives?q=Nectarius%20Optina'),
('barsanuphius-optina','Venerable Barsanuphius of Optina','Όσιος Βαρσανούφιος της Όπτινα','Optina elder','Γέροντας της Όπτινα','Born Paul Plikhankov in 1845, Barsanuphius had a military career before entering Optina in middle age. He became a disciple in the monastery’s spiritual tradition and eventually served as elder, confessor, and skete superior. He ministered during the Russo-Japanese War and later guided many pilgrims. His final years included administrative conflict and transfer away from Optina; he reposed in 1913.','Γεννημένος ως Παύλος Πλιχάνκοφ το 1845, ο Βαρσανούφιος ακολούθησε στρατιωτική σταδιοδρομία πριν εισέλθει στην Όπτινα σε ώριμη ηλικία. Έγινε μαθητής της πνευματικής παράδοσης της μονής και τελικά γέροντας, εξομολόγος και προϊστάμενος σκήτης. Διακόνησε κατά τον Ρωσοϊαπωνικό Πόλεμο και καθοδήγησε πολλούς προσκυνητές. Τα τελευταία χρόνια του περιλάμβαναν διοικητικές δυσκολίες και μετάθεση από την Όπτινα· εκοιμήθη το 1913.','1 April','1 Απριλίου','https://www.oca.org/saints/lives?q=Barsanuphius%20Optina'),
('dimitri-basarabov','Saint Dimitri of Basarabov','Άγιος Δημήτριος Μπασαράμπωφ','Venerable hermit and protector of Bucharest','Όσιος ερημίτης και προστάτης του Βουκουρεστίου','Dimitri lived an ascetic life near the village of Basarabov south of the Danube, probably in the later medieval period. Tradition remembers him as a humble shepherd or villager who withdrew to a cave monastery and died in obscurity. His relics were later discovered and became renowned locally; in the eighteenth century they were transferred to Bucharest, where he is honored as a protector of the city.','Ο Δημήτριος έζησε ασκητικά κοντά στο χωριό Μπασαράμπωφ νότια του Δούναβη, πιθανότατα στους ύστερους μεσαιωνικούς χρόνους. Η παράδοση τον θυμάται ως ταπεινό βοσκό ή χωρικό που αποσύρθηκε σε σπηλαιώδη μονή και πέθανε αφανής. Τα λείψανά του ανακαλύφθηκαν αργότερα και απέκτησαν μεγάλη τοπική τιμή· τον 18ο αιώνα μεταφέρθηκαν στο Βουκουρέστι, όπου τιμάται ως προστάτης της πόλης.','27 October','27 Οκτωβρίου','https://www.oca.org/saints/lives?q=Dimitri%20Basarabov'),
('david-gareja','Saint David of Gareja','Άγιος Δαβίδ του Γκαρέτζα','Georgian monastic founder','Γεωργιανός μοναστικός ιδρυτής','David is remembered among the Thirteen Syrian Fathers who helped renew monastic and missionary life in sixth-century Georgia. He settled first near Tbilisi and later in the semi-desert of Gareja, where a major monastic center grew around his ascetic community. His Life combines historical memory with miracle traditions, including stories of pilgrimage to Jerusalem and the sanctity associated with the Gareja wilderness.','Ο Δαβίδ μνημονεύεται μεταξύ των Δεκατριών Σύρων Πατέρων που ανανέωσαν τη μοναστική και ιεραποστολική ζωή στη Γεωργία τον 6ο αιώνα. Εγκαταστάθηκε αρχικά κοντά στην Τιφλίδα και αργότερα στην ημιέρημο του Γκαρέτζα, όπου αναπτύχθηκε μεγάλο μοναστικό κέντρο γύρω από την ασκητική κοινότητά του. Ο Βίος του συνδυάζει ιστορική μνήμη με θαυματουργικές παραδόσεις, μεταξύ αυτών διηγήσεις για προσκύνημα στα Ιεροσόλυμα.','Thursday after the Ascension; local Georgian calendar','Πέμπτη μετά την Ανάληψη· σύμφωνα με το γεωργιανό ημερολόγιο','https://www.oca.org/saints/lives?q=David%20of%20Gareja'),
('euthymius-takaishvili','Saint Euthymius Takaishvili','Άγιος Ευθύμιος Τακαϊσβίλι','Scholar and guardian of Georgian cultural treasures','Λόγιος και φύλακας των γεωργιανών πολιτιστικών θησαυρών','Ekvtime Takaishvili (1863–1953) was a Georgian historian, archaeologist, teacher, and public servant. After the upheavals surrounding Georgian independence and Soviet takeover, he accompanied national treasures into exile in France and guarded them for decades despite poverty and pressure to sell them. He eventually returned the collection intact to Georgia. The Georgian Church glorified him as “the Man of God.”','Ο Εκβτίμε Τακαϊσβίλι (1863–1953) ήταν Γεωργιανός ιστορικός, αρχαιολόγος, εκπαιδευτικός και δημόσιος λειτουργός. Μετά τις αναταραχές της γεωργιανής ανεξαρτησίας και της σοβιετικής κατάληψης συνόδευσε τους εθνικούς θησαυρούς στην εξορία στη Γαλλία και τους φύλαξε επί δεκαετίες παρά τη φτώχεια και τις πιέσεις να τους πουλήσει. Τελικά επέστρεψε ολόκληρη τη συλλογή στη Γεωργία. Η Γεωργιανή Εκκλησία τον αγιοκατέταξε ως «Άνθρωπο του Θεού».','3 January','3 Ιανουαρίου','https://www.oca.org/saints/lives/2021/01/03'),
]
for r in rows:
    E.append(saint(*r))

# Only add truly new IDs.
E=[e for e in E if e['id'] not in base_ids]
(DATA/'v7-expansion.js').write_text('window.ORTHODOX_V7_EXPANSION = '+json.dumps(E,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')

# Update catalog loader to include V7.
cat=(DATA/'catalog.js').read_text(encoding='utf-8')
if 'ORTHODOX_V7_EXPANSION' not in cat:
    cat=cat.replace('  ...(window.ORTHODOX_COMPREHENSIVE_EXPANSION || [])','  ...(window.ORTHODOX_COMPREHENSIVE_EXPANSION || []),\n  ...(window.ORTHODOX_V7_EXPANSION || [])')
    (DATA/'catalog.js').write_text(cat,encoding='utf-8')

# Dignified, unmistakably-generic LOCAL fallback art: no cartoon faces and no fake icon claim.
def initials(name):
    parts=re.findall(r"[A-Za-zΑ-ΩΆΈΉΊΌΎΏΪΫα-ωάέήίόύώϊϋΐΰ]+",name)
    if not parts:return '☦'
    return ''.join(p[0].upper() for p in parts[:2])

def fallback_svg(e):
    name=e['name']['en']; ini=html.escape(initials(name)); cat=e['category']
    palette={'christ':('#5b2b83','#ffd967'),'theotokos':('#245fa7','#ffe39a'),'angel':('#257d9a','#f4f5ff'),'forefather':('#79502f','#ffe3a0'),'righteous':('#2e7758','#ffe1a0'),'prophet':('#60408f','#ffdf8a'),'apostle':('#7e3568','#ffe092'),'nt-saint':('#2b7c72','#ffe39a'),'church-saint':('#81422f','#ffe299'),'feast':('#76552a','#fff0a8'),'biblical-context':('#424861','#d9dfef')}
    bg,gold=palette.get(cat,('#3b4564','#f4d989'))
    # Purely symbolic silhouette + halo. This is deliberately a fallback, not claimed as a historical portrait/icon.
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240" role="img" aria-label="Local fallback artwork for {html.escape(name)}">
<defs><radialGradient id="b" cx="38%" cy="25%"><stop stop-color="#fff" stop-opacity=".18"/><stop offset="1" stop-color="{bg}"/></radialGradient></defs>
<rect width="240" height="240" rx="32" fill="url(#b)"/>
<circle cx="120" cy="82" r="55" fill="none" stroke="{gold}" stroke-width="8" opacity=".92"/>
<circle cx="120" cy="91" r="31" fill="#15182a"/>
<path d="M55 219c5-58 31-91 65-91s60 33 65 91" fill="#15182a"/>
<path d="M79 155l41 28 41-28" fill="none" stroke="{gold}" stroke-width="4" opacity=".7"/>
<text x="120" y="28" text-anchor="middle" font-family="Georgia,serif" font-size="24" fill="{gold}">☦</text>
<text x="120" y="211" text-anchor="middle" font-family="system-ui,sans-serif" font-size="25" font-weight="800" fill="#fff">{ini}</text>
</svg>'''

all_entries=base+E
for e in all_entries:
    p=ROOT/e['image']; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(fallback_svg(e),encoding='utf-8')

stats=Counter(e['category'] for e in all_entries)
(DATA/'catalog-stats.json').write_text(json.dumps({'total':len(all_entries),'categories':dict(sorted(stats.items()))},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(f'Base {len(base)} + new {len(E)} = {len(all_entries)}')
print(dict(sorted(stats.items())))
