#!/usr/bin/env python3
from pathlib import Path
import json

ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'web/data/v24-expansion.js'

entries=[]

def pair(en,el): return {'en':en,'el':el}

def saint(id,en,el,role_en,role_el,feast_en,feast_el,story_en,story_el,source_url,aliases=None,metadata=None,notes_en='',notes_el=''):
    md=metadata or {}
    e={
      'id':id,'name':pair(en,el),'category':'church-saint','role':pair(role_en,role_el),
      'story':pair(story_en,story_el),'feast':pair(feast_en,feast_el),'scripture':'Church tradition / Lives of the Saints',
      'prayer':pair(f'{en}, pray to God for us, that we may grow in repentance, courage, mercy, humility, and faithfulness.',
                    f'{el}, πρέσβευε στον Θεό για μας, ώστε να αυξανόμαστε σε μετάνοια, θάρρος, έλεος, ταπείνωση και πιστότητα.'),
      'notes':pair(notes_en or 'This profile summarizes the cited Orthodox source and distinguishes hagiographic tradition from strictly datable historical evidence.',
                   notes_el or 'Το προφίλ συνοψίζει την παρατιθέμενη ορθόδοξη πηγή και διακρίνει την αγιολογική παράδοση από τα αυστηρά χρονολογήσιμα ιστορικά δεδομένα.'),
      'aliases':aliases or [],'venerated':True,'image':f'web/images/catalog/{id}.svg','sourceUrl':source_url,
      'metadata':md,
      'search':' '.join([en,el,role_en,role_el,feast_en,feast_el,*[str(x) for x in md.values() if isinstance(x,str)]])
    }
    e['knowledge']={
      'en':{'sections':[
        {'title':'Life and setting','text':story_en},
        {'title':'Why this saint is remembered','text':md.get('significance_en', f'Orthodox memory preserves {en} as a witness to repentance, endurance, prayer, and faithfulness to Christ.')},
        {'title':'Searchable themes and associations','text':'; '.join(md.get('themes_en',[])) or role_en},
        {'title':'Source note','text':'The linked Orthodox Church in America life is the primary web source used for this expansion entry. Hagiographic miracle narratives are preserved as tradition rather than silently converted into modern historical claims.'}
      ],'sources':[{'label':pair('Orthodox Church in America — Life of the Saint','Ορθόδοξη Εκκλησία στην Αμερική — Βίος του Αγίου'),'url':source_url}]},
      'el':{'sections':[
        {'title':'Βίος και πλαίσιο','text':story_el},
        {'title':'Γιατί μνημονεύεται','text':md.get('significance_el', f'Η ορθόδοξη μνήμη διαφυλάσσει τον/την {el} ως μαρτυρία μετανοίας, υπομονής, προσευχής και πιστότητας στον Χριστό.')},
        {'title':'Θέματα και συσχετισμοί αναζήτησης','text':'; '.join(md.get('themes_el',[])) or role_el},
        {'title':'Σημείωση πηγής','text':'Ο συνδεδεμένος Βίος Αγίων της Ορθόδοξης Εκκλησίας στην Αμερική (OCA) είναι η κύρια διαδικτυακή πηγή αυτής της νέας καταχώρισης. Οι θαυματουργικές αγιολογικές διηγήσεις διατηρούνται ως παράδοση και δεν παρουσιάζονται ως σύγχρονη ιστοριογραφική απόδειξη.'}
      ],'sources':[{'label':pair('Orthodox Church in America — Life of the Saint','Ορθόδοξη Εκκλησία στην Αμερική — Βίος του Αγίου'),'url':source_url}]}
    }
    entries.append(e)

# Less-known saints, with direct Orthodox source pages.
saint('mamas-caesarea','Martyr Mamas of Caesarea','Άγιος Μάμας Καισαρείας','Third-century martyr of Cappadocia','Μάρτυρας του 3ου αιώνα στην Καππαδοκία','2 September','2 Σεπτεμβρίου',
      'Born after his Christian parents Theodotus and Rufina were imprisoned, Mamas was raised by the Christian Ammia. Orthodox hagiography remembers his youthful confession of Christ, his life among the mountains, and his martyrdom under persecution.',
      'Γεννημένος ενώ οι χριστιανοί γονείς του Θεόδοτος και Ρουφίνα ήταν φυλακισμένοι, ο Μάμας ανατράφηκε από τη χριστιανή Αμμία. Η ορθόδοξη αγιολογική παράδοση θυμάται τη νεανική ομολογία του Χριστού, την ασκητική ζωή του στα βουνά και το μαρτύριό του.',
      'https://www.oca.org/saints/lives/2026/09/02/102459-martyr-mamas-of-caesarea-in-cappadocia',
      aliases=['Saint Mamas','Mammes of Caesarea','Άγιος Μάμας'],
      metadata={'era':'3rd century','location':'Cappadocia / Asia Minor','themes_en':['youthful witness','martyrdom','orphaned child','shepherding imagery','care of creation'],'themes_el':['νεανική ομολογία','μαρτύριο','ορφανός','ποιμαντική εικόνα','φροντίδα της κτίσης'],'significance_en':'Mamas is especially remembered as a young martyr whose story joins confession of faith with imagery of shepherding and life among animals.','significance_el':'Ο Μάμας μνημονεύεται ιδιαίτερα ως νεαρός μάρτυρας, με διήγηση που συνδέει την ομολογία της πίστης με την ποιμαντική ζωή και την κτίση.'})

saint('gerasimus-jordan','Venerable Gerasimus of the Jordan','Όσιος Γεράσιμος του Ιορδάνου','Desert monastic founder of the Jordan','Ερημίτης και ιδρυτής μονής στον Ιορδάνη','4 March','4 Μαρτίου',
      'Gerasimus, originally from Lycia, embraced monastic life, lived in the Egyptian desert, and around the mid-fifth century settled near the Jordan where he founded a monastery with a strict rule. His life also preserves the famous tradition of a lion that served him after the saint helped it, which explains the lion shown on many icons of him.',
      'Ο Γεράσιμος, καταγόμενος από τη Λυκία, ακολούθησε τη μοναχική ζωή, ασκήτεψε στην αιγυπτιακή έρημο και στα μέσα του 5ου αιώνα εγκαταστάθηκε κοντά στον Ιορδάνη όπου ίδρυσε μονή με αυστηρό κανόνα. Ο βίος του διασώζει επίσης τη γνωστή παράδοση του λιονταριού που τον υπηρετούσε αφού ο άγιος το βοήθησε, γεγονός που εξηγεί το λιοντάρι σε πολλές εικόνες του.',
      'https://www.oca.org/saints/lives/2026/03/04/100649-venerable-gerasimus-of-the-jordan',aliases=['Gerasimos of the Jordan','Saint Gerasimus and the lion','Άγιος Γεράσιμος του Ιορδάνου'],
      metadata={'era':'5th century','location':'Jordan / Palestine','themes_en':['desert monasticism','lion','animals','compassion for creation','monastic rule','repentance from doctrinal error'],'themes_el':['ερημικός μοναχισμός','λιοντάρι','ζώα','συμπόνια για την κτίση','μοναστικός κανόνας','επιστροφή από δογματική πλάνη'],'significance_en':'The saint is strongly associated in Orthodox iconography and hagiography with a lion that served him, making him a useful search result for saints connected with animals and care for creation.','significance_el':'Ο άγιος συνδέεται έντονα στην ορθόδοξη εικονογραφία και αγιολογία με λιοντάρι που τον υπηρετούσε, γι’ αυτό είναι χρήσιμη καταχώριση σε αναζητήσεις για αγίους που σχετίζονται με ζώα και φροντίδα της κτίσης.'})

saint('pimen-great','Venerable Pimen the Great','Όσιος Ποιμήν ο Μέγας','Egyptian Desert Father','Αιγύπτιος Πατέρας της Ερήμου','27 August','27 Αυγούστου',
      'Born about 340 in Egypt, Pimen entered monastic life with his brothers and became one of the most frequently quoted Desert Fathers. His sayings emphasize humility, restraint in judging others, repentance, patience, and practical mercy.',
      'Γεννημένος περίπου το 340 στην Αίγυπτο, ο Ποιμήν ακολούθησε τη μοναχική ζωή μαζί με τους αδελφούς του και έγινε ένας από τους συχνότερα μνημονευόμενους Πατέρες της Ερήμου. Οι λόγοι του τονίζουν την ταπείνωση, την αποφυγή της κατάκρισης, τη μετάνοια, την υπομονή και το έλεος.',
      'https://www.oca.org/saints/lives/2026/08/27/102404-venerable-pimen-the-great',aliases=['Abba Poemen','Poemen the Great','Αββάς Ποιμήν'],
      metadata={'era':'4th–5th century','location':'Egypt / Scetis tradition','themes_en':['Desert Fathers','humility','repentance','non-judgment','discernment'],'themes_el':['Πατέρες της Ερήμου','ταπείνωση','μετάνοια','αποφυγή κατάκρισης','διάκριση']})

saint('paphnutius-jerusalem','Hieromartyr Paphnutius of Jerusalem','Ιερομάρτυρας Παφνούτιος Ιεροσολύμων','Bishop and martyr','Επίσκοπος και μάρτυρας','19 April','19 Απριλίου',
      'Paphnutius is remembered as a bishop who endured persecution, including torture by fire and exposure to wild beasts, and was finally put to death by the sword. The source also notes uncertainty about whether he was an Egyptian bishop exiled to Palestinian mines during the Diocletian persecution.',
      'Ο Παφνούτιος μνημονεύεται ως επίσκοπος που υπέμεινε διωγμό, βασανισμούς με φωτιά και έκθεση σε άγρια θηρία και τελικά θανατώθηκε με ξίφος. Η πηγή σημειώνει επίσης αβεβαιότητα ως προς το αν ήταν Αιγύπτιος επίσκοπος εξόριστος στα παλαιστινιακά μεταλλεία επί Διοκλητιανού.',
      'https://www.oca.org/saints/lives/2026/04/19/101150-hieromartyr-paphnutius-of-jerusalem',
      metadata={'era':'Diocletianic persecution','location':'Jerusalem / Egypt tradition','themes_en':['episcopal witness','martyrdom','persecution','historical uncertainty'],'themes_el':['επισκοπική μαρτυρία','μαρτύριο','διωγμός','ιστορική αβεβαιότητα']})

saint('agathon-egypt','Venerable Agathon of Egypt','Όσιος Αγάθων της Αιγύπτου','Desert Father and disciple of Abba Lot','Πατέρας της Ερήμου και μαθητής του Αββά Λωτ','2 March','2 Μαρτίου',
      'Agathon lived ascetically in the Egyptian desert and was renowned for meekness and discernment. A famous saying preserved in his life distinguishes humble acceptance of personal accusations from accepting the charge of heresy, which he rejected because it meant separation from God.',
      'Ο Αγάθων ασκήτεψε στην αιγυπτιακή έρημο και έγινε γνωστός για την πραότητα και τη διάκρισή του. Γνωστή διήγηση του βίου του διακρίνει την ταπεινή αποδοχή προσωπικών κατηγοριών από την κατηγορία της αίρεσης, την οποία αρνήθηκε επειδή σημαίνει χωρισμό από τον Θεό.',
      'https://www.oca.org/saints/lives/2026/03/02/100638-venerable-agathon-of-egypt',
      metadata={'era':'4th century','location':'Egyptian desert','themes_en':['meekness','discernment','humility','orthodoxy','Desert Fathers'],'themes_el':['πραότητα','διάκριση','ταπείνωση','ορθόδοξη πίστη','Πατέρες της Ερήμου']})

saint('theodora-alexandria','Venerable Theodora of Alexandria','Οσία Θεοδώρα της Αλεξανδρείας','Penitent ascetic','Μετανοούσα ασκήτρια','11 September','11 Σεπτεμβρίου',
      'Theodora is remembered in Orthodox hagiography as a married woman who fell into grave sin, repented deeply, and entered ascetic life disguised as a male monk under the name Theodore. Her story centers on repentance, hidden holiness, false accusation, patience, and forgiveness.',
      'Η Θεοδώρα μνημονεύεται στην ορθόδοξη αγιολογία ως έγγαμη γυναίκα που έπεσε σε βαρύ αμάρτημα, μετανόησε βαθιά και εισήλθε στην ασκητική ζωή με ανδρική ενδυμασία και το όνομα Θεόδωρος. Η διήγησή της επικεντρώνεται στη μετάνοια, την κρυφή αγιότητα, την άδικη κατηγορία, την υπομονή και τη συγχώρηση.',
      'https://www.oca.org/saints/lives/2026/09/11/102570-venerable-theodora-of-alexandria',
      metadata={'era':'late antiquity','location':'Alexandria / Egyptian monasticism','themes_en':['repentance','hidden holiness','false accusation','forgiveness','monasticism'],'themes_el':['μετάνοια','κρυφή αγιότητα','άδικη κατηγορία','συγχώρηση','μοναχισμός']})

saint('pelagia-penitent','Venerable Pelagia the Penitent','Οσία Πελαγία η Μετανοούσα','Penitent ascetic of Antioch','Μετανοούσα ασκήτρια της Αντιόχειας','8 October','8 Οκτωβρίου',
      'Pelagia is remembered as a woman of Antioch whose life changed after hearing Saint Nonnus preach. She received Baptism, renounced her former way of life and wealth, and embraced rigorous repentance and asceticism.',
      'Η Πελαγία μνημονεύεται ως γυναίκα της Αντιόχειας της οποίας η ζωή άλλαξε όταν άκουσε το κήρυγμα του Αγίου Νόννου. Βαπτίστηκε, απαρνήθηκε τον προηγούμενο τρόπο ζωής και τον πλούτο της και ακολούθησε αυστηρή μετάνοια και άσκηση.',
      'https://www.oca.org/saints/lives/2026/10/08/102899-venerable-pelagia-the-penitent',
      metadata={'era':'late antiquity','location':'Antioch / Jerusalem tradition','themes_en':['repentance','conversion','Baptism','renunciation','asceticism'],'themes_el':['μετάνοια','μεταστροφή','Βάπτισμα','αποταγή','άσκηση']})

saint('theodotus-rufina','Martyrs Theodotus and Rufina of Caesarea','Μάρτυρες Θεόδοτος και Ρουφίνα Καισαρείας','Christian parents and martyrs','Χριστιανοί γονείς και μάρτυρες','2 September','2 Σεπτεμβρίου',
      'Theodotus and Rufina, parents of Saint Mamas, were imprisoned for openly confessing Christianity. Theodotus died in prison; Rufina gave birth prematurely, entrusted her child to God, and also died after enduring imprisonment and grief.',
      'Ο Θεόδοτος και η Ρουφίνα, γονείς του Αγίου Μάμα, φυλακίστηκαν επειδή ομολόγησαν δημόσια τη χριστιανική πίστη. Ο Θεόδοτος πέθανε στη φυλακή· η Ρουφίνα γέννησε πρόωρα, εμπιστεύθηκε το παιδί της στον Θεό και επίσης εκοιμήθη έπειτα από τις στερήσεις και τη θλίψη.',
      'https://www.oca.org/saints/lives/2026/09/02/102460-martyrs-theodotus-and-rufina-of-caesarea-in-cappadocia',
      metadata={'era':'3rd century','location':'Caesarea in Cappadocia','themes_en':['Christian family','parents of Saint Mamas','confession','imprisonment','martyrdom'],'themes_el':['χριστιανική οικογένεια','γονείς Αγίου Μάμα','ομολογία','φυλάκιση','μαρτύριο']})

saint('pimen-faster-kiev','Venerable Pimen the Faster of the Kiev Caves','Όσιος Ποιμήν ο Νηστευτής των Σπηλαίων του Κιέβου','Abbot and ascetic of the Kiev Caves','Ηγούμενος και ασκητής των Σπηλαίων του Κιέβου','7 August; also 28 August','7 Αυγούστου· επίσης 28 Αυγούστου',
      'Pimen labored in the Far Caves of Kiev and was known for strict fasting joined to inward restraint of thoughts and actions. He served as abbot of the Kiev Caves monastery from 1132 to 1141.',
      'Ο Ποιμήν ασκήθηκε στα Μακρινά Σπήλαια του Κιέβου και έγινε γνωστός για την αυστηρή νηστεία που συνδεόταν με εσωτερική εγκράτεια λογισμών και πράξεων. Διετέλεσε ηγούμενος της μονής των Σπηλαίων του Κιέβου από το 1132 έως το 1141.',
      'https://www.oca.org/saints/lives/2026/08/07/102221-venerable-pimen-the-faster-of-the-kiev-caves',
      metadata={'era':'12th century','location':'Kiev Caves','themes_en':['fasting','inner watchfulness','abbot','Kiev Caves','monastic discipline'],'themes_el':['νηστεία','νήψη','ηγούμενος','Σπήλαια Κιέβου','μοναχική άσκηση']})

saint('eusebius-hermit-syria','Venerable Eusebius the Hermit of Syria','Όσιος Ευσέβιος ο Ερημίτης της Συρίας','Fourth-century Syrian hermit','Σύρος ερημίτης του 4ου αιώνα','15 February','15 Φεβρουαρίου',
      'Eusebius lived in the open air on a mountain near Asicha in Syria, enduring heat and cold with a highly austere diet. When visitors became numerous, he moved beside a monastery and remained in a small enclosure until his death at about ninety years of age.',
      'Ο Ευσέβιος έζησε υπαίθρια σε βουνό κοντά στην Ασίχα της Συρίας, υπομένοντας ζέστη και κρύο με πολύ αυστηρή διατροφή. Όταν οι επισκέπτες πλήθυναν, εγκαταστάθηκε δίπλα σε μονή και έζησε σε μικρό περίβολο μέχρι την κοίμησή του, περίπου σε ηλικία ενενήντα ετών.',
      'https://www.oca.org/saints/lives/2026/02/15/100530-venerable-eusebius-the-hermit-of-syria',
      metadata={'era':'4th–early 5th century','location':'Syria, near Asicha','themes_en':['hermit','extreme asceticism','endurance','simplicity','Syrian monasticism'],'themes_el':['ερημίτης','αυστηρή άσκηση','υπομονή','απλότητα','συριακός μοναχισμός']})

saint('dositheus-pskov','Venerable Dositheus of Verkhneostrov, Pskov','Όσιος Δοσίθεος του Βερχνεοστρόφ, Πσκοφ','Monastic founder and abbot','Μοναστικός ιδρυτής και ηγούμενος','8 October','8 Οκτωβρίου',
      'Dositheus was a disciple in the Pskov monastic tradition and in 1470 founded the Peter and Paul monastery on an island in Lake Pskov. The chronicles describe the islands as forested and dangerous before the monastic settlement; he reposed in 1482.',
      'Ο Δοσίθεος ανήκε στη μοναστική παράδοση του Πσκοφ και το 1470 ίδρυσε τη μονή των Αγίων Πέτρου και Παύλου σε νησί της λίμνης Πσκοφ. Τα χρονικά περιγράφουν τα νησιά ως δασώδη και επικίνδυνα πριν από τη μοναστική εγκατάσταση· εκοιμήθη το 1482.',
      'https://www.oca.org/saints/lives/2026/10/08/102900-venerable-dositheus-abbot-of-verkneostrov-pskov',
      metadata={'era':'15th century','location':'Lake Pskov','themes_en':['monastic founder','abbot','mission in remote places','Pskov saints'],'themes_el':['μοναστικός ιδρυτής','ηγούμενος','διακονία σε απομονωμένο τόπο','Άγιοι Πσκοφ']})

saint('peter-hermit-galatia','Venerable Peter the Hermit of Galatia','Όσιος Πέτρος ο Ερημίτης της Γαλατίας','Hermit and wonderworker','Ερημίτης και θαυματουργός','1 February; in Greek usage also 25 November','1 Φεβρουαρίου· στην ελληνική χρήση και 25 Νοεμβρίου',
      'Peter of Galatia, from the Black Sea region, pursued ascetic life in Galatia and Palestine and is described by Theodoret as a spiritual guide and wonderworker. His long life is associated with prayer, healing, resistance to violence, and pastoral counsel.',
      'Ο Πέτρος της Γαλατίας, από την περιοχή του Εύξεινου Πόντου, ακολούθησε ασκητική ζωή στη Γαλατία και την Παλαιστίνη και περιγράφεται από τον Θεοδώρητο ως πνευματικός οδηγός και θαυματουργός. Η μακρά ζωή του συνδέεται με προσευχή, θεραπείες, αντίσταση στη βία και πνευματική συμβουλή.',
      'https://www.oca.org/saints/lives/2026/02/01/100404-venerable-peter-the-hermit-of-galatia-near-antioch-in-syria',
      metadata={'era':'4th–5th century','location':'Galatia / Palestine / Syria','themes_en':['hermit','healing','pastoral counsel','Theodoret of Cyrrhus','long ascetic life'],'themes_el':['ερημίτης','θεραπεία','πνευματική συμβουλή','Θεοδώρητος Κύρου','μακρά ασκητική ζωή']})

saint('paphnutius-martyr-egypt','Martyr Paphnutius and 546 Companions','Μάρτυρας Παφνούτιος και 546 Σύντροφοι','Egyptian ascetic and martyr','Αιγύπτιος ασκητής και μάρτυρας','25 September','25 Σεπτεμβρίου',
      'During the Diocletian persecution, the Egyptian ascetic Paphnutius openly confessed Christ and endured repeated tortures. The hagiographic account says that soldiers, prisoners, and families were converted through his witness, producing a large company of martyrs; he was eventually crucified.',
      'Κατά τον διωγμό του Διοκλητιανού, ο Αιγύπτιος ασκητής Παφνούτιος ομολόγησε δημόσια τον Χριστό και υπέμεινε επανειλημμένα βασανιστήρια. Η αγιολογική διήγηση αναφέρει ότι στρατιώτες, φυλακισμένοι και οικογένειες μεταστράφηκαν μέσω της μαρτυρίας του, σχηματίζοντας μεγάλο πλήθος μαρτύρων· τελικά σταυρώθηκε.',
      'https://www.oca.org/saints/lives/2026/09/25/102729-martyr-paphnutius-and-546-companions-in-egypt',
      metadata={'era':'Diocletianic persecution','location':'Egypt','themes_en':['martyrdom','confession','conversion of others','persecution','companions in martyrdom'],'themes_el':['μαρτύριο','ομολογία','μεταστροφή άλλων','διωγμός','σύντροφοι στο μαρτύριο']})


saint('vendemianus-bithynia','Venerable Vendemianus the Hermit of Bithynia','Όσιος Βενδημιανός ο Ερημίτης της Βιθυνίας','Hermit and disciple of Saint Auxentius','Ερημίτης και μαθητής του Αγίου Αυξεντίου','1 February','1 Φεβρουαρίου',
      'Vendemianus was born in Mysia and became a disciple of Saint Auxentius, one of the Fathers associated with the Fourth Ecumenical Council. He lived for forty-two years in asceticism at his teacher’s cell in a cliff crevice near Chalcedon, practicing fasting and prayer; his life also remembers a gift of healing. He reposed around 512.',
      'Ο Βενδημιανός γεννήθηκε στη Μυσία και έγινε μαθητής του Αγίου Αυξεντίου, ενός από τους Πατέρες που συνδέονται με την Δ΄ Οικουμενική Σύνοδο. Ασκήτεψε επί σαράντα δύο χρόνια στο κελλί του διδασκάλου του σε σχισμή βράχου κοντά στη Χαλκηδόνα, με νηστεία και προσευχή· ο βίος του μνημονεύει επίσης χάρισμα ιάσεων. Εκοιμήθη περίπου το 512.',
      'https://www.oca.org/saints/lives/2036/02/01/100405-venerable-vendemianus-the-hermit-of-bithynia',aliases=['Bendemianus','Vendemianus of Bithynia','Βενδημιανός'],
      metadata={'era':'5th–6th century','location':'Bithynia / near Chalcedon','themes_en':['hermit','forty-two years of asceticism','fasting','prayer','healing','disciple of Auxentius'],'themes_el':['ερημίτης','σαράντα δύο χρόνια άσκησης','νηστεία','προσευχή','ιάσεις','μαθητής του Αυξεντίου'],'significance_en':'A comparatively little-known Bithynian hermit whose life gives a concrete picture of long-term solitary asceticism near Chalcedon.','significance_el':'Σχετικά λιγότερο γνωστός ερημίτης της Βιθυνίας, του οποίου ο βίος δίνει συγκεκριμένη εικόνα μακρόχρονης ασκητικής ζωής κοντά στη Χαλκηδόνα.'})

saint('paphnutius-recluse-kiev','Venerable Paphnutius the Recluse of the Kiev Caves','Όσιος Παφνούτιος ο Έγκλειστος των Σπηλαίων του Κιέβου','Kiev Caves recluse remembered for the gift of tears','Έγκλειστος των Σπηλαίων του Κιέβου, γνωστός για το χάρισμα των δακρύων','15 February','15 Φεβρουαρίου',
      'Paphnutius is remembered for the gift of tears joined to remembrance of death. His commemoration describes this remembrance not as despair, but as a discipline leading to prayer, guarding of the mind, repentance, fasting, and freedom from distractions and passions.',
      'Ο Παφνούτιος μνημονεύεται για το χάρισμα των δακρύων, συνδεδεμένο με τη μνήμη του θανάτου. Η παράδοση της μνήμης του παρουσιάζει αυτή τη μνήμη όχι ως απόγνωση, αλλά ως άσκηση που οδηγεί σε προσευχή, νήψη, μετάνοια, νηστεία και ελευθερία από περισπασμούς και πάθη.',
      'https://www.oca.org/saints/lives/2012/02/15/100527-venerable-paphnutius-the-recluse-of-the-kiev-caves',aliases=['Paphnutius of the Kiev Caves','Παφνούτιος των Σπηλαίων του Κιέβου'],
      metadata={'era':'Kiev Caves monastic tradition','location':'Kiev Caves','themes_en':['gift of tears','remembrance of death','watchfulness','repentance','fasting','guarding the mind'],'themes_el':['χάρισμα δακρύων','μνήμη θανάτου','νήψη','μετάνοια','νηστεία','φύλαξη του νου'],'significance_en':'His brief life is especially useful for searches about compunction, tears, remembrance of death, and guarding the mind in Orthodox ascetic teaching.','significance_el':'Ο σύντομος βίος του είναι ιδιαίτερα χρήσιμος σε αναζητήσεις για κατάνυξη, δάκρυα, μνήμη θανάτου και φύλαξη του νου στην ορθόδοξη ασκητική παράδοση.'})

saint('theophanes-faster-kiev','Venerable Theophanes the Faster of the Kiev Near Caves','Όσιος Θεοφάνης ο Νηστευτής των Κοντινών Σπηλαίων του Κιέβου','Twelfth-century ascetic of the Near Caves','Ασκητής του 12ου αιώνα στα Κοντινά Σπήλαια','11 October','11 Οκτωβρίου',
      'The surviving notice about Theophanes is unusually brief. His epithet “the Faster” records the strict fasting through which he pursued life with God. He lived in the twelfth century, and his relics repose in the Near Caves of Saint Anthony; the source explicitly notes that fuller biographical details are not preserved in the commemoration books.',
      'Η σωζόμενη αναφορά για τον Θεοφάνη είναι ασυνήθιστα σύντομη. Η προσωνυμία «Νηστευτής» μαρτυρεί την αυστηρή νηστεία με την οποία επιδίωκε τη ζωή με τον Θεό. Έζησε τον 12ο αιώνα και τα λείψανά του αναπαύονται στα Κοντινά Σπήλαια του Αγίου Αντωνίου· η πηγή σημειώνει ρητά ότι δεν έχουν διασωθεί πληρέστερες βιογραφικές λεπτομέρειες στα βιβλία μνήμης.',
      'https://www.oca.org/saints/lives/2455/10/11/102938-venerable-theophanes-the-faster-of-the-kiev-near-caves',aliases=['Theophanes the Faster','Θεοφάνης ο Νηστευτής'],
      metadata={'era':'12th century','location':'Kiev Near Caves','themes_en':['strict fasting','Near Caves','limited historical record','asceticism'],'themes_el':['αυστηρή νηστεία','Κοντινά Σπήλαια','περιορισμένη ιστορική μαρτυρία','άσκηση'],'significance_en':'A useful example of an obscure saint for whom the Church preserves a real liturgical memory while detailed biography is explicitly unavailable.','significance_el':'Χρήσιμο παράδειγμα λιγότερο γνωστού αγίου για τον οποίο διατηρείται πραγματική λειτουργική μνήμη, ενώ η λεπτομερής βιογραφία δηλώνεται ρητά ως μη σωζόμενη.'})

saint('spyridon-nikodemos-prosphora','Venerable Spyridon and Nikodemos the Prosphora-bakers','Όσιοι Σπυρίδων και Νικόδημος οι Προσφοράρηδες','Kiev Caves monks and prosphora-bakers','Μοναχοί των Σπηλαίων του Κιέβου και προσφοράρηδες','31 October','31 Οκτωβρίου',
      'Spyridon and Nikodemos fulfilled the obedience of baking prosphora for about thirty years. Spyridon entered the monastery in the time of Igumen Pimen, knew the entire Psalter by heart despite being illiterate, and joined his work to constant prayer and daily psalmody. Nikodemos labored with him in a strict ascetic life.',
      'Ο Σπυρίδων και ο Νικόδημος διακονούσαν επί περίπου τριάντα χρόνια στην παρασκευή προσφόρων. Ο Σπυρίδων εισήλθε στη μονή επί ηγουμένου Ποιμένος, γνώριζε ολόκληρο το Ψαλτήρι απ’ έξω παρότι ήταν αγράμματος και συνέδεε την εργασία του με αδιάλειπτη προσευχή και καθημερινή ψαλμωδία. Ο Νικόδημος ασκήθηκε μαζί του με αυστηρή ζωή.',
      'https://www.oca.org/saints/lives/0201/10/31/103129-venerable-spyridon-and-ikdmos-the-prosphora-bakers-of-the-kiev-c',aliases=['Spyridon the Prosphora-baker','Nikodemos the Prosphora-baker','Σπυρίδων και Νικόδημος Προσφοράρηδες'],
      metadata={'era':'12th century','location':'Kiev Caves','themes_en':['prosphora','bread baking','Psalter by heart','unceasing prayer','work and prayer','obedience'],'themes_el':['πρόσφορα','αρτοποιία','Ψαλτήρι από μνήμης','αδιάλειπτη προσευχή','εργασία και προσευχή','διακόνημα'],'significance_en':'Their life connects ordinary monastery work—baking the Eucharistic offering bread—with memorization of the Psalter and continual prayer.','significance_el':'Ο βίος τους συνδέει ένα καθημερινό μοναστηριακό διακόνημα — την παρασκευή του ευχαριστιακού προσφόρου — με την απομνημόνευση του Ψαλτηρίου και την αδιάλειπτη προσευχή.'})

saint('onuphrius-onesimos-kiev','Venerable Onuphrius the Silent and Onesimos the Recluse','Όσιοι Ονούφριος ο Σιωπηλός και Ονήσιμος ο Έγκλειστος','Ascetics of the Kiev Near Caves','Ασκητές των Κοντινών Σπηλαίων του Κιέβου','21 July','21 Ιουλίου',
      'Onuphrius the Silent was a twelfth-century ascetic of the Near Caves of Saint Anthony. Onesimos, who lived in the twelfth to thirteenth centuries, practiced enclosure in the same Near Caves. The surviving notice is sparse and emphasizes their forms of ascetic withdrawal rather than supplying a detailed narrative life.',
      'Ο Ονούφριος ο Σιωπηλός ήταν ασκητής του 12ου αιώνα στα Κοντινά Σπήλαια του Αγίου Αντωνίου. Ο Ονήσιμος, που έζησε τον 12ο–13ο αιώνα, ασκήθηκε ως έγκλειστος στα ίδια Σπήλαια. Η σωζόμενη αναφορά είναι λιτή και τονίζει τις μορφές ασκητικής απομόνωσής τους αντί να παρέχει εκτενή βιογραφική αφήγηση.',
      'https://www.oca.org/saints/lives/1134/07/21/102067-venerable-onuphrius-the-silent-and-venerable-onesimos-the-reclus',aliases=['Onuphrius the Silent','Onesimos the Recluse','Ονούφριος ο Σιωπηλός','Ονήσιμος ο Έγκλειστος'],
      metadata={'era':'12th–13th century','location':'Kiev Near Caves','themes_en':['silence','reclusion','Near Caves','ascetic withdrawal','sparse biography'],'themes_el':['σιωπή','εγκλεισμός','Κοντινά Σπήλαια','ασκητική απομόνωση','λιτή βιογραφική μαρτυρία'],'significance_en':'These little-known Kiev ascetics are especially relevant to searches for silence, enclosure, and the diversity of Orthodox monastic disciplines.','significance_el':'Αυτοί οι λιγότερο γνωστοί ασκητές του Κιέβου είναι ιδιαίτερα σχετικοί με αναζητήσεις για σιωπή, εγκλεισμό και την ποικιλία των ορθόδοξων μοναχικών ασκήσεων.'})

saint('moses-hungarian','Venerable Moses the Hungarian of the Kiev Near Caves','Όσιος Μωυσής ο Ούγγρος των Κοντινών Σπηλαίων του Κιέβου','Kiev Caves monk and confessor of chastity','Μοναχός των Σπηλαίων του Κιέβου και ομολογητής της αγνότητας','26 July','26 Ιουλίου',
      'Moses, a Hungarian by birth and servant in the household of the holy Prince Boris, survived the violence surrounding Boris’s death and was later taken captive to Poland. His life remembers his refusal of a wealthy widow’s attempts to force him into marriage and his determination to embrace the monastic schema despite coercion and suffering.',
      'Ο Μωυσής, Ούγγρος στην καταγωγή και υπηρέτης στην ακολουθία του αγίου πρίγκιπα Βόριδος, επέζησε από τη βία γύρω από τον θάνατο του Βόριδος και αργότερα αιχμαλωτίστηκε στην Πολωνία. Ο βίος του θυμάται την άρνησή του στις προσπάθειες μιας πλούσιας χήρας να τον εξαναγκάσει σε γάμο και την αποφασιστικότητά του να δεχθεί το μοναχικό σχήμα παρά τον καταναγκασμό και τα παθήματα.',
      'https://www.oca.org/saints/lives/2022/07/26/102095-venerable-moses-the-hungarian-of-the-kiev-near-caves',aliases=['Moses the Hungarian','Moses of the Kiev Caves','Μωυσής ο Ούγγρος'],
      metadata={'era':'11th century','location':'Kiev / Poland','themes_en':['captivity','chastity','coercion resisted','monastic vocation','Prince Boris'],'themes_el':['αιχμαλωσία','αγνότητα','αντίσταση σε καταναγκασμό','μοναχική κλήση','πρίγκιπας Βόρις'],'significance_en':'His life is a less-known account of monastic vocation under captivity and coercion, centered on fidelity to a freely chosen ascetic calling.','significance_el':'Ο βίος του είναι λιγότερο γνωστή διήγηση μοναχικής κλήσης μέσα σε αιχμαλωσία και καταναγκασμό, με κέντρο την πιστότητα σε ελεύθερα επιλεγμένη ασκητική κλήση.'})

saint('john-faster-constantinople','Saint John the Faster, Patriarch of Constantinople','Άγιος Ιωάννης ο Νηστευτής, Πατριάρχης Κωνσταντινουπόλεως','Patriarch, ascetic, and teacher on repentance','Πατριάρχης, ασκητής και διδάσκαλος της μετάνοιας','2 September','2 Σεπτεμβρίου',
      'John was born in Constantinople and first worked as a goldsmith. Known for continence and fasting, he entered clerical service and eventually became Patriarch of Constantinople from 582 to 595. His life emphasizes daily study of Scripture, strict fasting, care for the poor, prayer, and writings associated with repentance and confession.',
      'Ο Ιωάννης γεννήθηκε στην Κωνσταντινούπολη και αρχικά εργαζόταν ως χρυσοχόος. Γνωστός για την εγκράτεια και τη νηστεία του, εισήλθε στην εκκλησιαστική διακονία και τελικά έγινε Πατριάρχης Κωνσταντινουπόλεως από το 582 έως το 595. Ο βίος του τονίζει την καθημερινή μελέτη της Αγίας Γραφής, την αυστηρή νηστεία, τη φροντίδα των φτωχών, την προσευχή και συγγράμματα που συνδέονται με τη μετάνοια και την εξομολόγηση.',
      'https://www.oca.org/saints/lives/0577/09/02/102462-saint-john-the-faster-patriarch-of-constantinople',aliases=['John IV of Constantinople','John the Faster','Ιωάννης ο Νηστευτής'],
      metadata={'era':'6th century','location':'Constantinople','themes_en':['Patriarch of Constantinople','fasting','repentance','confession','care for the poor','daily Scripture study'],'themes_el':['Πατριάρχης Κωνσταντινουπόλεως','νηστεία','μετάνοια','εξομολόγηση','φροντίδα φτωχών','καθημερινή μελέτη Αγίας Γραφής'],'significance_en':'His life joins patriarchal ministry to radical personal simplicity, fasting, care for the poor, and teaching on repentance and confession.','significance_el':'Ο βίος του συνδέει την πατριαρχική διακονία με προσωπική απλότητα, νηστεία, φροντίδα των φτωχών και διδασκαλία για τη μετάνοια και την εξομολόγηση.'})

# Biblical / visionary beings and symbolic figures. These are context records, not objects of veneration.
def context_entry(id,en,el,role_en,role_el,scripture,story_en,story_el,themes_en,themes_el):
    entries.append({
      'id':id,'name':pair(en,el),'category':'biblical-context','role':pair(role_en,role_el),
      'story':pair(story_en,story_el),'feast':pair('No separate feast; biblical context','Χωρίς ιδιαίτερη εορτή· βιβλικό πλαίσιο'),
      'scripture':scripture,'prayer':pair('Lord God, grant us wisdom to read these biblical images faithfully, without fear or speculation, and lead us to Christ.','Κύριε Θεέ, χάρισέ μας σοφία να διαβάζουμε πιστά αυτές τις βιβλικές εικόνες, χωρίς φόβο ή αυθαίρετες εικασίες, και οδήγησέ μας στον Χριστό.'),
      'notes':pair('This is a biblical-context entry. Symbolic or visionary language is not treated as a literal taxonomy beyond what the text itself states.','Πρόκειται για καταχώριση βιβλικού πλαισίου. Η συμβολική ή οραματική γλώσσα δεν μετατρέπεται σε κυριολεκτική ταξινομία πέρα από όσα δηλώνει το ίδιο το κείμενο.'),
      'aliases':[],'venerated':False,'image':f'web/images/catalog/{id}.svg','metadata':{'themes_en':themes_en,'themes_el':themes_el,'type':'biblical visionary/context'},
      'search':' '.join([en,el,role_en,role_el,scripture,*themes_en,*themes_el])
    })

context_entry('angel-of-the-lord','Angel of the Lord','Άγγελος Κυρίου','Mysterious messenger appearing in biblical narratives','Μυστηριώδης αγγελιοφόρος σε βιβλικές διηγήσεις','Genesis 16; Genesis 22; Exodus 3; Judges 6; Judges 13','The phrase “Angel of the Lord” appears in several biblical narratives, sometimes with unusually close identification between the messenger and God’s own speech. Christian interpretation has approached these passages carefully and variously, often reading them christologically without reducing every occurrence to one simple formula.','Η φράση «Άγγελος Κυρίου» εμφανίζεται σε πολλές βιβλικές διηγήσεις, μερικές φορές με ιδιαίτερα στενή σύνδεση ανάμεσα στον αγγελιοφόρο και τον ίδιο τον λόγο του Θεού. Η χριστιανική ερμηνεία προσεγγίζει τα χωρία με προσοχή και ποικιλία, συχνά χριστολογικά, χωρίς να περιορίζει κάθε εμφάνιση σε μία απλή ταύτιση.',['divine messenger','theophany','angel','Old Testament','Christological interpretation'],['θείος αγγελιοφόρος','θεοφάνεια','άγγελος','Παλαιά Διαθήκη','χριστολογική ερμηνεία'])
context_entry('wheels-ezekiel','Wheels in Ezekiel’s Vision','Τροχοί στο Όραμα του Ιεζεκιήλ','Visionary wheels associated with the living creatures','Οραματικοί τροχοί συνδεδεμένοι με τα ζῷα','Ezekiel 1; Ezekiel 10','Ezekiel describes immense, intersecting wheels beside the living creatures, full of eyes and moving in harmony with the Spirit. Later religious art and commentary sometimes call them “ophanim,” but the catalog keeps the biblical image distinct from later angelic classifications.','Ο Ιεζεκιήλ περιγράφει μεγάλους αλληλοτεμνόμενους τροχούς δίπλα στα ζῷα, γεμάτους οφθαλμούς και κινούμενους σε αρμονία με το Πνεύμα. Μεταγενέστερη τέχνη και ερμηνεία τους αποκαλεί συχνά «Οφανίμ», αλλά ο κατάλογος διακρίνει τη βιβλική εικόνα από μεταγενέστερες αγγελικές ταξινομήσεις.',['Ezekiel','wheels','ophanim','living creatures','divine throne vision'],['Ιεζεκιήλ','τροχοί','Οφανίμ','ζῷα','όραμα θείου θρόνου'])
context_entry('twenty-four-elders','Twenty-Four Elders','Είκοσι Τέσσερις Πρεσβύτεροι','Heavenly elders around the throne in Revelation','Ουράνιοι πρεσβύτεροι γύρω από τον θρόνο στην Αποκάλυψη','Revelation 4–5; Revelation 11; Revelation 19','Revelation portrays twenty-four elders seated around God’s throne, clothed in white and crowned, worshipping God and the Lamb. Their exact symbolic identification is interpreted in several ways; the text clearly presents them as part of the heavenly worship scene.','Η Αποκάλυψη παρουσιάζει είκοσι τέσσερις πρεσβυτέρους καθισμένους γύρω από τον θρόνο του Θεού, ντυμένους στα λευκά και στεφανωμένους, να προσκυνούν τον Θεό και το Αρνίο. Η ακριβής συμβολική τους ταύτιση ερμηνεύεται με περισσότερους από έναν τρόπους· το κείμενο τους εντάσσει καθαρά στη σκηνή της ουράνιας λατρείας.',['Revelation','heavenly worship','elders','throne','Lamb'],['Αποκάλυψη','ουράνια λατρεία','πρεσβύτεροι','θρόνος','Αρνίο'])
context_entry('four-horsemen','Four Horsemen of Revelation','Τέσσερις Ιππείς της Αποκάλυψης','Apocalyptic figures released with the first four seals','Αποκαλυπτικές μορφές των τεσσάρων πρώτων σφραγίδων','Revelation 6:1–8','The opening of the first four seals is accompanied by four horsemen on white, red, black, and pale horses. The passage uses compressed apocalyptic imagery associated with conquest, violence, scarcity, and death; interpretation should remain anchored in Revelation rather than sensational speculation.','Το άνοιγμα των τεσσάρων πρώτων σφραγίδων συνοδεύεται από τέσσερις ιππείς σε λευκό, κόκκινο, μαύρο και ωχρό άλογο. Το χωρίο χρησιμοποιεί πυκνή αποκαλυπτική εικόνα που συνδέεται με κατάκτηση, βία, έλλειψη και θάνατο· η ερμηνεία πρέπει να παραμένει δεμένη με το κείμενο και όχι με εντυπωσιοθηρικές εικασίες.',['Revelation','seals','horsemen','apocalyptic symbolism','judgment'],['Αποκάλυψη','σφραγίδες','ιππείς','αποκαλυπτικός συμβολισμός','κρίση'])
context_entry('woman-clothed-sun','Woman Clothed with the Sun','Γυναίκα Περιβεβλημένη τον Ήλιο','Symbolic woman in the vision of Revelation 12','Συμβολική γυναίκα στο όραμα της Αποκάλυψης 12','Revelation 12','Revelation 12 depicts a woman clothed with the sun, the moon under her feet, and a crown of twelve stars, opposed by the dragon. Christian interpretation has seen ecclesial and Marian dimensions in the image; the entry presents these as interpretive layers rather than a single exhaustive identification.','Η Αποκάλυψη 12 παρουσιάζει γυναίκα περιβεβλημένη τον ήλιο, με τη σελήνη κάτω από τα πόδια της και στέφανο δώδεκα αστέρων, απέναντι στον δράκοντα. Η χριστιανική ερμηνεία διακρίνει εκκλησιολογικές και μαριολογικές διαστάσεις στην εικόνα· η καταχώριση τις παρουσιάζει ως ερμηνευτικά επίπεδα και όχι ως μία εξαντλητική ταύτιση.',['Revelation 12','woman','Church','Theotokos','dragon','twelve stars'],['Αποκάλυψη 12','γυναίκα','Εκκλησία','Θεοτόκος','δράκοντας','δώδεκα αστέρια'])
context_entry('two-witnesses-revelation','Two Witnesses of Revelation','Δύο Μάρτυρες της Αποκάλυψης','Prophetic witnesses in Revelation 11','Προφητικοί μάρτυρες στην Αποκάλυψη 11','Revelation 11:3–13','Revelation describes two witnesses who prophesy, confront opposition, are killed, and are vindicated by God. Later interpretations have proposed identities such as Enoch and Elijah, but the biblical text itself does not name them.','Η Αποκάλυψη περιγράφει δύο μάρτυρες που προφητεύουν, αντιμετωπίζουν εχθρότητα, θανατώνονται και δικαιώνονται από τον Θεό. Μεταγενέστερες ερμηνείες πρότειναν ταυτίσεις όπως ο Ενώχ και ο Ηλίας, αλλά το ίδιο το βιβλικό κείμενο δεν τους ονομάζει.',['Revelation 11','two witnesses','prophecy','martyrdom','vindication','Enoch and Elijah tradition'],['Αποκάλυψη 11','δύο μάρτυρες','προφητεία','μαρτύριο','δικαίωση','παράδοση Ενώχ και Ηλία'])
context_entry('abaddon-abyss','Angel of the Abyss — Abaddon/Apollyon','Άγγελος της Αβύσσου — Αβαδδών/Απολλύων','Destructive figure named in Revelation 9','Καταστροφική μορφή που ονομάζεται στην Αποκάλυψη 9','Revelation 9:1–11','Revelation names the king over the plague-like locusts as the angel of the abyss, called Abaddon in Hebrew and Apollyon in Greek, both connected with destruction. This is not a saintly angel and receives no veneration.','Η Αποκάλυψη ονομάζει τον βασιλιά πάνω από τις πληγόμορφες ακρίδες ως άγγελο της αβύσσου, Αβαδδών στα εβραϊκά και Απολλύων στα ελληνικά, ονόματα που συνδέονται με την καταστροφή. Δεν πρόκειται για άγιο άγγελο και δεν τιμάται.',['Revelation 9','Abaddon','Apollyon','abyss','destruction','not venerated'],['Αποκάλυψη 9','Αβαδδών','Απολλύων','άβυσσος','καταστροφή','μη τιμώμενος'])
context_entry('seven-trumpet-angels','Seven Angels with Trumpets','Επτά Άγγελοι με Σάλπιγγες','Angels associated with the seven trumpets of Revelation','Άγγελοι των επτά σαλπίγγων της Αποκάλυψης','Revelation 8–11','Seven angels receive seven trumpets whose sounding structures a major sequence of visions and judgments in Revelation. The text emphasizes divine sovereignty, warning, repentance, and the movement of history toward God’s kingdom.','Επτά άγγελοι λαμβάνουν επτά σάλπιγγες, των οποίων το σάλπισμα οργανώνει μεγάλη ακολουθία οραμάτων και κρίσεων στην Αποκάλυψη. Το κείμενο τονίζει την κυριαρχία του Θεού, την προειδοποίηση, τη μετάνοια και την πορεία της ιστορίας προς τη Βασιλεία Του.',['Revelation','seven trumpets','angels','judgment','repentance'],['Αποκάλυψη','επτά σάλπιγγες','άγγελοι','κρίση','μετάνοια'])
context_entry('seven-bowl-angels','Seven Angels with the Bowls','Επτά Άγγελοι με τις Φιάλες','Angels associated with the seven bowls of Revelation','Άγγελοι των επτά φιαλών της Αποκάλυψης','Revelation 15–16','Revelation portrays seven angels receiving bowls associated with the final sequence of plagues. The imagery belongs to apocalyptic judgment and echoes the Exodus plagues while pointing toward the defeat of evil.','Η Αποκάλυψη παρουσιάζει επτά αγγέλους που λαμβάνουν φιάλες συνδεδεμένες με την τελική ακολουθία πληγών. Η εικόνα ανήκει στην αποκαλυπτική κρίση, θυμίζει τις πληγές της Εξόδου και κατευθύνεται προς την ήττα του κακού.',['Revelation','seven bowls','angels','plagues','Exodus echoes'],['Αποκάλυψη','επτά φιάλες','άγγελοι','πληγές','αναφορές στην Έξοδο'])
context_entry('morning-stars-job','Morning Stars in Job','Πρωινοί Αστέρες στον Ιώβ','Poetic heavenly beings in God’s speech to Job','Ποιητική εικόνα ουράνιων όντων στον λόγο του Θεού προς τον Ιώβ','Job 38:4–7','In God’s speech from the whirlwind, the laying of the earth’s foundations is accompanied by the morning stars singing together and the sons of God shouting for joy. The language is poetic and cosmic, depicting creation as an event celebrated by the heavenly realm.','Στον λόγο του Θεού μέσα από τον ανεμοστρόβιλο, η θεμελίωση της γης συνοδεύεται από τους πρωινούς αστέρες που ψάλλουν μαζί και τους υιούς του Θεού που αλαλάζουν από χαρά. Η γλώσσα είναι ποιητική και κοσμική, παρουσιάζοντας τη δημιουργία ως γεγονός που εορτάζεται από τον ουράνιο κόσμο.',['Job 38','creation','morning stars','sons of God','heavenly joy'],['Ιώβ 38','δημιουργία','πρωινοί αστέρες','υιοί Θεού','ουράνια χαρά'])

# Parables — summarized, never reproducing a copyrighted translation.
PARABLES=[
('parable-sower','Parable of the Sower','Παραβολή του Σπορέα','Matthew 13:1–23; Mark 4:1–20; Luke 8:4–15','Seed falls on different kinds of ground. Jesus interprets the soils as different ways the word of God is received, ranging from immediate loss to lasting fruitfulness.','Ο σπόρος πέφτει σε διαφορετικά είδη γης. Ο Ιησούς ερμηνεύει τα εδάφη ως διαφορετικούς τρόπους υποδοχής του λόγου του Θεού, από την άμεση απώλεια έως τη σταθερή καρποφορία.',['word of God','hearing','perseverance','fruitfulness']),
('parable-weeds','Parable of the Wheat and Weeds','Παραβολή των Ζιζανίων','Matthew 13:24–30, 36–43','An enemy sows weeds among good wheat, but the owner delays separation until harvest. Jesus connects the image with patient judgment and the final setting-right of evil.','Ένας εχθρός σπέρνει ζιζάνια ανάμεσα στο καλό σιτάρι, αλλά ο κύριος αναβάλλει τον χωρισμό μέχρι τον θερισμό. Ο Ιησούς συνδέει την εικόνα με την υπομονή και την τελική κρίση του κακού.',['kingdom','judgment','patience','good and evil']),
('parable-mustard-seed','Parable of the Mustard Seed','Παραβολή του Κόκκου Σινάπεως','Matthew 13:31–32; Mark 4:30–32; Luke 13:18–19','The Kingdom is compared with a tiny seed that grows into something unexpectedly large, stressing hidden beginnings and surprising growth.','Η Βασιλεία παρομοιάζεται με έναν πολύ μικρό σπόρο που μεγαλώνει σε κάτι απροσδόκητα μεγάλο, τονίζοντας τις κρυφές αρχές και την εντυπωσιακή αύξηση.',['kingdom','small beginnings','growth','hope']),
('parable-leaven','Parable of the Leaven','Παραβολή της Ζύμης','Matthew 13:33; Luke 13:20–21','A small amount of leaven works through a large quantity of dough, an image of the Kingdom’s quiet and transforming presence.','Μικρή ποσότητα ζύμης διαπερνά μεγάλη ποσότητα αλευριού, εικόνα της ήσυχης και μεταμορφωτικής παρουσίας της Βασιλείας.',['kingdom','hidden transformation','growth']),
('parable-hidden-treasure','Parable of the Hidden Treasure','Παραβολή του Κρυμμένου Θησαυρού','Matthew 13:44','A person discovers treasure hidden in a field and joyfully gives up everything to obtain the field. The parable highlights the incomparable value of God’s Kingdom.','Κάποιος ανακαλύπτει θησαυρό κρυμμένο σε αγρό και με χαρά δίνει τα πάντα για να αποκτήσει τον αγρό. Η παραβολή τονίζει την ασύγκριτη αξία της Βασιλείας του Θεού.',['kingdom','joy','value','renunciation']),
('parable-pearl','Parable of the Pearl of Great Price','Παραβολή του Πολύτιμου Μαργαριταριού','Matthew 13:45–46','A merchant searching for fine pearls finds one of exceptional value and sells everything to obtain it, portraying wholehearted commitment to the Kingdom.','Έμπορος που αναζητά εκλεκτά μαργαριτάρια βρίσκει ένα εξαιρετικής αξίας και πουλά τα πάντα για να το αποκτήσει, εικόνα ολοκληρωτικής αφοσίωσης στη Βασιλεία.',['kingdom','discernment','value','commitment']),
('parable-dragnet','Parable of the Dragnet','Παραβολή του Δικτύου','Matthew 13:47–50','A net gathers fish of every kind before a final sorting. Jesus uses the image to speak of the completion of the age and judgment.','Ένα δίχτυ συγκεντρώνει ψάρια κάθε είδους πριν από τον τελικό διαχωρισμό. Ο Ιησούς χρησιμοποιεί την εικόνα για το τέλος του αιώνα και την κρίση.',['kingdom','judgment','end of the age']),
('parable-lost-sheep','Parable of the Lost Sheep','Παραβολή του Απολωλότος Προβάτου','Matthew 18:12–14; Luke 15:3–7','A shepherd leaves the larger flock to seek one lost sheep and rejoices when it is found. The image emphasizes God’s seeking mercy and the value of the person who has strayed.','Ποιμένας αφήνει το μεγαλύτερο ποίμνιο για να αναζητήσει ένα χαμένο πρόβατο και χαίρεται όταν το βρίσκει. Η εικόνα τονίζει το έλεος του Θεού που αναζητεί και την αξία του ανθρώπου που απομακρύνθηκε.',['mercy','repentance','shepherd','lost and found']),
('parable-lost-coin','Parable of the Lost Coin','Παραβολή της Χαμένης Δραχμής','Luke 15:8–10','A woman searches carefully for one lost coin and celebrates after finding it. Jesus connects the joy with heavenly rejoicing over repentance.','Μια γυναίκα αναζητεί προσεκτικά μία χαμένη δραχμή και γιορτάζει όταν τη βρίσκει. Ο Ιησούς συνδέει τη χαρά με την ουράνια αγαλλίαση για τη μετάνοια.',['repentance','joy','search','lost and found']),
('parable-prodigal-son','Parable of the Prodigal Son','Παραβολή του Ασώτου Υιού','Luke 15:11–32','A younger son wastes his inheritance and returns in repentance; his father receives him with compassion, while the elder brother struggles with resentment. The parable joins repentance, mercy, restoration, and the danger of self-righteousness.','Ο νεότερος γιος σπαταλά την κληρονομιά του και επιστρέφει μετανοημένος· ο πατέρας τον δέχεται με συμπόνια, ενώ ο μεγαλύτερος αδελφός παλεύει με την πικρία. Η παραβολή ενώνει τη μετάνοια, το έλεος, την αποκατάσταση και τον κίνδυνο της αυτοδικαίωσης.',['repentance','mercy','forgiveness','fatherhood','self-righteousness']),
('parable-good-samaritan','Parable of the Good Samaritan','Παραβολή του Καλού Σαμαρείτη','Luke 10:25–37','A wounded traveler is ignored by respected passers-by and helped by a Samaritan, a social outsider to the hearers. Jesus turns the question of defining one’s neighbor into a call to become merciful toward the person in need.','Ένας τραυματισμένος ταξιδιώτης αγνοείται από σεβαστά πρόσωπα και βοηθιέται από έναν Σαμαρείτη, κοινωνικά ξένο για τους ακροατές. Ο Ιησούς μετατρέπει το ερώτημα «ποιος είναι ο πλησίον» σε κλήση να γίνουμε εμείς πλησίον με έλεος προς τον άνθρωπο που έχει ανάγκη.',['mercy','neighbor','compassion','love','Samaritan']),
('parable-rich-fool','Parable of the Rich Fool','Παραβολή του Άφρονος Πλουσίου','Luke 12:13–21','A wealthy man plans larger barns and a secure future but dies before enjoying his stored goods. Jesus warns against defining life by possessions rather than becoming rich toward God.','Ένας πλούσιος σχεδιάζει μεγαλύτερες αποθήκες και ασφαλές μέλλον, αλλά πεθαίνει πριν απολαύσει τα αποθέματά του. Ο Ιησούς προειδοποιεί να μη μετριέται η ζωή με τα υπάρχοντα, αλλά με τον πλούτο ενώπιον του Θεού.',['wealth','death','greed','eternity','stewardship']),
('parable-barren-fig-tree','Parable of the Barren Fig Tree','Παραβολή της Άκαρπης Συκής','Luke 13:6–9','A fruitless fig tree is given additional time and care rather than being cut down immediately. The image joins divine patience with the urgency of repentance and fruitfulness.','Μια άκαρπη συκιά λαμβάνει επιπλέον χρόνο και φροντίδα αντί να κοπεί αμέσως. Η εικόνα συνδέει τη θεία μακροθυμία με την επείγουσα ανάγκη μετανοίας και καρποφορίας.',['repentance','patience','fruitfulness','mercy']),
('parable-great-banquet','Parable of the Great Banquet','Παραβολή του Μεγάλου Δείπνου','Luke 14:15–24','Invited guests make excuses, so the host brings in the poor, disabled, and outsiders. The parable warns against refusing God’s invitation and stresses the surprising breadth of the invitation.','Οι προσκεκλημένοι προβάλλουν δικαιολογίες, και έτσι ο οικοδεσπότης καλεί φτωχούς, αναπήρους και ανθρώπους από έξω. Η παραβολή προειδοποιεί να μην απορρίπτουμε την πρόσκληση του Θεού και τονίζει το απροσδόκητο εύρος της.',['invitation','kingdom','excuses','poor','hospitality']),
('parable-unforgiving-servant','Parable of the Unforgiving Servant','Παραβολή του Ανελεήμονος Δούλου','Matthew 18:23–35','A servant forgiven an enormous debt refuses mercy to someone owing him far less. Jesus uses the contrast to connect receiving forgiveness with extending forgiveness to others.','Ένας δούλος που του χαρίζεται τεράστιο χρέος αρνείται έλεος σε κάποιον που του οφείλει πολύ λιγότερα. Ο Ιησούς συνδέει τη λήψη συγχώρησης με την προσφορά συγχώρησης στους άλλους.',['forgiveness','mercy','debt','judgment']),
('parable-workers-vineyard','Parable of the Workers in the Vineyard','Παραβολή των Εργατών του Αμπελώνα','Matthew 20:1–16','Workers hired at different hours receive the same wage, provoking resentment among those who worked longest. The parable challenges calculations of entitlement and emphasizes the generosity of the master.','Εργάτες που προσλαμβάνονται σε διαφορετικές ώρες λαμβάνουν τον ίδιο μισθό, προκαλώντας αγανάκτηση σε όσους εργάστηκαν περισσότερο. Η παραβολή αμφισβητεί τη λογική της αξίωσης και τονίζει τη γενναιοδωρία του κυρίου.',['grace','generosity','envy','kingdom']),
('parable-two-sons','Parable of the Two Sons','Παραβολή των Δύο Υιών','Matthew 21:28–32','One son initially refuses his father’s request but later obeys; the other agrees verbally and does nothing. Jesus highlights the difference between words and actual repentance expressed in action.','Ο ένας γιος αρχικά αρνείται το αίτημα του πατέρα αλλά αργότερα υπακούει· ο άλλος συμφωνεί με λόγια και δεν πράττει. Ο Ιησούς τονίζει τη διαφορά ανάμεσα στα λόγια και στην πραγματική μετάνοια που εκφράζεται με πράξη.',['obedience','repentance','words and deeds']),
('parable-wicked-tenants','Parable of the Wicked Tenants','Παραβολή των Κακών Γεωργών','Matthew 21:33–46; Mark 12:1–12; Luke 20:9–19','Tenant farmers abuse the owner’s servants and finally kill his son. The parable confronts rejection of God’s messengers and points toward the rejection of the Son.','Γεωργοί κακοποιούν τους δούλους του ιδιοκτήτη και τελικά σκοτώνουν τον γιο του. Η παραβολή ελέγχει την απόρριψη των απεσταλμένων του Θεού και κατευθύνει προς την απόρριψη του Υιού.',['prophets','Son','rejection','judgment','vineyard']),
('parable-wedding-banquet','Parable of the Wedding Banquet','Παραβολή των Γάμων','Matthew 22:1–14','A royal wedding invitation is rejected by the first guests and extended broadly to others; Matthew also includes the warning image of a guest without a wedding garment. The parable combines invitation, accountability, and readiness.','Η βασιλική πρόσκληση σε γάμο απορρίπτεται από τους πρώτους καλεσμένους και επεκτείνεται ευρύτερα σε άλλους· ο Ματθαίος περιλαμβάνει και την προειδοποιητική εικόνα του καλεσμένου χωρίς ένδυμα γάμου. Η παραβολή συνδυάζει πρόσκληση, ευθύνη και ετοιμότητα.',['kingdom','invitation','wedding garment','readiness','judgment']),
('parable-ten-virgins','Parable of the Ten Virgins','Παραβολή των Δέκα Παρθένων','Matthew 25:1–13','Ten young women await the bridegroom; five prepare sufficient oil and five do not. The central command is spiritual watchfulness because the time of the bridegroom’s arrival is unknown.','Δέκα παρθένες περιμένουν τον νυμφίο· πέντε έχουν προνοήσει αρκετό λάδι και πέντε όχι. Η κεντρική προτροπή είναι η πνευματική εγρήγορση, επειδή ο χρόνος της άφιξης του νυμφίου είναι άγνωστος.',['watchfulness','bridegroom','readiness','Holy Week']),
('parable-talents','Parable of the Talents','Παραβολή των Ταλάντων','Matthew 25:14–30','Servants receive different sums to steward during their master’s absence. The story emphasizes faithful use of what is entrusted rather than fear-driven inactivity.','Δούλοι λαμβάνουν διαφορετικά ποσά για να τα διαχειριστούν όσο απουσιάζει ο κύριός τους. Η διήγηση τονίζει την πιστή αξιοποίηση όσων μας εμπιστεύεται ο Θεός και όχι την αδράνεια που γεννά ο φόβος.',['stewardship','faithfulness','gifts','accountability']),
('parable-pharisee-publican','Parable of the Publican and the Pharisee','Παραβολή του Τελώνη και του Φαρισαίου','Luke 18:9–14','A Pharisee lists his religious achievements while a tax collector asks God for mercy. Jesus says the humble penitent goes home justified rather than the self-exalting man.','Ένας Φαρισαίος απαριθμεί τα θρησκευτικά του κατορθώματα, ενώ ένας τελώνης ζητεί το έλεος του Θεού. Ο Ιησούς λέει ότι ο ταπεινός μετανοών δικαιώνεται και όχι εκείνος που υψώνει τον εαυτό του.',['humility','repentance','prayer','Great Lent','self-righteousness']),
('parable-persistent-widow','Parable of the Persistent Widow','Παραβολή της Επίμονης Χήρας','Luke 18:1–8','A widow repeatedly appeals to an unjust judge until he finally acts. Jesus uses the contrast to encourage persistent prayer and confidence in God’s justice.','Μια χήρα απευθύνεται επανειλημμένα σε άδικο δικαστή μέχρι εκείνος να ενεργήσει. Ο Ιησούς χρησιμοποιεί την αντίθεση για να ενθαρρύνει την επίμονη προσευχή και την εμπιστοσύνη στη δικαιοσύνη του Θεού.',['persistent prayer','justice','faith','perseverance']),
('parable-rich-man-lazarus','Rich Man and Lazarus','Πλούσιος και Λάζαρος','Luke 16:19–31','A rich man ignores poor Lazarus at his gate; after death their conditions are reversed. The story warns against indifference to suffering and insists that the revealed word already calls people to repentance.','Ένας πλούσιος αγνοεί τον φτωχό Λάζαρο στην πύλη του· μετά τον θάνατο οι καταστάσεις τους αντιστρέφονται. Η διήγηση προειδοποιεί για την αδιαφορία απέναντι στον πόνο και τονίζει ότι ο αποκαλυμμένος λόγος ήδη καλεί τους ανθρώπους σε μετάνοια.',['poor','wealth','afterlife','repentance','Moses and prophets'])
]

def add_parable(row):
    id,en,el,scripture,se,sg,themes=row
    entries.append({'id':id,'name':pair(en,el),'category':'parable','role':pair('Parable / teaching of Jesus','Παραβολή / διδασκαλία του Ιησού'),'story':pair(se,sg),'feast':pair('Read within the Gospel and the Church’s liturgical cycle','Αναγιγνώσκεται στο Ευαγγέλιο και στον λειτουργικό κύκλο της Εκκλησίας'),'scripture':scripture,'prayer':pair('Lord Jesus Christ, open our minds and hearts to receive this parable with repentance, wisdom, and mercy, and help us put Your teaching into practice.','Κύριε Ιησού Χριστέ, άνοιξε τον νου και την καρδιά μας ώστε να δεχθούμε αυτή την παραβολή με μετάνοια, σοφία και έλεος και βοήθησέ μας να κάνουμε πράξη τη διδασκαλία Σου.'),'notes':pair('Parable summaries are paraphrases of the Gospel narrative, not quotations from a modern Bible translation.','Οι περιλήψεις των παραβολών είναι παραφράσεις της ευαγγελικής διήγησης και όχι αυτούσιες παραθέσεις από σύγχρονη μετάφραση της Βίβλου.'),'aliases':[],'venerated':False,'image':f'web/images/catalog/{id}.svg','metadata':{'themes_en':themes,'themes_el':themes,'type':'parable','teacher':'Jesus Christ'},'knowledge':{'en':{'sections':[{'title':'Narrative','text':se},{'title':'Main spiritual themes','text':'; '.join(themes)},{'title':'Reading note','text':f'The primary text is {scripture}. The summary intentionally avoids pretending that every detail has only one possible patristic application.'}],'sources':[]},'el':{'sections':[{'title':'Διήγηση','text':sg},{'title':'Κύρια πνευματικά θέματα','text':'; '.join(themes)},{'title':'Σημείωση ανάγνωσης','text':f'Κύριο βιβλικό κείμενο: {scripture}. Η περίληψη αποφεύγει να παρουσιάσει κάθε λεπτομέρεια σαν να είχε μία και μοναδική πατερική εφαρμογή.'}],'sources':[]}},'search':' '.join([en,el,scripture,*themes])})
for r in PARABLES:add_parable(r)

# Key psalms. Orthodox/LXX numbering is primary; common Masoretic number is shown when different.
PSALMS=[
(1,'1','Two ways: delight in God’s law and the contrast between the righteous and the wicked.','Δύο οδοί: χαρά στον νόμο του Θεού και αντίθεση δικαίου και ασεβούς',['wisdom','two ways','law','righteousness']),
(2,'2','The nations rage, but God establishes His anointed king; Christian reading receives the psalm messianically.','Τα έθνη ταράσσονται, αλλά ο Θεός εγκαθιστά τον χρισμένο βασιλιά Του· η χριστιανική ανάγνωση δέχεται τον ψαλμό μεσσιανικά.',['Messiah','king','nations','Son']),
(3,'3','A prayer of trust under threat, traditionally linked with David fleeing Absalom.','Προσευχή εμπιστοσύνης μέσα σε απειλή, παραδοσιακά συνδεδεμένη με τη φυγή του Δαβίδ από τον Αβεσσαλώμ.',['danger','trust','deliverance','morning prayer']),
(6,'6','A penitential cry from suffering that asks God for mercy, healing, and deliverance.','Μετανοητική κραυγή μέσα στον πόνο που ζητεί έλεος, θεραπεία και λύτρωση από τον Θεό.',['penitence','mercy','healing','sorrow']),
(22,'23','The Lord as shepherd who guides, feeds, protects, and brings the faithful into His house.','Ο Κύριος ως ποιμένας που οδηγεί, τρέφει, προστατεύει και φέρνει τον πιστό στον οίκο Του.',['shepherd','protection','trust','pasture']),
(23,'24','A liturgical hymn of God’s kingship: the earth belongs to the Lord and the King of glory enters.','Λειτουργικός ύμνος της βασιλείας του Θεού: η γη ανήκει στον Κύριο και εισέρχεται ο Βασιλεύς της δόξης.',['King of glory','creation','temple','ascension']),
(26,'27','Confidence that the Lord is light and salvation, joined to longing to dwell in God’s presence.','Βεβαιότητα ότι ο Κύριος είναι φως και σωτηρία, μαζί με πόθο για παραμονή στην παρουσία του Θεού.',['light','salvation','fear','temple','seeking God']),
(31,'32','Blessedness of forgiveness and the relief that comes from confessing sin rather than hiding it.','Μακαριότητα της συγχώρησης και ανακούφιση που έρχεται από την εξομολόγηση της αμαρτίας αντί για την απόκρυψή της.',['forgiveness','confession','repentance','blessedness']),
(37,'38','A penitential lament expressing the bodily and spiritual weight of sin and the need for God’s mercy.','Μετανοητικός θρήνος που εκφράζει το σωματικό και πνευματικό βάρος της αμαρτίας και την ανάγκη του ελέους του Θεού.',['penitence','suffering','sin','mercy']),
(50,'51','The great penitential psalm: confession, cleansing, renewal of the heart, and restoration by the Holy Spirit.','Ο κατεξοχήν μετανοητικός ψαλμός: εξομολόγηση, κάθαρση, ανακαίνιση της καρδιάς και αποκατάσταση με το Άγιο Πνεύμα.',['repentance','clean heart','Holy Spirit','mercy','daily prayer']),
(62,'63','Thirst for God in a dry land, expressing desire for God stronger than bodily need.','Δίψα για τον Θεό σε άνυδρη γη, που εκφράζει πόθο για τον Θεό ισχυρότερο από τη σωματική ανάγκη.',['thirst for God','prayer','desire','wilderness']),
(67,'68','A sweeping hymn of God’s victorious presence, care for the vulnerable, and procession to the sanctuary.','Μεγάλος ύμνος της νικηφόρας παρουσίας του Θεού, της φροντίδας για τους αδύναμους και της πορείας προς το ιερό.',['victory','procession','orphans','widows','sanctuary']),
(69,'70','A brief urgent plea for God to hurry to help and deliver the one who is afflicted.','Σύντομη και επείγουσα δέηση προς τον Θεό να σπεύσει σε βοήθεια και λύτρωση του θλιβομένου.',['help','deliverance','urgent prayer']),
(90,'91','Trust in God’s protection amid fear, danger, disease, and hidden threats; frequently used devotionally.','Εμπιστοσύνη στην προστασία του Θεού μέσα σε φόβο, κίνδυνο, ασθένεια και κρυφές απειλές· χρησιμοποιείται συχνά στην προσωπική προσευχή.',['protection','refuge','angels','fear','night']),
(102,'103','A hymn blessing God for forgiveness, healing, compassion, and fatherly mercy toward human frailty.','Ύμνος που ευλογεί τον Θεό για συγχώρηση, θεραπεία, συμπόνια και πατρικό έλεος απέναντι στην ανθρώπινη αδυναμία.',['mercy','healing','forgiveness','compassion']),
(103,'104','A majestic creation hymn praising God’s wisdom in the ordered world, used prominently at Orthodox Vespers.','Μεγαλοπρεπής ύμνος της δημιουργίας που δοξάζει τη σοφία του Θεού στην τάξη του κόσμου και χρησιμοποιείται εξέχοντα στον Ορθόδοξο Εσπερινό.',['creation','Vespers','nature','wisdom','providence']),
(118,'119','The longest psalm, an extended meditation on God’s commandments, word, guidance, suffering, and faithfulness.','Ο μεγαλύτερος ψαλμός, εκτενής μελέτη πάνω στις εντολές, τον λόγο, την καθοδήγηση, τη θλίψη και την πιστότητα του Θεού.',['law','commandments','word of God','funeral','obedience']),
(120,'121','A song of ascent that looks to the Lord as the keeper and guardian of the traveler.','Ωδή αναβαθμών που στρέφεται στον Κύριο ως φύλακα και προστάτη του οδοιπόρου.',['journey','protection','Songs of Ascents','guardian']),
(126,'127','A song teaching that human labor and security are empty without the Lord’s blessing; family and children are received as gifts.','Ωδή που διδάσκει ότι ο ανθρώπινος κόπος και η ασφάλεια είναι κενά χωρίς την ευλογία του Κυρίου· η οικογένεια και τα παιδιά δέχονται ως δώρα.',['family','work','God’s blessing','children']),
(129,'130','A cry “from the depths” for mercy and forgiveness, moving from guilt toward patient hope in God.','Κραυγή «εκ βαθέων» για έλεος και συγχώρηση, που κινείται από την ενοχή προς την υπομονετική ελπίδα στον Θεό.',['from the depths','forgiveness','hope','repentance']),
(133,'134','A short night-time call for the servants of the Lord to bless God in the sanctuary.','Σύντομη νυχτερινή πρόσκληση προς τους δούλους του Κυρίου να ευλογούν τον Θεό στο ιερό.',['night prayer','temple','blessing','Songs of Ascents']),
(142,'143','A plea for mercy and guidance when pursued and exhausted, asking God’s Spirit to lead on level ground.','Δέηση για έλεος και καθοδήγηση μέσα σε καταδίωξη και εξάντληση, με αίτημα το Πνεύμα του Θεού να οδηγήσει σε ευθεία οδό.',['mercy','guidance','Holy Spirit','morning','repentance']),
(148,'148','A cosmic summons for angels, heavens, earth, creatures, rulers, and peoples to praise the Lord.','Κοσμική πρόσκληση προς αγγέλους, ουρανούς, γη, κτίσματα, άρχοντες και λαούς να δοξολογήσουν τον Κύριο.',['praise','creation','angels','cosmic worship']),
(150,'150','The Psalter closes with an overflowing call for every kind of instrument and every breathing creature to praise God.','Το Ψαλτήρι κλείνει με πληθωρική πρόσκληση κάθε οργάνου και κάθε πνοής να δοξολογήσει τον Θεό.',['praise','music','worship','doxology'])
]
for lxx,mt,se,sg,themes in PSALMS:
    id=f'psalm-{lxx}'
    name_en=f'Psalm {lxx}' if str(lxx)==str(mt) else f'Psalm {lxx} (LXX) / {mt} (MT)'
    name_el=f'Ψαλμός {lxx}' if str(lxx)==str(mt) else f'Ψαλμός {lxx} (Ο΄) / {mt} (ΜΤ)'
    scripture=f'Psalm {lxx} (Septuagint/LXX)' + (f' / Psalm {mt} (Masoretic/common numbering)' if str(lxx)!=str(mt) else '')
    entries.append({'id':id,'name':pair(name_en,name_el),'category':'psalm','role':pair('Psalm — prayer and biblical poetry','Ψαλμός — προσευχή και βιβλική ποίηση'),'story':pair(se,sg),'feast':pair('Used in Orthodox prayer and liturgy according to the Psalter cycle','Χρησιμοποιείται στην ορθόδοξη προσευχή και λατρεία σύμφωνα με τον κύκλο του Ψαλτηρίου'),'scripture':scripture,'prayer':pair('Lord, teach us to pray with the faith, repentance, hope, and praise expressed in this Psalm, and make its wisdom fruitful in our life.','Κύριε, δίδαξέ μας να προσευχόμαστε με την πίστη, τη μετάνοια, την ελπίδα και τη δοξολογία που εκφράζει αυτός ο Ψαλμός και κάνε τη σοφία του καρποφόρα στη ζωή μας.'),'notes':pair('The entry summarizes the Psalm and does not reproduce a modern copyrighted Bible translation. Orthodox numbering follows the Septuagint; common modern numbering is shown where it differs.','Η καταχώριση συνοψίζει τον Ψαλμό και δεν αναπαράγει σύγχρονη μετάφραση της Βίβλου που μπορεί να προστατεύεται από πνευματικά δικαιώματα. Η ορθόδοξη αρίθμηση ακολουθεί τους Εβδομήκοντα· όπου διαφέρει εμφανίζεται και η συνήθης σύγχρονη αρίθμηση.'),'aliases':[f'Psalm {mt}' if str(lxx)!=str(mt) else f'Psalm {lxx}',f'Ψαλμός {mt}' if str(lxx)!=str(mt) else f'Ψαλμός {lxx}'],'venerated':False,'image':f'web/images/catalog/{id}.svg','metadata':{'type':'psalm','lxx_number':str(lxx),'common_number':str(mt),'themes_en':themes,'themes_el':themes,'liturgical_context':'Orthodox Psalter / prayer'},'knowledge':{'en':{'sections':[{'title':'Summary','text':se},{'title':'Themes','text':'; '.join(themes)},{'title':'Numbering and use','text':f'Orthodox liturgical books primarily follow Septuagint numbering. This entry labels the Psalm as {lxx} in the LXX and {mt} in common Masoretic numbering where the systems differ.'}],'sources':[]},'el':{'sections':[{'title':'Περίληψη','text':sg},{'title':'Θέματα','text':'; '.join(themes)},{'title':'Αρίθμηση και χρήση','text':f'Τα ορθόδοξα λειτουργικά βιβλία ακολουθούν κυρίως την αρίθμηση των Εβδομήκοντα. Η καταχώριση δηλώνει τον αριθμό {lxx} στους Ο΄ και {mt} στη συνήθη μασοριτική αρίθμηση όπου τα συστήματα διαφέρουν.'}],'sources':[]}},'search':' '.join([name_en,name_el,scripture,*themes])})

STORIES=[
('story-creation','Creation of the World','Η Δημιουργία του Κόσμου','Genesis 1–2','Genesis opens with God creating and ordering the heavens and earth, culminating in humanity made in the image of God and the sanctification of the seventh day.','Η Γένεση ανοίγει με τον Θεό να δημιουργεί και να τακτοποιεί τον ουρανό και τη γη, με κορύφωση τον άνθρωπο κατ’ εικόνα Θεού και τον αγιασμό της έβδομης ημέρας.',['creation','image of God','Sabbath','cosmos']),
('story-fall','The Fall of Adam and Eve','Η Πτώση του Αδάμ και της Εύας','Genesis 3','The serpent tempts the first humans to mistrust God’s command. Their disobedience brings shame, alienation, toil, and mortality, while the narrative also contains the beginning of the biblical hope for deliverance.','Ο όφις δελεάζει τους πρωτοπλάστους να δυσπιστήσουν προς την εντολή του Θεού. Η παρακοή φέρνει ντροπή, αποξένωση, κόπο και θνητότητα, ενώ η διήγηση περιέχει και την αρχή της βιβλικής ελπίδας για λύτρωση.',['fall','sin','temptation','death','promise']),
('story-cain-abel','Cain and Abel','Κάιν και Άβελ','Genesis 4:1–16','Cain becomes jealous when Abel’s offering is received favorably and murders his brother. God confronts him, exposing the growth of sin from resentment into violence while still placing a protective mark on Cain.','Ο Κάιν ζηλεύει όταν η προσφορά του Άβελ γίνεται δεκτή ευνοϊκά και σκοτώνει τον αδελφό του. Ο Θεός τον ελέγχει, αποκαλύπτοντας πώς η αμαρτία μεγαλώνει από τη μνησικακία στη βία, ενώ ταυτόχρονα θέτει προστατευτικό σημείο στον Κάιν.',['jealousy','murder','brotherhood','sin','mercy']),
('story-flood','Noah and the Flood','Ο Νώε και ο Κατακλυσμός','Genesis 6–9','Amid widespread violence, Noah is instructed to build the ark and preserve his family and living creatures through the flood. Afterward God establishes a covenant signified by the rainbow.','Μέσα σε γενικευμένη βία, ο Νώε καλείται να κατασκευάσει την κιβωτό και να διασώσει την οικογένειά του και ζωντανά πλάσματα μέσα από τον κατακλυσμό. Έπειτα ο Θεός συνάπτει διαθήκη με σημείο το ουράνιο τόξο.',['Noah','ark','flood','covenant','rainbow','animals']),
('story-babel','Tower of Babel','Πύργος της Βαβέλ','Genesis 11:1–9','Humanity attempts to build a city and tower to secure a name and prevent dispersion. The confusion of languages interrupts the project and explains the scattering of peoples within Genesis’ theological narrative.','Η ανθρωπότητα επιχειρεί να χτίσει πόλη και πύργο για να αποκτήσει όνομα και να αποφύγει τη διασπορά. Η σύγχυση των γλωσσών διακόπτει το έργο και εξηγεί τη διασπορά των λαών μέσα στη θεολογική αφήγηση της Γένεσης.',['Babel','languages','pride','nations','Pentecost typology']),
('story-call-abraham','Call of Abraham','Η Κλήση του Αβραάμ','Genesis 12','Abram is called to leave country and kindred and journey toward a land God will show him. The call is joined to promises of descendants, blessing, and a blessing extending to the families of the earth.','Ο Άβραμ καλείται να αφήσει χώρα και συγγένεια και να πορευθεί προς γη που θα του δείξει ο Θεός. Η κλήση συνδέεται με υποσχέσεις απογόνων, ευλογίας και ευλογίας που θα φτάσει στις οικογένειες της γης.',['Abraham','call','faith','promise','blessing']),
('story-binding-isaac','Binding of Isaac','Η Θυσία / Δέσμευση του Ισαάκ','Genesis 22','Abraham is tested with the command to offer Isaac, but God stops the sacrifice and provides a ram. Christian tradition reads the episode typologically in relation to Christ while affirming that the story ends with God preventing human sacrifice.','Ο Αβραάμ δοκιμάζεται με την εντολή να προσφέρει τον Ισαάκ, αλλά ο Θεός σταματά τη θυσία και παρέχει κριό. Η χριστιανική παράδοση διαβάζει το επεισόδιο τυπολογικά σε σχέση με τον Χριστό, ενώ το ίδιο το κείμενο ολοκληρώνεται με την αποτροπή της ανθρώπινης θυσίας.',['Abraham','Isaac','test','sacrifice','typology']),
('story-jacob-ladder','Jacob’s Ladder','Η Κλίμακα του Ιακώβ','Genesis 28:10–22','While fleeing, Jacob dreams of a stairway or ladder joining earth and heaven with angels ascending and descending. God renews the ancestral promises, and Jacob names the place Bethel.','Καθώς φεύγει, ο Ιακώβ ονειρεύεται κλίμακα που ενώνει γη και ουρανό, με αγγέλους να ανεβαίνουν και να κατεβαίνουν. Ο Θεός ανανεώνει τις πατριαρχικές υποσχέσεις και ο Ιακώβ ονομάζει τον τόπο Βαιθήλ.',['Jacob','ladder','angels','Bethel','promise']),
('story-joseph-egypt','Joseph in Egypt','Ο Ιωσήφ στην Αίγυπτο','Genesis 37–50','Joseph is sold by his brothers, suffers false accusation and imprisonment, rises to authority in Egypt, and eventually preserves his family during famine. The story strongly develops providence, forgiveness, and reconciliation.','Ο Ιωσήφ πωλείται από τους αδελφούς του, υπομένει ψευδή κατηγορία και φυλάκιση, ανέρχεται σε εξουσία στην Αίγυπτο και τελικά διασώζει την οικογένειά του σε περίοδο πείνας. Η διήγηση αναπτύσσει έντονα την πρόνοια, τη συγχώρηση και τη συμφιλίωση.',['Joseph','Egypt','providence','forgiveness','famine','reconciliation']),
('story-burning-bush','Moses and the Burning Bush','Ο Μωυσής και η Φλεγόμενη Βάτος','Exodus 3–4','God calls Moses from the bush that burns without being consumed, reveals the divine name, and commissions him to confront Pharaoh and lead Israel out of slavery.','Ο Θεός καλεί τον Μωυσή από τη βάτο που φλέγεται χωρίς να κατακαίγεται, αποκαλύπτει το θείο όνομα και τον αποστέλλει να αντιμετωπίσει τον Φαραώ και να οδηγήσει τον Ισραήλ έξω από τη δουλεία.',['Moses','burning bush','divine name','calling','Exodus']),
('story-passover','Passover and the Exodus','Το Πάσχα και η Έξοδος','Exodus 11–13','On the night of deliverance from Egypt, Israel marks the Passover meal and prepares to depart. The event becomes foundational to biblical memory and, in Christian liturgical interpretation, a major type of Christ’s Pascha.','Τη νύχτα της λύτρωσης από την Αίγυπτο, ο Ισραήλ τελεί το Πάσχα και ετοιμάζεται να αναχωρήσει. Το γεγονός γίνεται θεμελιώδες στη βιβλική μνήμη και, στη χριστιανική λειτουργική ερμηνεία, σημαντικός τύπος του Πάσχα του Χριστού.',['Passover','Exodus','deliverance','Pascha','lamb']),
('story-red-sea','Crossing of the Red Sea','Η Διάβαση της Ερυθράς Θάλασσας','Exodus 14–15','Israel escapes Pharaoh’s pursuing army through the sea and responds with a song of victory. Christian baptismal and Paschal tradition reads the crossing as an image of deliverance from bondage and death.','Ο Ισραήλ διαφεύγει από τον στρατό του Φαραώ περνώντας μέσα από τη θάλασσα και απαντά με ύμνο νίκης. Η χριστιανική βαπτισματική και πασχάλια παράδοση διαβάζει τη διάβαση ως εικόνα λύτρωσης από δουλεία και θάνατο.',['Red Sea','Moses','deliverance','baptism','Pascha']),
('story-ten-commandments','Giving of the Ten Commandments','Η Παράδοση των Δέκα Εντολών','Exodus 19–20; Deuteronomy 5','At Sinai the covenant people receive commandments concerning worship of God and life with one another. The Decalogue becomes a foundational summary of covenant obedience.','Στο Σινά ο λαός της διαθήκης λαμβάνει εντολές για τη λατρεία του Θεού και τη ζωή με τον πλησίον. Ο Δεκάλογος γίνεται θεμελιώδης σύνοψη της υπακοής στη διαθήκη.',['Ten Commandments','Sinai','covenant','law','Moses']),
('story-bronze-serpent','Bronze Serpent in the Wilderness','Ο Χάλκινος Όφις στην Έρημο','Numbers 21:4–9; John 3:14–15','After deadly snake bites in the wilderness, Moses makes a bronze serpent according to God’s command and those who look toward it live. John’s Gospel later uses the lifting up of the serpent as a typological image for Christ’s lifting up.','Μετά από θανατηφόρα δαγκώματα φιδιών στην έρημο, ο Μωυσής κατασκευάζει χάλκινο όφι σύμφωνα με την εντολή του Θεού και όσοι στρέφονται προς αυτόν ζουν. Το κατά Ιωάννην Ευαγγέλιο χρησιμοποιεί αργότερα την ύψωση του όφεως ως τυπολογική εικόνα της ύψωσης του Χριστού.',['bronze serpent','Moses','healing','Cross typology','John 3']),
('story-balaam-donkey','Balaam and the Donkey','Ο Βαλαάμ και η Όνος','Numbers 22–24','Balaam is summoned to curse Israel, but on the journey his donkey perceives the angelic danger before he does. The story reverses expectations and ends with Balaam speaking blessing rather than the desired curse.','Ο Βαλαάμ καλείται να καταραστεί τον Ισραήλ, αλλά στο ταξίδι η όνος του αντιλαμβάνεται τον αγγελικό κίνδυνο πριν από τον ίδιο. Η διήγηση ανατρέπει τις προσδοκίες και καταλήγει με τον Βαλαάμ να εκφωνεί ευλογία αντί για την επιθυμητή κατάρα.',['Balaam','donkey','angel','blessing','prophecy']),
('story-jericho','Fall of Jericho','Η Πτώση της Ιεριχούς','Joshua 6','Israel circles Jericho according to the commanded ritual, and the city’s defenses fall. The episode belongs to the conquest narrative and requires careful reading within the theological and historical world of Joshua.','Ο Ισραήλ περιέρχεται την Ιεριχώ σύμφωνα με την εντολή και τα οχυρά της πόλης καταρρέουν. Το επεισόδιο ανήκει στη διήγηση της κατάκτησης και απαιτεί προσεκτική ανάγνωση μέσα στον θεολογικό και ιστορικό κόσμο του Ιησού του Ναυή.',['Joshua','Jericho','trumpets','conquest','Rahab']),
('story-gideon-fleece','Gideon and the Fleece','Ο Γεδεών και ο Πόκος','Judges 6:36–40','Gideon asks for confirming signs involving dew on a fleece before acting against Midian. The episode is part of a larger story in which God reduces Gideon’s army so victory cannot be credited simply to military strength.','Ο Γεδεών ζητεί επιβεβαιωτικά σημεία με δρόσο πάνω σε πόκο πριν ενεργήσει κατά των Μαδιανιτών. Το επεισόδιο ανήκει σε μεγαλύτερη διήγηση όπου ο Θεός μειώνει τον στρατό του Γεδεών ώστε η νίκη να μην αποδοθεί απλώς στη στρατιωτική δύναμη.',['Gideon','fleece','sign','Midian','trust']),
('story-samson','Samson and Delilah','Ο Σαμψών και η Δαλιδά','Judges 13–16','Samson’s extraordinary strength is intertwined with a Nazirite calling, impulsiveness, conflict with the Philistines, betrayal by Delilah, capture, and a final act that destroys the Philistine temple at the cost of his own life.','Η εξαιρετική δύναμη του Σαμψών συνδέεται με ναζιραϊκή κλήση, παρορμητικότητα, σύγκρουση με τους Φιλισταίους, προδοσία από τη Δαλιδά, αιχμαλωσία και τελική πράξη που καταστρέφει τον φιλισταϊκό ναό με κόστος τη δική του ζωή.',['Samson','Delilah','strength','Nazirite','Philistines']),
('story-ruth-naomi','Ruth and Naomi','Η Ρουθ και η Ναομί','Ruth 1–4','Ruth, a Moabite widow, remains faithful to Naomi, enters Israel, gleans in the fields of Boaz, and becomes part of the family line leading to David. The story highlights loyalty, providence, generosity, and the welcome of an outsider.','Η Ρουθ, Μωαβίτισσα χήρα, παραμένει πιστή στη Ναομί, εισέρχεται στον Ισραήλ, σταχυολογεί στα χωράφια του Βοόζ και γίνεται μέρος της γενεαλογικής γραμμής που οδηγεί στον Δαβίδ. Η διήγηση τονίζει πιστότητα, πρόνοια, γενναιοδωρία και υποδοχή του ξένου.',['Ruth','Naomi','Boaz','loyalty','genealogy of David']),
('story-david-goliath','David and Goliath','Ο Δαβίδ και ο Γολιάθ','1 Samuel / 1 Kingdoms 17','Young David confronts the Philistine champion Goliath without conventional armor, trusting in God rather than military appearance. His victory becomes a major episode in the rise of David.','Ο νεαρός Δαβίδ αντιμετωπίζει τον Φιλισταίο πρωταθλητή Γολιάθ χωρίς συμβατική πανοπλία, εμπιστευόμενος τον Θεό και όχι τη στρατιωτική εμφάνιση. Η νίκη του γίνεται σημαντικό επεισόδιο στην άνοδο του Δαβίδ.',['David','Goliath','faith','courage','Philistines']),
('story-elijah-carmel','Elijah on Mount Carmel','Ο Ηλίας στο Όρος Κάρμηλος','1 Kings / 3 Kingdoms 18','Elijah challenges the prophets of Baal on Mount Carmel, and the narrative contrasts idolatry with the God of Israel who answers. The episode ends with renewed rain after drought.','Ο Ηλίας προκαλεί τους προφήτες του Βάαλ στο Όρος Κάρμηλος και η διήγηση αντιπαραθέτει την ειδωλολατρία με τον Θεό του Ισραήλ που απαντά. Το επεισόδιο ολοκληρώνεται με την επιστροφή της βροχής μετά την ξηρασία.',['Elijah','Carmel','Baal','fire','rain','idolatry']),
('story-jonah-nineveh','Jonah and Nineveh','Ο Ιωνάς και η Νινευή','Jonah 1–4','Jonah flees his prophetic commission, survives the sea after being swallowed by a great fish, preaches to Nineveh, and then struggles with God’s mercy toward repentant enemies.','Ο Ιωνάς φεύγει από την προφητική αποστολή του, διασώζεται στη θάλασσα αφού καταποθεί από μεγάλο κήτος, κηρύττει στη Νινευή και έπειτα δυσκολεύεται να δεχθεί το έλεος του Θεού προς μετανοημένους εχθρούς.',['Jonah','Nineveh','great fish','repentance','mercy']),
('story-three-youths','Three Holy Youths in the Fiery Furnace','Οι Τρεις Άγιοι Παίδες στην Κάμινο','Daniel 3; Song of the Three Holy Youths','Hananiah, Azariah, and Mishael refuse idolatry and are cast into a furnace, yet are preserved while praising God. The episode is prominent in Orthodox hymnography, especially its canticle of cosmic praise.','Ο Ανανίας, ο Αζαρίας και ο Μισαήλ αρνούνται την ειδωλολατρία και ρίχνονται σε κάμινο, αλλά διαφυλάσσονται ενώ δοξολογούν τον Θεό. Το επεισόδιο έχει εξέχουσα θέση στην ορθόδοξη υμνογραφία, ιδιαίτερα μέσω του ύμνου κοσμικής δοξολογίας.',['Daniel','fiery furnace','three youths','idolatry','praise']),
('story-daniel-lions','Daniel in the Lions’ Den','Ο Δανιήλ στον Λάκκο των Λεόντων','Daniel 6','Daniel continues praying despite a royal prohibition and is cast among lions. God preserves him, and the plot exposes the malice of his accusers while affirming steadfast prayer.','Ο Δανιήλ συνεχίζει να προσεύχεται παρά τη βασιλική απαγόρευση και ρίχνεται σε λάκκο λεόντων. Ο Θεός τον διαφυλάσσει, και η διήγηση αποκαλύπτει την κακία των κατηγόρων του ενώ επιβεβαιώνει τη σταθερότητα στην προσευχή.',['Daniel','lions','prayer','persecution','deliverance']),
('story-esther','Esther and the Deliverance of Her People','Η Εσθήρ και η Σωτηρία του Λαού της','Esther','Queen Esther risks approaching the king to expose the plot against her people. The reversal of Haman’s scheme becomes a story of courage, providence, communal fasting, and deliverance associated with Purim in Jewish tradition.','Η βασίλισσα Εσθήρ διακινδυνεύει να παρουσιαστεί στον βασιλιά για να αποκαλύψει τη συνωμοσία εναντίον του λαού της. Η ανατροπή του σχεδίου του Αμάν γίνεται διήγηση θάρρους, πρόνοιας, κοινής νηστείας και σωτηρίας, συνδεδεμένη με το Πουρίμ στην ιουδαϊκή παράδοση.',['Esther','Haman','courage','fasting','deliverance']),
('story-tobit-raphael','Tobit, Tobias, and Raphael','Ο Τωβίτ, ο Τωβίας και ο Ραφαήλ','Tobit 1–12','The book of Tobit follows a righteous family through blindness, grief, travel, marriage, danger, healing, and almsgiving. Raphael accompanies Tobias in disguise and later reveals his angelic identity.','Το βιβλίο του Τωβίτ ακολουθεί μια δίκαιη οικογένεια μέσα από τύφλωση, θλίψη, ταξίδι, γάμο, κίνδυνο, θεραπεία και ελεημοσύνη. Ο Ραφαήλ συνοδεύει τον Τωβία μεταμφιεσμένος και αργότερα αποκαλύπτει την αγγελική του ταυτότητα.',['Tobit','Tobias','Raphael','healing','marriage','almsgiving']),
('story-judith','Judith and Holofernes','Η Ιουδίθ και ο Ολοφέρνης','Judith','Judith, a devout widow, enters the enemy camp and uses courage and strategy to defeat Holofernes, leading to the deliverance of her people. The book combines prayer, fasting, courage, and dramatic reversal.','Η Ιουδίθ, ευσεβής χήρα, εισέρχεται στο εχθρικό στρατόπεδο και χρησιμοποιεί θάρρος και στρατηγική για να νικήσει τον Ολοφέρνη, οδηγώντας στη σωτηρία του λαού της. Το βιβλίο συνδυάζει προσευχή, νηστεία, ανδρεία και δραματική ανατροπή.',['Judith','Holofernes','courage','fasting','deliverance']),
('story-maccabean-martyrs','Maccabean Martyrs and the Mother','Οι Μακκαβαίοι Μάρτυρες και η Μητέρα τους','2 Maccabees 7; 4 Maccabees','A mother and her sons endure torture rather than abandon the ancestral faith. Their witness became important in Christian reflection on martyrdom, resurrection hope, and faithfulness under persecution.','Μια μητέρα και οι γιοι της υπομένουν βασανιστήρια αντί να εγκαταλείψουν την πατροπαράδοτη πίστη. Η μαρτυρία τους έγινε σημαντική στη χριστιανική σκέψη για το μαρτύριο, την ελπίδα της ανάστασης και την πιστότητα μέσα στον διωγμό.',['Maccabees','martyrdom','mother and sons','resurrection','persecution']),
('story-cana','Wedding at Cana','Ο Γάμος στην Κανά','John 2:1–11','At a wedding feast, Jesus transforms water into wine after His mother brings the lack of wine to His attention. John presents the event as the first of the signs revealing Christ’s glory.','Σε γαμήλια εορτή, ο Ιησούς μεταβάλλει νερό σε κρασί αφού η Μητέρα Του Του γνωστοποιεί την έλλειψη κρασιού. Ο Ιωάννης παρουσιάζει το γεγονός ως το πρώτο σημείο που φανερώνει τη δόξα του Χριστού.',['Cana','wedding','Theotokos','water into wine','signs']),
('story-raising-lazarus','Raising of Lazarus','Η Ανάσταση του Λαζάρου','John 11','Jesus comes to Bethany after Lazarus has died, encounters Martha and Mary in grief, weeps, and calls Lazarus from the tomb. The sign points toward Christ as resurrection and life and leads directly into the final conflict in John’s Gospel.','Ο Ιησούς έρχεται στη Βηθανία μετά τον θάνατο του Λαζάρου, συναντά τη Μάρθα και τη Μαρία μέσα στο πένθος, δακρύζει και καλεί τον Λάζαρο από τον τάφο. Το σημείο φανερώνει τον Χριστό ως ανάσταση και ζωή και οδηγεί άμεσα προς την τελική σύγκρουση στο κατά Ιωάννην.',['Lazarus','Bethany','resurrection','Martha','Mary','Holy Week'])
]
for id,en,el,scripture,se,sg,themes in STORIES:
    entries.append({'id':id,'name':pair(en,el),'category':'scripture-story','role':pair('Biblical story / episode','Βιβλική διήγηση / επεισόδιο'),'story':pair(se,sg),'feast':pair('Read in Scripture; some episodes have specific liturgical commemorations','Αναγιγνώσκεται στη Γραφή· ορισμένα επεισόδια έχουν ιδιαίτερη λειτουργική μνήμη'),'scripture':scripture,'prayer':pair('Lord, teach us through this biblical story to trust You, repent of sin, love our neighbor, and recognize Your saving work.','Κύριε, δίδαξέ μας μέσα από αυτή τη βιβλική διήγηση να Σε εμπιστευόμαστε, να μετανοούμε για την αμαρτία, να αγαπούμε τον πλησίον και να αναγνωρίζουμε το σωτήριο έργο Σου.'),'notes':pair('This entry is a concise paraphrase and study guide. It does not replace reading the cited biblical text in full.','Η καταχώριση είναι σύντομη παράφραση και οδηγός μελέτης. Δεν αντικαθιστά την πλήρη ανάγνωση του παρατιθέμενου βιβλικού κειμένου.'),'aliases':[],'venerated':False,'image':f'web/images/catalog/{id}.svg','metadata':{'type':'scripture story','themes_en':themes,'themes_el':themes},'knowledge':{'en':{'sections':[{'title':'What happens','text':se},{'title':'Themes','text':'; '.join(themes)},{'title':'Read the source','text':f'Read {scripture} for the full narrative and literary context.'}],'sources':[]},'el':{'sections':[{'title':'Τι συμβαίνει','text':sg},{'title':'Θέματα','text':'; '.join(themes)},{'title':'Ανάγνωση της πηγής','text':f'Διαβάστε {scripture} για την πλήρη διήγηση και το λογοτεχνικό της πλαίσιο.'}],'sources':[]}},'search':' '.join([en,el,scripture,*themes])})

# Greek theme labels for entries whose English keywords would otherwise leak into the Greek dossier.
GREEK_THEME_FIXES={
 'parable-wicked-tenants':['προφήτες','Υιός','απόρριψη','κρίση','αμπελώνας'],
 'parable-pharisee-publican':['ταπείνωση','μετάνοια','προσευχή','Μεγάλη Τεσσαρακοστή','αυτοδικαίωση'],
 'parable-persistent-widow':['επίμονη προσευχή','δικαιοσύνη','πίστη','επιμονή'],
 'parable-rich-man-lazarus':['φτωχός','πλούτος','μετά θάνατον ζωή','μετάνοια','Μωυσής και προφήτες'],
 'psalm-3':['κίνδυνος','εμπιστοσύνη','λύτρωση','πρωινή προσευχή'],
 'psalm-50':['μετάνοια','καθαρή καρδιά','Άγιο Πνεύμα','έλεος','καθημερινή προσευχή'],
 'psalm-62':['δίψα για τον Θεό','προσευχή','πόθος','έρημος'],
 'psalm-69':['βοήθεια','λύτρωση','επείγουσα προσευχή'],
 'psalm-133':['νυχτερινή προσευχή','ναός','ευλογία','Ωδές των Αναβαθμών'],
 'story-daniel-lions':['Δανιήλ','λιοντάρια','προσευχή','διωγμός','λύτρωση'],
}
for e in entries:
    themes=GREEK_THEME_FIXES.get(e['id'])
    if not themes: continue
    e.setdefault('metadata',{})['themes_el']=themes
    try:
        e['knowledge']['el']['sections'][1]['text']='; '.join(themes)
    except (KeyError,IndexError,TypeError):
        pass

# ensure no accidental duplicate IDs inside the new layer
ids=[e['id'] for e in entries]
if len(ids)!=len(set(ids)):
    from collections import Counter
    raise SystemExit('duplicate v24 ids: '+str([k for k,v in Counter(ids).items() if v>1]))

OUT.write_text('window.ORTHODOX_V24_EXPANSION = '+json.dumps(entries,ensure_ascii=False,separators=(',',':'))+';\n',encoding='utf-8')
print(f'Wrote {len(entries)} v24 expansion entries -> {OUT.relative_to(ROOT)}')
